// packages/svelte/src/components/chat/CopilotChatToolCallsView.svelte
<script lang="ts">
  import type { AssistantMessage, Message, ToolCall, ToolMessage } from "@ag-ui/core";
  import { DEFAULT_AGENT_ID } from "@copilotkit/shared";
  import { ToolCallStatus } from "@copilotkit/core";
  import { partialJSONParse } from "@copilotkit/shared";
  import { useCopilotKit } from "../../providers/useCopilotKit";
  import { getChatConfig } from "./chat-config-context.svelte";
  import type { CopilotChatToolCallRenderSlotProps } from "./types";
  import type { Snippet } from "svelte";
  import { IconCheckCircle, IconCircle, IconLoader2 } from "../icons";

  let {
    message,
    messages = [] as Message[],
    toolCall,
  }: {
    message: AssistantMessage;
    messages?: Message[];
    toolCall?: Snippet<[CopilotChatToolCallRenderSlotProps]>;
  } = $props();

  const { copilotkit, executingToolCallIds } = useCopilotKit();

  function findToolMessage(toolCallId: string): ToolMessage | undefined {
    return messages.find(
      (msg) =>
        msg.role === "tool" &&
        (msg as ToolMessage).toolCallId === toolCallId,
    ) as ToolMessage | undefined;
  }

  function isExecuting(toolCallId: string): boolean {
    return executingToolCallIds.has(toolCallId);
  }

  function getToolResult(toolCallId: string): string | undefined {
    return findToolMessage(toolCallId)?.content;
  }

  function getRenderProps(tc: ToolCall): CopilotChatToolCallRenderSlotProps {
    const toolMessage = findToolMessage(tc.id);
    const parsedArgs = partialJSONParse(tc.function.arguments);

    if (toolMessage) {
      return {
        name: tc.function.name,
        args: parsedArgs,
        status: ToolCallStatus.Complete,
        result: toolMessage.content,
        toolCall: tc,
        toolMessage,
      };
    }

    return {
      name: tc.function.name,
      args: parsedArgs,
      status: isExecuting(tc.id) ? ToolCallStatus.Executing : ToolCallStatus.InProgress,
      result: undefined,
      toolCall: tc,
      toolMessage: undefined,
    };
  }
</script>

{#each message.toolCalls ?? [] as tc (tc.id)}
  {#if toolCall}
    {@render toolCall(getRenderProps(tc))}
  {:else}
    <div class="cpk:flex cpk:items-center cpk:gap-2 cpk:py-1 cpk:text-sm cpk:text-muted-foreground">
      {#if isExecuting(tc.id)}
        <IconLoader2 class="cpk:size-4 cpk:animate-spin" />
        <span>{tc.function.name}</span>
      {:else if getToolResult(tc.id)}
        <IconCheckCircle class="cpk:size-4 cpk:text-green-500" />
        <span>{tc.function.name}</span>
      {:else}
        <IconCircle class="cpk:size-4 cpk:text-muted-foreground" />
        <span>{tc.function.name}</span>
      {/if}
    </div>
  {/if}
{/each}

// packages/vue/src/components/chat/CopilotChatToolCallsView.vue
<script setup lang="ts">
import type {
  AssistantMessage,
  Message,
  ToolCall,
  ToolMessage,
} from "@ag-ui/core";
import { DEFAULT_AGENT_ID } from "@copilotkit/shared";
import { ToolCallStatus } from "@copilotkit/core";
import { partialJSONParse } from "@copilotkit/shared";
import { useCopilotKit } from "../../providers/useCopilotKit";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import type { CopilotChatToolCallRenderSlotProps } from "./types";
import type { VueToolCallRenderer } from "../../types";
import type { VueToolCallRendererRenderProps } from "../../types";

const props = withDefaults(
  defineProps<{
    message: AssistantMessage;
    messages?: Message[];
  }>(),
  {
    messages: () => [],
  },
);

defineSlots<{
  "tool-call"?: (props: CopilotChatToolCallRenderSlotProps) => unknown;
  [key: `tool-call-${string}`]: (
    props: CopilotChatToolCallRenderSlotProps,
  ) => unknown;
}>();

const { copilotkit, executingToolCallIds } = useCopilotKit();
const config = useCopilotChatConfiguration();

function findToolMessage(toolCallId: string): ToolMessage | undefined {
  return props.messages.find(
    (message) =>
      message.role === "tool" &&
      (message as ToolMessage).toolCallId === toolCallId,
  ) as ToolMessage | undefined;
}

function getSlotName(toolName: string): `tool-call-${string}` {
  return `tool-call-${toolName}`;
}

function isExecutingToolCall(toolCallId: string): boolean {
  return executingToolCallIds.value.has(toolCallId);
}

function getToolResultContent(toolCallId: string): string | undefined {
  return findToolMessage(toolCallId)?.content;
}

function getRenderProps(
  toolCall: ToolCall,
): CopilotChatToolCallRenderSlotProps {
  const toolMessage = findToolMessage(toolCall.id);
  const parsedArgs = partialJSONParse(toolCall.function.arguments);

  if (toolMessage) {
    return {
      name: toolCall.function.name,
      args: parsedArgs,
      status: ToolCallStatus.Complete,
      result: toolMessage.content,
      toolCall,
      toolMessage,
    };
  }

  const isExecuting = isExecutingToolCall(toolCall.id);
  return {
    name: toolCall.function.name,
    args: parsedArgs,
    status: isExecuting ? ToolCallStatus.Executing : ToolCallStatus.InProgress,
    result: undefined,
    toolCall,
    toolMessage: undefined,
  };
}

function getCoreRenderProps(
  toolCall: ToolCall,
): VueToolCallRendererRenderProps<unknown> {
  const toolMessage = findToolMessage(toolCall.id);
  const parsedArgs = partialJSONParse(toolCall.function.arguments);

  if (toolMessage) {
    return {
      name: toolCall.function.name,
      args: parsedArgs,
      status: ToolCallStatus.Complete,
      result: toolMessage.content,
    };
  }

  const isExecuting = isExecutingToolCall(toolCall.id);
  if (isExecuting) {
    return {
      name: toolCall.function.name,
      args: parsedArgs,
      status: ToolCallStatus.Executing,
      result: undefined,
    };
  }

  return {
    name: toolCall.function.name,
    args: parsedArgs && typeof parsedArgs === "object" ? parsedArgs : {},
    status: ToolCallStatus.InProgress,
    result: undefined,
  };
}

function getCoreRenderConfig(
  toolCall: ToolCall,
): VueToolCallRenderer<unknown> | undefined {
  const renderToolCalls = copilotkit.value.renderToolCalls;
  const agentId = config.value?.agentId ?? DEFAULT_AGENT_ID;
  const exactMatches = renderToolCalls.filter(
    (renderConfig) => renderConfig.name === toolCall.function.name,
  );

  return (
    exactMatches.find((renderConfig) => renderConfig.agentId === agentId) ??
    exactMatches.find((renderConfig) => !renderConfig.agentId) ??
    exactMatches[0] ??
    renderToolCalls.find((renderConfig) => renderConfig.name === "*")
  );
}
</script>

<template>
  <template v-for="toolCall in message.toolCalls ?? []" :key="toolCall.id">
    <slot
      :name="getSlotName(toolCall.function.name)"
      v-bind="getRenderProps(toolCall)"
    >
      <slot name="tool-call" v-bind="getRenderProps(toolCall)">
        <component
          :is="getCoreRenderConfig(toolCall)?.render"
          v-if="getCoreRenderConfig(toolCall)"
          v-bind="getCoreRenderProps(toolCall)"
          v-memo="[
            toolCall.id,
            toolCall.function.arguments,
            getToolResultContent(toolCall.id),
            isExecutingToolCall(toolCall.id),
            getCoreRenderConfig(toolCall)?.render,
          ]"
        />
      </slot>
    </slot>
  </template>
</template>
