// packages/react-core/src/v2/components/chat/CopilotChatToggleButton.tsx
import type { MouseEvent } from "react";
import React, { useState } from "react";
import { MessageCircle, X } from "lucide-react";

import type { SlotValue } from "../../lib/slots";
import { renderSlot } from "../../lib/slots";
import { cn } from "../../lib/utils";
import {
  CopilotChatDefaultLabels,
  useCopilotChatConfiguration,
} from "../../providers/CopilotChatConfigurationProvider";

const DefaultOpenIcon: React.FC<React.SVGProps<SVGSVGElement>> = ({
  className,
  ...props
}) => (
  <MessageCircle
    className={cn("cpk:size-6", className)}
    strokeWidth={1.75}
    fill="currentColor"
    {...props}
  />
);

const DefaultCloseIcon: React.FC<React.SVGProps<SVGSVGElement>> = ({
  className,
  ...props
}) => (
  <X className={cn("cpk:size-6", className)} strokeWidth={1.75} {...props} />
);

DefaultOpenIcon.displayName = "CopilotChatToggleButton.OpenIcon";
DefaultCloseIcon.displayName = "CopilotChatToggleButton.CloseIcon";

export interface CopilotChatToggleButtonProps extends Omit<
  React.ButtonHTMLAttributes<HTMLButtonElement>,
  "children"
> {
  /** Optional slot override for the chat (closed) icon. */
  openIcon?: SlotValue<typeof DefaultOpenIcon>;
  /** Optional slot override for the close icon. */
  closeIcon?: SlotValue<typeof DefaultCloseIcon>;
}

const ICON_TRANSITION_STYLE: React.CSSProperties = Object.freeze({
  transition:
    "opacity 120ms ease-out, transform 260ms cubic-bezier(0.22, 1, 0.36, 1)",
});

const ICON_WRAPPER_BASE =
  "cpk:pointer-events-none cpk:absolute cpk:inset-0 cpk:flex cpk:items-center cpk:justify-center cpk:will-change-transform";

const BUTTON_BASE_CLASSES = cn(
  "copilotKitButton",
  "cpk:fixed cpk:bottom-6 cpk:right-6 cpk:z-[1100] cpk:flex cpk:h-14 cpk:w-14 cpk:items-center cpk:justify-center",
  "cpk:rounded-full cpk:bg-primary cpk:text-primary-foreground",
  "cpk:shadow-[0_1px_2px_0_rgb(0_0_0/0.10),0_8px_24px_-6px_rgb(0_0_0/0.25)] cpk:ring-1 cpk:ring-foreground/5",
  "cpk:transition-[transform,box-shadow] cpk:duration-200 cpk:ease-out",
  "cpk:hover:scale-[1.04] cpk:hover:shadow-[0_2px_4px_0_rgb(0_0_0/0.12),0_12px_32px_-8px_rgb(0_0_0/0.30)]",
  "cpk:cursor-pointer",
  "cpk:active:scale-[0.96]",
  "cpk:focus-visible:outline-none cpk:focus-visible:ring-2 cpk:focus-visible:ring-primary/50 cpk:focus-visible:ring-offset-2 cpk:focus-visible:ring-offset-background",
  "cpk:disabled:pointer-events-none cpk:disabled:opacity-60",
);

export const CopilotChatToggleButton = React.forwardRef<
  HTMLButtonElement,
  CopilotChatToggleButtonProps
>(function CopilotChatToggleButton(
  { openIcon, closeIcon, className, ...buttonProps },
  ref,
) {
  const { onClick, type, disabled, ...restProps } = buttonProps;

  const configuration = useCopilotChatConfiguration();
  const labels = configuration?.labels ?? CopilotChatDefaultLabels;

  const [fallbackOpen, setFallbackOpen] = useState(false);

  const isOpen = configuration?.isModalOpen ?? fallbackOpen;
  const setModalOpen = configuration?.setModalOpen ?? setFallbackOpen;

  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (disabled) {
      return;
    }

    if (onClick) {
      onClick(event);
    }

    if (event.defaultPrevented) {
      return;
    }

    const nextOpen = !isOpen;
    setModalOpen(nextOpen);
  };

  const renderedOpenIcon = renderSlot(openIcon, DefaultOpenIcon, {
    className: "cpk:size-6",
    "aria-hidden": true,
    focusable: false,
  });

  const renderedCloseIcon = renderSlot(closeIcon, DefaultCloseIcon, {
    className: "cpk:size-6",
    "aria-hidden": true,
    focusable: false,
  });

  const openIconElement = (
    <span
      aria-hidden="true"
      data-slot="chat-toggle-button-open-icon"
      className={ICON_WRAPPER_BASE}
      style={{
        ...ICON_TRANSITION_STYLE,
        opacity: isOpen ? 0 : 1,
        transform: `scale(${isOpen ? 0.75 : 1}) rotate(${isOpen ? 90 : 0}deg)`,
      }}
    >
      {renderedOpenIcon}
    </span>
  );

  const closeIconElement = (
    <span
      aria-hidden="true"
      data-slot="chat-toggle-button-close-icon"
      className={ICON_WRAPPER_BASE}
      style={{
        ...ICON_TRANSITION_STYLE,
        opacity: isOpen ? 1 : 0,
        transform: `scale(${isOpen ? 1 : 0.75}) rotate(${isOpen ? 0 : -90}deg)`,
      }}
    >
      {renderedCloseIcon}
    </span>
  );

  return (
    <button
      ref={ref}
      type={type ?? "button"}
      data-copilotkit
      data-testid="copilot-chat-toggle"
      data-slot="chat-toggle-button"
      data-state={isOpen ? "open" : "closed"}
      className={cn(BUTTON_BASE_CLASSES, className)}
      aria-label={
        isOpen ? labels.chatToggleCloseLabel : labels.chatToggleOpenLabel
      }
      aria-pressed={isOpen}
      disabled={disabled}
      onClick={handleClick}
      {...restProps}
    >
      {openIconElement}
      {closeIconElement}
    </button>
  );
});
CopilotChatToggleButton.displayName = "CopilotChatToggleButton";
export default CopilotChatToggleButton;

export {
  DefaultOpenIcon as CopilotChatToggleButtonOpenIcon,
  DefaultCloseIcon as CopilotChatToggleButtonCloseIcon,
};

// packages/angular/src/lib/components/modal/copilot-chat-toggle-button.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

import { CopilotIcon, MessageCircle, X } from "../icons/copilot-icon";

const ICON_TRANSITION =
  "opacity 120ms ease-out, transform 260ms cubic-bezier(0.22, 1, 0.36, 1)";

/**
 * Round launcher for `<copilot-popup>` / `<copilot-sidebar>`, matching React's
 * `CopilotChatToggleButton`: a chat bubble that turns into an X while open.
 * Applied to a native `<button>` so the host keeps button semantics.
 */
@Component({
  selector: "button[copilotChatToggleButton]",
  imports: [CopilotIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    type: "button",
    class:
      "copilotKitButton cpk:fixed cpk:bottom-6 cpk:right-6 cpk:z-[1100] cpk:flex cpk:h-14 cpk:w-14 cpk:items-center cpk:justify-center cpk:rounded-full cpk:border-0 cpk:bg-primary cpk:text-primary-foreground cpk:shadow-[0_1px_2px_0_rgb(0_0_0/0.10),0_8px_24px_-6px_rgb(0_0_0/0.25)] cpk:ring-1 cpk:ring-foreground/5 cpk:transition-[transform,scale,box-shadow] cpk:duration-200 cpk:ease-out cpk:hover:scale-[1.04] cpk:hover:shadow-[0_2px_4px_0_rgb(0_0_0/0.12),0_12px_32px_-8px_rgb(0_0_0/0.30)] cpk:cursor-pointer cpk:active:scale-[0.96] cpk:focus-visible:outline-none cpk:focus-visible:ring-2 cpk:focus-visible:ring-primary/50 cpk:focus-visible:ring-offset-2 cpk:focus-visible:ring-offset-background cpk:disabled:pointer-events-none cpk:disabled:opacity-60 cpk:data-[position=left]:left-6 cpk:data-[position=left]:right-auto",
    "data-copilotkit": "",
    "data-testid": "copilot-chat-toggle",
    "data-slot": "chat-toggle-button",
    "[attr.data-state]": "open() ? 'open' : 'closed'",
    "[attr.data-position]": "position()",
    "[attr.aria-label]": "open() ? 'Close chat' : 'Open chat'",
    "[attr.aria-expanded]": "open()",
  },
  template: `
    <span
      aria-hidden="true"
      data-slot="chat-toggle-button-open-icon"
      class="cpk:pointer-events-none cpk:absolute cpk:inset-0 cpk:flex cpk:items-center cpk:justify-center cpk:will-change-transform cpk:[&_svg]:fill-current cpk:[&_svg]:stroke-[1.75]"
      [style.transition]="transition"
      [style.opacity]="open() ? 0 : 1"
      [style.transform]="
        open() ? 'scale(0.75) rotate(90deg)' : 'scale(1) rotate(0deg)'
      "
    >
      <copilot-icon [img]="MessageCircle" [size]="24" />
    </span>
    <span
      aria-hidden="true"
      data-slot="chat-toggle-button-close-icon"
      class="cpk:pointer-events-none cpk:absolute cpk:inset-0 cpk:flex cpk:items-center cpk:justify-center cpk:will-change-transform cpk:[&_svg]:stroke-[1.75]"
      [style.transition]="transition"
      [style.opacity]="open() ? 1 : 0"
      [style.transform]="
        open() ? 'scale(1) rotate(0deg)' : 'scale(0.75) rotate(-90deg)'
      "
    >
      <copilot-icon [img]="X" [size]="24" />
    </span>
  `,
})
export class CopilotChatToggleButton {
  readonly open = input(false);
  readonly position = input<"left" | "right">("right");

  protected readonly MessageCircle = MessageCircle;
  protected readonly X = X;
  protected readonly transition = ICON_TRANSITION;
}
