// examples/integrations/langgraph-python/apps/app/src/components/generative-ui/a2ui-progress.tsx
"use client";

import { memo, useRef } from "react";

interface A2UIProgressProps {
  parameters: unknown;
}

/**
 * Visual progress indicator for dynamic A2UI generation.
 * Shows a skeleton wireframe that represents components being assembled.
 */
export const A2UIProgress = memo(function A2UIProgress({
  parameters,
}: A2UIProgressProps) {
  const lastRef = useRef({ time: 0, tokens: 0 });
  const now = Date.now();

  let { tokens } = lastRef.current;
  if (now - lastRef.current.time > 200) {
    const chars = JSON.stringify(parameters ?? {}).length;
    tokens = Math.round(chars / 4);
    lastRef.current = { time: now, tokens };
  }

  // Progress phase: more skeleton elements appear as tokens increase
  const phase = tokens < 50 ? 0 : tokens < 200 ? 1 : tokens < 400 ? 2 : 3;

  return (
    <div className="my-3 max-w-[320px]">
      <div
        className="relative overflow-hidden rounded-xl border border-gray-200/80 bg-white shadow-sm"
        style={{ padding: "16px 18px 14px" }}
      >
        {/* Top bar: three dots + filename skeleton */}
        <div className="flex items-center gap-2 mb-3">
          <div className="flex gap-1">
            <div className="w-[7px] h-[7px] rounded-full bg-gray-300" />
            <div className="w-[7px] h-[7px] rounded-full bg-gray-300" />
            <div className="w-[7px] h-[7px] rounded-full bg-gray-300" />
          </div>
          <div
            className="h-[6px] rounded-full bg-gray-200"
            style={{
              width: 64,
              opacity: phase >= 1 ? 1 : 0.4,
              transition: "opacity 0.5s",
            }}
          />
        </div>

        {/* Skeleton code lines */}
        <div className="space-y-[7px]">
          {/* Line 1 */}
          <div
            className="flex items-center gap-2"
            style={{ opacity: phase >= 0 ? 1 : 0, transition: "opacity 0.4s" }}
          >
            <div
              className="h-[7px] w-[36px] rounded-full bg-blue-200/70"
              style={{ animation: "a2ui-fade 2.4s ease-in-out infinite" }}
            />
            <div
              className="h-[7px] w-[80px] rounded-full bg-blue-100/80"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.2s infinite" }}
            />
          </div>

          {/* Line 2 */}
          <div
            className="flex items-center gap-2"
            style={{
              opacity: phase >= 0 ? 1 : 0,
              transition: "opacity 0.4s 0.1s",
            }}
          >
            <div className="w-3" />
            <div className="h-[6px] w-[6px] rounded-full bg-gray-300" />
            <div
              className="h-[7px] w-[100px] rounded-full bg-gray-800/20"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.3s infinite" }}
            />
          </div>

          {/* Line 3: row of blocks */}
          <div
            className="flex items-center gap-[6px]"
            style={{
              opacity: phase >= 1 ? 1 : 0,
              transition: "opacity 0.4s 0.15s",
            }}
          >
            <div className="w-3" />
            <div
              className="h-[7px] w-[48px] rounded-full bg-gray-800/15"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.1s infinite" }}
            />
            <div
              className="h-[7px] w-[40px] rounded-full bg-teal-200/60"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.5s infinite" }}
            />
            <div
              className="h-[7px] w-[56px] rounded-full bg-blue-200/60"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.3s infinite" }}
            />
          </div>

          {/* Line 4 */}
          <div
            className="flex items-center gap-2"
            style={{
              opacity: phase >= 1 ? 1 : 0,
              transition: "opacity 0.4s 0.2s",
            }}
          >
            <div className="w-3" />
            <div className="h-[6px] w-[6px] rounded-full bg-gray-300" />
            <div
              className="h-[7px] w-[60px] rounded-full bg-gray-800/15"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.4s infinite" }}
            />
          </div>

          {/* Line 5: wider row */}
          <div
            className="flex items-center gap-[6px]"
            style={{
              opacity: phase >= 2 ? 1 : 0,
              transition: "opacity 0.4s 0.25s",
            }}
          >
            <div
              className="h-[7px] w-[40px] rounded-full bg-teal-200/50"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.2s infinite" }}
            />
            <div className="h-[6px] w-[6px] rounded-full bg-gray-300" />
            <div
              className="h-[7px] w-[48px] rounded-full bg-gray-800/15"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.6s infinite" }}
            />
            <div
              className="h-[7px] w-[64px] rounded-full bg-blue-200/50"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.1s infinite" }}
            />
          </div>

          {/* Line 6 */}
          <div
            className="flex items-center gap-2"
            style={{
              opacity: phase >= 2 ? 1 : 0,
              transition: "opacity 0.4s 0.3s",
            }}
          >
            <div
              className="h-[7px] w-[36px] rounded-full bg-blue-200/60"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.5s infinite" }}
            />
            <div
              className="h-[7px] w-[36px] rounded-full bg-gray-800/12"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.7s infinite" }}
            />
          </div>

          {/* Line 7: bottom row */}
          <div
            className="flex items-center gap-[6px]"
            style={{
              opacity: phase >= 3 ? 1 : 0,
              transition: "opacity 0.4s 0.35s",
            }}
          >
            <div className="h-[6px] w-[6px] rounded-full bg-gray-300" />
            <div
              className="h-[7px] w-[44px] rounded-full bg-gray-800/18"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.3s infinite" }}
            />
            <div className="h-[6px] w-[6px] rounded-full bg-gray-300" />
            <div
              className="h-[7px] w-[56px] rounded-full bg-teal-200/50"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.8s infinite" }}
            />
            <div
              className="h-[7px] w-[48px] rounded-full bg-blue-200/50"
              style={{ animation: "a2ui-fade 2.4s ease-in-out 0.4s infinite" }}
            />
          </div>
        </div>

        {/* Shimmer overlay */}
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              "linear-gradient(105deg, transparent 0%, transparent 40%, rgba(255,255,255,0.6) 50%, transparent 60%, transparent 100%)",
            backgroundSize: "250% 100%",
            animation: "a2ui-sweep 3s ease-in-out infinite",
          }}
        />
      </div>

      {/* Label below */}
      <div className="flex items-center justify-center gap-2 mt-2">
        <span className="text-[12px] text-gray-400 tracking-wide">
          Building interface
        </span>
        <span className="text-[11px] tabular-nums text-gray-300">
          {tokens > 0 && `~${tokens.toLocaleString()} tokens`}
        </span>
      </div>

      <style>{`
        @keyframes a2ui-fade {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
        @keyframes a2ui-sweep {
          0% { background-position: 250% 0; }
          100% { background-position: -250% 0; }
        }
      `}</style>
    </div>
  );
});

// packages/angular/src/lib/components/a2ui/a2ui-progress.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

/**
 * Presentational loading placeholder shown while an A2UI tool call is still
 * streaming. Renders an animated skeleton card whose rows reveal as the
 * estimated token count climbs through `phase`.
 */
@Component({
  selector: "copilot-a2ui-progress",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="copilot-a2ui-progress" data-testid="a2ui-progress">
      <div class="copilot-a2ui-progress-card">
        <div class="copilot-a2ui-topbar">
          <div class="copilot-a2ui-dot-group">
            <span class="copilot-a2ui-dot"></span>
            <span class="copilot-a2ui-dot"></span>
            <span class="copilot-a2ui-dot"></span>
          </div>
          <span [class]="topbarBarClass()"></span>
        </div>

        <div class="copilot-a2ui-lines">
          <div [class]="rowClass(0, 'cpk:[transition-delay:0s]')">
            <span
              class="copilot-a2ui-bar cpk:w-[36px] cpk:h-[7px] cpk:bg-[rgba(147,197,253,0.7)] cpk:[animation-delay:0s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-20 cpk:h-[7px] cpk:bg-[rgba(219,234,254,0.8)] cpk:[animation-delay:0.2s]"
            ></span>
          </div>

          <div [class]="rowClass(0, 'cpk:[transition-delay:0.1s]')">
            <span class="copilot-a2ui-spacer"></span>
            <span class="copilot-a2ui-dot"></span>
            <span
              class="copilot-a2ui-bar cpk:w-[100px] cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.2)] cpk:[animation-delay:0.3s]"
            ></span>
          </div>

          <div [class]="rowClass(1, 'cpk:[transition-delay:0.15s]')">
            <span class="copilot-a2ui-spacer"></span>
            <span
              class="copilot-a2ui-bar cpk:w-12 cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.15)] cpk:[animation-delay:0.1s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-10 cpk:h-[7px] cpk:bg-[rgba(153,246,228,0.6)] cpk:[animation-delay:0.5s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-14 cpk:h-[7px] cpk:bg-[rgba(147,197,253,0.6)] cpk:[animation-delay:0.3s]"
            ></span>
          </div>

          <div [class]="rowClass(1, 'cpk:[transition-delay:0.2s]')">
            <span class="copilot-a2ui-spacer"></span>
            <span class="copilot-a2ui-dot"></span>
            <span
              class="copilot-a2ui-bar cpk:w-[60px] cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.15)] cpk:[animation-delay:0.4s]"
            ></span>
          </div>

          <div [class]="rowClass(2, 'cpk:[transition-delay:0.25s]')">
            <span
              class="copilot-a2ui-bar cpk:w-10 cpk:h-[7px] cpk:bg-[rgba(153,246,228,0.5)] cpk:[animation-delay:0.2s]"
            ></span>
            <span class="copilot-a2ui-dot"></span>
            <span
              class="copilot-a2ui-bar cpk:w-12 cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.15)] cpk:[animation-delay:0.6s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-16 cpk:h-[7px] cpk:bg-[rgba(147,197,253,0.5)] cpk:[animation-delay:0.1s]"
            ></span>
          </div>

          <div [class]="rowClass(2, 'cpk:[transition-delay:0.3s]')">
            <span
              class="copilot-a2ui-bar cpk:w-[36px] cpk:h-[7px] cpk:bg-[rgba(147,197,253,0.6)] cpk:[animation-delay:0.5s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-[36px] cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.12)] cpk:[animation-delay:0.7s]"
            ></span>
          </div>

          <div [class]="rowClass(3, 'cpk:[transition-delay:0.35s]')">
            <span class="copilot-a2ui-dot"></span>
            <span
              class="copilot-a2ui-bar cpk:w-11 cpk:h-[7px] cpk:bg-[rgba(24,24,27,0.18)] cpk:[animation-delay:0.3s]"
            ></span>
            <span class="copilot-a2ui-dot"></span>
            <span
              class="copilot-a2ui-bar cpk:w-14 cpk:h-[7px] cpk:bg-[rgba(153,246,228,0.5)] cpk:[animation-delay:0.8s]"
            ></span>
            <span
              class="copilot-a2ui-bar cpk:w-12 cpk:h-[7px] cpk:bg-[rgba(147,197,253,0.5)] cpk:[animation-delay:0.4s]"
            ></span>
          </div>
        </div>

        <div class="copilot-a2ui-shimmer"></div>
      </div>

      <div class="copilot-a2ui-label">
        <span>Building interface</span>
        @if (tokens() > 0) {
          <span class="copilot-a2ui-token-count">
            ~{{ tokens().toLocaleString() }} tokens
          </span>
        }
      </div>
    </div>
  `,
  styles: [
    `
      .copilot-a2ui-progress {
        margin: 12px 0;
        max-width: 320px;
      }

      .copilot-a2ui-progress-card {
        position: relative;
        overflow: hidden;
        border-radius: 12px;
        border: 1px solid rgba(228, 228, 231, 0.8);
        background-color: #fff;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
        padding: 16px 18px 14px;
      }

      .copilot-a2ui-topbar,
      .copilot-a2ui-row,
      .copilot-a2ui-label,
      .copilot-a2ui-dot-group {
        display: flex;
        align-items: center;
      }

      .copilot-a2ui-topbar {
        gap: 8px;
        margin-bottom: 12px;
      }

      .copilot-a2ui-dot-group,
      .copilot-a2ui-row {
        gap: 6px;
      }

      .copilot-a2ui-lines {
        display: grid;
        gap: 7px;
      }

      .copilot-a2ui-row {
        transition-property: opacity;
        transition-duration: 0.4s;
      }

      .copilot-a2ui-dot {
        width: 7px;
        height: 7px;
        border-radius: 9999px;
        background-color: #d4d4d8;
        flex-shrink: 0;
      }

      .copilot-a2ui-spacer {
        width: 12px;
        flex: 0 0 12px;
      }

      .copilot-a2ui-bar {
        display: inline-flex;
        border-radius: 9999px;
        animation: copilot-a2ui-fade 2.4s ease-in-out infinite;
      }

      .copilot-a2ui-shimmer {
        pointer-events: none;
        position: absolute;
        inset: 0;
        background: linear-gradient(
          105deg,
          transparent 0%,
          transparent 40%,
          rgba(255, 255, 255, 0.6) 50%,
          transparent 60%,
          transparent 100%
        );
        background-size: 250% 100%;
        animation: copilot-a2ui-sweep 3s ease-in-out infinite;
      }

      .copilot-a2ui-label {
        justify-content: center;
        gap: 8px;
        margin-top: 8px;
        font-size: 12px;
        color: #a1a1aa;
      }

      .copilot-a2ui-token-count {
        font-size: 11px;
        color: #d4d4d8;
        font-variant-numeric: tabular-nums;
      }

      @keyframes copilot-a2ui-fade {
        0%,
        100% {
          opacity: 1;
        }
        50% {
          opacity: 0.5;
        }
      }

      @keyframes copilot-a2ui-sweep {
        0% {
          background-position: 250% 0;
        }
        100% {
          background-position: -250% 0;
        }
      }
    `,
  ],
})
export class CopilotA2UIProgress {
  readonly phase = input.required<number>();
  readonly tokens = input(0);

  protected topbarBarClass(): string {
    return [
      "copilot-a2ui-bar",
      "cpk:w-16",
      "cpk:h-1.5",
      "cpk:bg-[#e4e4e7]",
      this.phase() >= 1 ? "cpk:opacity-100" : "cpk:opacity-40",
    ].join(" ");
  }

  protected rowClass(phase: number, delayClass: string): string {
    return [
      "copilot-a2ui-row",
      delayClass,
      this.phase() >= phase ? "cpk:opacity-100" : "cpk:opacity-0",
    ].join(" ");
  }
}
