// src/v2.x/apps/react/storybook/stories/CopilotStoryLayout.tsx
import React from "react";

import { CopilotChatConfigurationProvider, CopilotKitProvider } from "@copilotkitnext/react";

interface CopilotStoryLayoutProps {
  children: React.ReactNode;
  threadId?: string;
  isModalDefaultOpen?: boolean;
  content?: React.ReactNode;
}

const defaultContent = (
  <>
    <section className="space-y-4">
      <h1 className="text-3xl font-semibold tracking-tight">Project Dashboard</h1>
      <p className="text-muted-foreground">
        Toggle the assistant to draft updates, summarize discussions, and keep track of action items while you stay in
        context.
      </p>
    </section>

    <div className="grid gap-4 sm:grid-cols-2">
      {Array.from({ length: 4 }).map((_, index) => (
        <article
          key={index}
          className="rounded-xl border border-border bg-card p-4 shadow-sm transition hover:shadow-md"
        >
          <h2 className="text-lg font-medium">Task {index + 1}</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            Placeholder content to illustrate how the assistant integrates alongside your existing workflow.
          </p>
        </article>
      ))}
    </div>
  </>
);

class MockAgent {}

export const CopilotStoryLayout: React.FC<CopilotStoryLayoutProps> = ({
  children,
  threadId = "story-copilot-layout",
  isModalDefaultOpen = true,
  content,
}) => (
  <CopilotKitProvider runtimeUrl="https://copilotkit.ai">
    <CopilotChatConfigurationProvider threadId={"123"} isModalDefaultOpen={isModalDefaultOpen}>
      <div className="min-h-screen bg-background text-foreground">
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 px-6 py-10">{content ?? defaultContent}</div>
        {children}
      </div>
    </CopilotChatConfigurationProvider>
  </CopilotKitProvider>
);

export default CopilotStoryLayout;

// examples/v2/vue/storybook/stories/CopilotStoryLayout.vue
<script setup lang="ts">
import {
  CopilotChatConfigurationProvider,
  CopilotKitProvider,
} from "@copilotkitnext/vue";

withDefaults(
  defineProps<{
    threadId?: string;
    isModalDefaultOpen?: boolean;
  }>(),
  {
    threadId: "story-copilot-layout",
    isModalDefaultOpen: true,
  },
);
</script>

<template>
  <CopilotKitProvider runtime-url="https://copilotkit.ai">
    <CopilotChatConfigurationProvider
      :thread-id="threadId"
      :is-modal-default-open="isModalDefaultOpen"
    >
      <div
        style="
          min-height: 100vh;
          background: var(--color-background, #fff);
          color: var(--color-foreground, #020617);
        "
      >
        <div
          style="
            margin: 0 auto;
            max-width: 1024px;
            display: grid;
            grid-template-columns: 1fr;
            gap: 24px;
            padding: 40px 24px;
          "
        >
          <section style="display: flex; flex-direction: column; gap: 16px">
            <h1
              style="
                margin: 0;
                font-size: 30px;
                font-weight: 600;
                letter-spacing: -0.02em;
              "
            >
              Project Dashboard
            </h1>
            <p style="margin: 0; color: #64748b">
              Toggle the assistant to draft updates, summarize discussions, and
              keep track of action items while you stay in context.
            </p>
          </section>

          <div
            style="
              display: grid;
              gap: 16px;
              grid-template-columns: repeat(2, minmax(0, 1fr));
            "
          >
            <article
              v-for="index in 4"
              :key="index"
              style="
                border: 1px solid var(--color-border, #e2e8f0);
                border-radius: 12px;
                background: var(--color-card, #fff);
                padding: 16px;
                box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
              "
            >
              <h2 style="margin: 0; font-size: 18px; font-weight: 500">
                Task {{ index }}
              </h2>
              <p style="margin: 8px 0 0; font-size: 14px; color: #64748b">
                Placeholder content to illustrate how the assistant integrates
                alongside your existing workflow.
              </p>
            </article>
          </div>
        </div>
        <slot />
      </div>
    </CopilotChatConfigurationProvider>
  </CopilotKitProvider>
</template>
