// examples/experiments/a2ui-private/original_a2ui_source/renderers/angular/src/lib/catalog/row.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input } from '@angular/core';
import * as v0_8 from '@a2ui/web-lib/0.8';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';

@Component({
  selector: 'a2ui-row',
  imports: [Renderer],
  host: {
    '[attr.alignment]': 'alignment()',
    '[attr.distribution]': 'distribution()',
  },
  styles: `
    :host {
      display: flex;
      flex: var(--weight);
    }

    section {
      display: flex;
      flex-direction: row;
      width: 100%;
      min-height: 100%;
      box-sizing: border-box;
    }

    .align-start {
      align-items: start;
    }

    .align-center {
      align-items: center;
    }

    .align-end {
      align-items: end;
    }

    .align-stretch {
      align-items: stretch;
    }

    .distribute-start {
      justify-content: start;
    }

    .distribute-center {
      justify-content: center;
    }

    .distribute-end {
      justify-content: end;
    }

    .distribute-spaceBetween {
      justify-content: space-between;
    }

    .distribute-spaceAround {
      justify-content: space-around;
    }

    .distribute-spaceEvenly {
      justify-content: space-evenly;
    }
  `,
  template: `
    <section [class]="classes()" [style]="theme.additionalStyles?.Row">
      @for (child of component().properties.children; track child) {
      <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="child" />
      }
    </section>
  `,
})
export class Row extends DynamicComponent<v0_8.Types.RowNode> {
  readonly alignment = input<v0_8.Types.ResolvedRow['alignment']>('stretch');
  readonly distribution = input<v0_8.Types.ResolvedRow['distribution']>('start');

  protected readonly classes = computed(() => ({
    ...this.theme.components.Row,
    [`align-${this.alignment()}`]: true,
    [`distribute-${this.distribution()}`]: true,
  }));
}

// examples/showcases/generative-ui-playground/lit/src/0.8/ui/row.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { html, css, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { Root } from "./root.js";
import { classMap } from "lit/directives/class-map.js";
import { ResolvedRow } from "../types/types";
import { styleMap } from "lit/directives/style-map.js";
import { structuralStyles } from "./styles.js";

@customElement("a2ui-row")
export class Row extends Root {
  @property({ reflect: true, type: String })
  accessor alignment: ResolvedRow["alignment"] = "stretch";

  @property({ reflect: true, type: String })
  accessor distribution: ResolvedRow["distribution"] = "start";

  static styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: flex;
        flex: var(--weight);
      }

      section {
        display: flex;
        flex-direction: row;
        width: 100%;
        min-height: 100%;
      }

      :host([alignment="start"]) section {
        align-items: start;
      }

      :host([alignment="center"]) section {
        align-items: center;
      }

      :host([alignment="end"]) section {
        align-items: end;
      }

      :host([alignment="stretch"]) section {
        align-items: stretch;
      }

      :host([distribution="start"]) section {
        justify-content: start;
      }

      :host([distribution="center"]) section {
        justify-content: center;
      }

      :host([distribution="end"]) section {
        justify-content: end;
      }

      :host([distribution="spaceBetween"]) section {
        justify-content: space-between;
      }

      :host([distribution="spaceAround"]) section {
        justify-content: space-around;
      }

      :host([distribution="spaceEvenly"]) section {
        justify-content: space-evenly;
      }
    `,
  ];

  render() {
    return html`<section
      class=${classMap(this.theme.components.Row)}
      style=${this.theme.additionalStyles?.Row
        ? styleMap(this.theme.additionalStyles?.Row)
        : nothing}
    >
      <slot></slot>
    </section>`;
  }
}
