// examples/experiments/a2ui-private/original_a2ui_source/renderers/angular/src/lib/catalog/tabs.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input, signal } from '@angular/core';
import * as v0_8 from '@a2ui/web-lib/0.8';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';

@Component({
  selector: 'a2ui-tabs',
  imports: [Renderer],
  template: `
    @let tabs = this.tabs();
    @let selectedIndex = this.selectedIndex();

    <section [class]="theme.components.Tabs.container" [style]="theme.additionalStyles?.Tabs">
      <div [class]="theme.components.Tabs.element">
        @for (tab of tabs; track tab) {
          <button
            (click)="this.selectedIndex.set($index)"
            [disabled]="selectedIndex === $index"
            [class]="buttonClasses()[selectedIndex]">
            {{ resolvePrimitive(tab.title) }}
          </button>
        }
      </div>

      <ng-container
        a2ui-renderer
        [surfaceId]="surfaceId()!"
        [component]="tabs[selectedIndex].child"
      />
    </section>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
    }
  `,
})
export class Tabs extends DynamicComponent {
  protected selectedIndex = signal(0);
  readonly tabs = input.required<v0_8.Types.ResolvedTabItem[]>();

  protected readonly buttonClasses = computed(() => {
    const selectedIndex = this.selectedIndex();

    return this.tabs().map((_, index) => {
      return index === selectedIndex
        ? v0_8.Styles.merge(
            this.theme.components.Tabs.controls.all,
            this.theme.components.Tabs.controls.selected
          )
        : this.theme.components.Tabs.controls.all;
    });
  });
}

// examples/showcases/generative-ui-playground/lit/src/0.8/ui/tabs.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { html, css, PropertyValues, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { Root } from "./root.js";
import { repeat } from "lit/directives/repeat.js";
import { StringValue } from "../types/primitives.js";
import { A2uiMessageProcessor } from "../data/model-processor.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import { structuralStyles } from "./styles.js";
import { Styles } from "../index.js";

@customElement("a2ui-tabs")
export class Tabs extends Root {
  @property()
  accessor titles: StringValue[] | null = null;

  @property()
  accessor selected = 0;

  static styles = [
    structuralStyles,
    css`
      :host {
        display: block;
        flex: var(--weight);
      }
    `,
  ];

  protected willUpdate(changedProperties: PropertyValues<this>): void {
    super.willUpdate(changedProperties);

    if (changedProperties.has("selected")) {
      for (const child of this.children) {
        child.removeAttribute("slot");
      }
      const selectedChild = this.children[this.selected];
      if (!selectedChild) {
        return;
      }

      selectedChild.slot = "current";
    }
  }

  #renderTabs() {
    if (!this.titles) {
      return nothing;
    }

    return html`<div
      id="buttons"
      class=${classMap(this.theme.components.Tabs.element)}
    >
      ${repeat(this.titles, (title, idx) => {
        let titleString = "";
        if ("literalString" in title && title.literalString) {
          titleString = title.literalString;
        } else if ("literal" in title && title.literal !== undefined) {
          titleString = title.literal;
        } else if (title && "path" in title && title.path) {
          if (!this.processor || !this.component) {
            return html`(no model)`;
          }

          const textValue = this.processor.getData(
            this.component,
            title.path,
            this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID
          );

          if (typeof textValue !== "string") {
            return html`(invalid)`;
          }

          titleString = textValue;
        }

        let classes;
        if (this.selected === idx) {
          classes = Styles.merge(
            this.theme.components.Tabs.controls.all,
            this.theme.components.Tabs.controls.selected
          );
        } else {
          classes = { ...this.theme.components.Tabs.controls.all };
        }

        return html`<button
          ?disabled=${this.selected === idx}
          class=${classMap(classes)}
          @click=${() => {
            this.selected = idx;
          }}
        >
          ${titleString}
        </button>`;
      })}
    </div>`;
  }

  #renderSlot() {
    return html`<slot name="current"></slot>`;
  }

  render() {
    return html`<section
      class=${classMap(this.theme.components.Tabs.container)}
      style=${this.theme.additionalStyles?.Tabs
        ? styleMap(this.theme.additionalStyles?.Tabs)
        : nothing}
    >
      ${[this.#renderTabs(), this.#renderSlot()]}
    </section>`;
  }
}
