// packages/vue/src/v2/components/CopilotKitInspector.vue
<script setup lang="ts">
import { version as sdkVersion } from "../../../package.json";
defineOptions({
  inheritAttrs: false,
});

import { onMounted, onUnmounted, shallowRef, useAttrs, watch } from "vue";
import type { ObjectDirective } from "vue";
import type { WebInspectorElement } from "@copilotkit/web-inspector";
import type { CopilotKitCoreVue } from "../lib/vue-core";
import type { VueInspectorOpenRequest } from "../providers/keys";

const props = defineProps<{
  core?: CopilotKitCoreVue | null;
  openRequest?: VueInspectorOpenRequest | null;
}>();

const attrs = useAttrs();
const inspectorTag = shallowRef<string | null>(null);
const inspector = shallowRef<WebInspectorElement | null>(null);

let isMounted = true;
let configureInspector:
  | ((
      element: WebInspectorElement,
      core: CopilotKitCoreVue | null,
    ) => WebInspectorElement)
  | null = null;

const vConfigureInspector: ObjectDirective<WebInspectorElement, undefined> = {
  created(element) {
    configureInspector?.(element, props.core ?? null);
    inspector.value = element;
    if (props.openRequest) {
      element.openInspector?.("message_toolbar", props.openRequest);
    }
  },
};

onMounted(() => {
  void import("@copilotkit/web-inspector")
    .then((mod) => {
      if (!isMounted) return;

      mod.defineWebInspector?.();
      configureInspector = (element, core) =>
        mod.configureWebInspectorElement(element, core, {
          development: process.env.NODE_ENV === "development",
          framework: "vue",
          sdkVersion,
        });
      inspectorTag.value = mod.WEB_INSPECTOR_TAG;
    })
    .catch((error: unknown) => {
      console.error("Failed to load CopilotKit inspector:", error);
    });
});

onUnmounted(() => {
  isMounted = false;
  inspector.value = null;
});

watch(
  () => props.core,
  (core) => {
    if (inspector.value) inspector.value.core = core ?? null;
  },
);

watch(
  () => props.openRequest,
  (request) => {
    if (request) inspector.value?.openInspector?.("message_toolbar", request);
  },
);
</script>

<template>
  <component
    :is="inspectorTag"
    v-if="inspectorTag"
    v-bind="attrs"
    v-configure-inspector
  />
</template>

// packages/react-core/src/v2/components/CopilotKitInspector.tsx
import { version as sdkVersion } from "../../../package.json";
import * as React from "react";
import type { CopilotKitCore } from "@copilotkit/core";
import type { WebInspectorElement } from "@copilotkit/web-inspector";
import type { CopilotKitInspectorOpenRequest } from "./CopilotKitInspectorContext";

export interface CopilotKitInspectorProps {
  core?: CopilotKitCore | null;
  intelligenceOnly?: boolean;
  intelligenceAppUrl?: string;
  onVisibilityChange?: (visible: boolean) => void;
  openRequest?: CopilotKitInspectorOpenRequest | null;
}

export const CopilotKitInspector: React.FC<CopilotKitInspectorProps> = ({
  core,
  intelligenceOnly = false,
  intelligenceAppUrl = "",
  openRequest,
  onVisibilityChange,
}) => {
  const mountRef = React.useRef<HTMLSpanElement | null>(null);
  const inspectorRef = React.useRef<WebInspectorElement | null>(null);
  const latestCoreRef = React.useRef(core ?? null);
  const latestOpenRequestRef = React.useRef(openRequest);

  const visibilityCallbackRef = React.useRef(onVisibilityChange);
  visibilityCallbackRef.current = onVisibilityChange;

  latestCoreRef.current = core ?? null;
  latestOpenRequestRef.current = openRequest;

  React.useEffect(() => {
    let mounted = true;
    let inspector: WebInspectorElement | null = null;

    const handleVisibilityChange = (event: Event) => {
      const visible = (event as CustomEvent<{ visible: boolean }>).detail
        ?.visible;
      visibilityCallbackRef.current?.(visible === true);
    };

    // Load the web component only on the client to keep SSR output stable.
    import("@copilotkit/web-inspector")
      .then((mod) => {
        if (!mounted || !mountRef.current) return;

        mod.defineWebInspector?.();
        inspector = mountRef.current.ownerDocument.createElement(
          mod.WEB_INSPECTOR_TAG,
        ) as WebInspectorElement;
        inspector.intelligenceOnly = intelligenceOnly;
        inspector.intelligenceAppUrl = intelligenceAppUrl;
        mod.configureWebInspectorElement(inspector, latestCoreRef.current, {
          development: process.env.NODE_ENV === "development",
          framework: "react",
          sdkVersion,
        });

        inspector.addEventListener(
          "cpk-inspector-visibility-change",
          handleVisibilityChange,
        );
        mountRef.current.appendChild(inspector);
        inspectorRef.current = inspector;

        const request = latestOpenRequestRef.current;
        if (request && !intelligenceOnly) {
          inspector.openInspector("message_toolbar", request);
        }
      })
      .catch((error: unknown) => {
        console.error("Failed to load CopilotKit inspector:", error);
      });

    return () => {
      mounted = false;
      inspector?.removeEventListener(
        "cpk-inspector-visibility-change",
        handleVisibilityChange,
      );
      inspector?.remove();
      visibilityCallbackRef.current?.(false);
      if (inspectorRef.current === inspector) {
        inspectorRef.current = null;
      }
    };
  }, [intelligenceOnly, intelligenceAppUrl]);

  React.useEffect(() => {
    if (inspectorRef.current) {
      inspectorRef.current.core = core ?? null;
    }
  }, [core]);

  React.useEffect(() => {
    if (openRequest && !intelligenceOnly) {
      inspectorRef.current?.openInspector("message_toolbar", openRequest);
    }
  }, [openRequest, intelligenceOnly]);

  return <span ref={mountRef} style={{ display: "contents" }} />;
};

CopilotKitInspector.displayName = "CopilotKitInspector";
