// packages/a2ui-renderer/src/web-components/catalog/basic/audio-player.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { AudioPlayerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { getBaseLeafStyle } from "./utils";

export const AudioPlayer = createLitComponent(AudioPlayerApi, ({ props }) => {
  const style = { ...getBaseLeafStyle(), width: "100%" };
  return html`
    <div
      style=${styleMap({
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        width: "100%",
      })}
    >
      ${
        props.description
          ? html`<span style="font-size: 12px; color: #666;"
            >${props.description}</span
          >`
          : nothing
      }
      <audio src=${props.url ?? ""} controls style=${styleMap(style)}></audio>
    </div>
  `;
});

// packages/angular/src/a2ui/lib/basic/audio-player.ts
import { Component } from "@angular/core";
import { AudioPlayerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-audio-player",
  template: `
    @if (props().description) {
      <span class="description">{{ props().description }}</span>
    }
    <audio class="audio" controls [src]="props().url ?? ''"></audio>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      gap: calc(var(--a2ui-spacing-m, 8px) / 2);
      width: 100%;
    }
    .description {
      font-size: var(--a2ui-font-size-xs, 12px);
      color: var(--a2ui-color-muted, #666);
    }
    .audio {
      width: 100%;
      box-sizing: border-box;
    }
  `,
})
export class CopilotA2UIAudioPlayer extends CopilotA2UIBasicComponent<
  typeof AudioPlayerApi
> {}
