// packages/a2ui-renderer/src/web-components/catalog/basic/image.ts
import { html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { ImageApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { getBaseLeafStyle } from "./utils";

export const Image = createLitComponent(ImageApi, ({ props }) => {
  const mapFit = (fit?: string): string => {
    if (fit === "scaleDown") return "scale-down";
    return fit || "fill";
  };
  const style: Record<string, string> = {
    ...getBaseLeafStyle(),
    objectFit: mapFit(props.fit),
    width: "100%",
    height: "auto",
    display: "block",
  } as Record<string, string>;

  if (props.variant === "icon") {
    style.width = "24px";
    style.height = "24px";
  } else if (props.variant === "avatar") {
    style.width = "40px";
    style.height = "40px";
    style.borderRadius = "50%";
  } else if (props.variant === "smallFeature") {
    style.maxWidth = "100px";
  } else if (props.variant === "largeFeature") {
    style.maxHeight = "400px";
  } else if (props.variant === "header") {
    style.height = "200px";
    style.objectFit = "cover";
  }

  return html`<img
    src=${props.url ?? ""}
    alt=${props.description ?? ""}
    style=${styleMap(style)}
  />`;
});

// packages/angular/src/a2ui/lib/basic/image.ts
import { Component, computed } from "@angular/core";
import { ImageApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-image",
  template: `
    <img
      class="image"
      [class]="'variant-' + (props().variant ?? 'default')"
      [src]="props().url ?? ''"
      [alt]="props().description ?? ''"
      [style.object-fit]="fit()"
    />
  `,
  styles: `
    :host {
      display: block;
    }
    .image {
      display: block;
      width: 100%;
      height: auto;
      box-sizing: border-box;
    }
    .variant-icon {
      width: 24px;
      height: 24px;
    }
    .variant-avatar {
      width: 40px;
      height: 40px;
      border-radius: 50%;
    }
    .variant-smallFeature {
      max-width: 100px;
    }
    .variant-largeFeature {
      max-height: 400px;
    }
    .variant-header {
      height: 200px;
    }
  `,
})
export class CopilotA2UIImage extends CopilotA2UIBasicComponent<
  typeof ImageApi
> {
  protected readonly fit = computed(() => {
    const { variant, fit } = this.props();
    if (variant === "header") return "cover";
    return fit === "scaleDown" ? "scale-down" : fit || "fill";
  });
}
