// packages/a2ui-renderer/src/web-components/catalog/basic/modal.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { ModalApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";

export const Modal = createLitComponent(
  ModalApi,
  ({ props, buildChild, state, requestUpdate }) => {
    const local = state as { isOpen: boolean };
    return html`
      <div
        @click=${() => {
          local.isOpen = true;
          requestUpdate();
        }}
        style="display: inline-block;"
      >
        ${props.trigger ? buildChild(props.trigger) : nothing}
      </div>
      ${
        local.isOpen
          ? html`
            <div
              style=${styleMap({
                position: "fixed",
                top: "0",
                left: "0",
                right: "0",
                bottom: "0",
                backgroundColor: "rgba(0,0,0,0.5)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                zIndex: "1000",
              })}
              @click=${() => {
                local.isOpen = false;
                requestUpdate();
              }}
            >
              <div
                style=${styleMap({
                  backgroundColor: "#fff",
                  padding: "24px",
                  borderRadius: "8px",
                  maxWidth: "90%",
                  maxHeight: "90%",
                  overflow: "auto",
                  display: "flex",
                  flexDirection: "column",
                })}
                @click=${(e: Event) => e.stopPropagation()}
              >
                <div style="display: flex; justify-content: flex-end;">
                  <button
                    type="button"
                    @click=${() => {
                      local.isOpen = false;
                      requestUpdate();
                    }}
                    style=${styleMap({
                      border: "none",
                      background: "none",
                      fontSize: "20px",
                      cursor: "pointer",
                      padding: "4px",
                    })}
                  >
                    &times;
                  </button>
                </div>
                <div style="flex: 1;">
                  ${props.content ? buildChild(props.content) : nothing}
                </div>
              </div>
            </div>
          `
          : nothing
      }
    `;
  },
  () => ({ isOpen: false }),
);

// packages/angular/src/a2ui/lib/basic/modal.ts
import { Component, signal } from "@angular/core";
import { ModalApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIChild } from "../child";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-modal",
  imports: [CopilotA2UIChild],
  template: `
    <div (click)="open.set(true)">
      <copilot-a2ui-child [child]="props().trigger" />
    </div>
    @if (open()) {
      <div class="backdrop" (click)="open.set(false)">
        <div
          class="dialog"
          role="dialog"
          aria-modal="true"
          (click)="$event.stopPropagation()"
        >
          <div class="dialog-header">
            <button
              type="button"
              class="close"
              aria-label="Close"
              (click)="open.set(false)"
            >
              &times;
            </button>
          </div>
          <div class="dialog-content">
            <copilot-a2ui-child [child]="props().content" />
          </div>
        </div>
      </div>
    }
  `,
  styles: `
    :host {
      display: inline-block;
    }
    .backdrop {
      position: fixed;
      inset: 0;
      z-index: var(--a2ui-modal-z-index, 1000);
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: var(--a2ui-modal-backdrop, rgba(0, 0, 0, 0.5));
    }
    .dialog {
      display: flex;
      flex-direction: column;
      max-width: 90%;
      max-height: 90%;
      overflow: auto;
      padding: var(--a2ui-modal-padding, 24px);
      border-radius: var(--a2ui-border-radius, 8px);
      background-color: var(--a2ui-color-surface, #fff);
    }
    .dialog-header {
      display: flex;
      justify-content: flex-end;
    }
    .close {
      padding: 4px;
      border: none;
      background: none;
      font-size: 20px;
      cursor: pointer;
    }
    .dialog-content {
      flex: 1;
    }
  `,
})
export class CopilotA2UIModal extends CopilotA2UIBasicComponent<
  typeof ModalApi
> {
  protected readonly open = signal(false);
}
