// packages/a2ui-renderer/src/web-components/catalog/basic/text.ts
import { html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { TextApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { getBaseLeafStyle } from "./utils";

export const Text = createLitComponent(TextApi, ({ props }) => {
  const text = props.text ?? "";
  const style = { ...getBaseLeafStyle(), display: "inline-block" };

  switch (props.variant) {
    case "h1":
      return html`<h1 style=${styleMap(style)}>${text}</h1>`;
    case "h2":
      return html`<h2 style=${styleMap(style)}>${text}</h2>`;
    case "h3":
      return html`<h3 style=${styleMap(style)}>${text}</h3>`;
    case "h4":
      return html`<h4 style=${styleMap(style)}>${text}</h4>`;
    case "h5":
      return html`<h5 style=${styleMap(style)}>${text}</h5>`;
    case "caption":
      return html`
        <small
          style=${styleMap({ ...style, color: "#666", textAlign: "left" })}
          >${text}</small
        >
      `;
    case "body":
    default:
      return html`<span style=${styleMap(style)}>${text}</span>`;
  }
});

// packages/angular/src/a2ui/lib/basic/text.ts
import { Component } from "@angular/core";
import { TextApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-text",
  template: `
    @switch (props().variant) {
      @case ("h1") {
        <h1 class="text">{{ props().text }}</h1>
      }
      @case ("h2") {
        <h2 class="text">{{ props().text }}</h2>
      }
      @case ("h3") {
        <h3 class="text">{{ props().text }}</h3>
      }
      @case ("h4") {
        <h4 class="text">{{ props().text }}</h4>
      }
      @case ("h5") {
        <h5 class="text">{{ props().text }}</h5>
      }
      @case ("caption") {
        <small class="text caption">{{ props().text }}</small>
      }
      @default {
        <span class="text">{{ props().text }}</span>
      }
    }
  `,
  styles: `
    :host {
      display: inline-block;
    }
    .text {
      display: block;
      box-sizing: border-box;
    }
    .caption {
      color: var(--a2ui-color-muted, #666);
      text-align: left;
    }
  `,
})
export class CopilotA2UIText extends CopilotA2UIBasicComponent<
  typeof TextApi
> {}
