// packages/a2ui-renderer/src/web-components/catalog/basic/text-field.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { TextFieldApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { uniqueId } from "./ids";
import { LEAF_MARGIN, STANDARD_BORDER, STANDARD_RADIUS } from "./utils";

export const TextField = createLitComponent(TextFieldApi, ({ props }) => {
  const inputId = uniqueId("textfield");
  const isLong = props.variant === "longText";
  const type =
    props.variant === "number"
      ? "number"
      : props.variant === "obscured"
        ? "password"
        : "text";
  const hasError = props.validationErrors && props.validationErrors.length > 0;
  const style = {
    padding: "8px",
    width: "100%",
    border: hasError ? "1px solid red" : STANDARD_BORDER,
    borderRadius: STANDARD_RADIUS,
    boxSizing: "border-box",
  };
  const onChange = (e: Event) => {
    props.setValue((e.target as HTMLInputElement | HTMLTextAreaElement).value);
  };

  return html`
    <div
      style=${styleMap({
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        width: "100%",
        margin: LEAF_MARGIN,
      })}
    >
      ${
        props.label
          ? html`<label
            for=${inputId}
            style="font-size: 14px; font-weight: bold;"
            >${props.label}</label
          >`
          : nothing
      }
      ${
        isLong
          ? html`<textarea
            id=${inputId}
            style=${styleMap(style)}
            .value=${props.value || ""}
            @input=${onChange}
          ></textarea>`
          : html`<input
            id=${inputId}
            type=${type}
            style=${styleMap(style)}
            .value=${props.value || ""}
            @input=${onChange}
          />`
      }
      ${
        hasError
          ? html`<span style="font-size: 12px; color: red;"
            >${props.validationErrors![0]}</span
          >`
          : nothing
      }
    </div>
  `;
});

// packages/angular/src/a2ui/lib/basic/text-field.ts
import { Component, computed, input } from "@angular/core";
import type { TextFieldApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { uniqueId, type BasicProps } from "./shared";

@Component({
  selector: "copilot-a2ui-text-field",
  template: `
    <div class="field">
      @if (props().label) {
        <label class="label" [for]="inputId">{{ props().label }}</label>
      }
      @if (props().variant === "longText") {
        <textarea
          class="input"
          [class.invalid]="error()"
          [id]="inputId"
          [value]="props().value ?? ''"
          (input)="update($event)"
        ></textarea>
      } @else {
        <input
          class="input"
          [class.invalid]="error()"
          [id]="inputId"
          [type]="type()"
          [value]="props().value ?? ''"
          (input)="update($event)"
        />
      }
      @if (error(); as error) {
        <span class="error">{{ error }}</span>
      }
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .field {
      display: flex;
      flex-direction: column;
      gap: calc(var(--a2ui-spacing-m, 8px) / 2);
      width: 100%;
      margin: var(--a2ui-spacing-m, 8px);
    }
    .label {
      font-size: var(--a2ui-font-size-s, 14px);
      font-weight: bold;
    }
    .input {
      width: 100%;
      padding: var(--a2ui-input-padding, 8px);
      border: 1px solid var(--a2ui-color-border, #ccc);
      border-radius: var(--a2ui-border-radius, 8px);
      box-sizing: border-box;
      background-color: var(--a2ui-color-input, Field);
      color: var(--a2ui-color-on-input, FieldText);
    }
    .invalid {
      border: 1px solid var(--a2ui-color-error, red);
    }
    .error {
      font-size: var(--a2ui-font-size-xs, 12px);
      color: var(--a2ui-color-error, red);
    }
  `,
})
export class CopilotA2UITextField {
  readonly props = input.required<BasicProps<typeof TextFieldApi>>();
  protected readonly inputId = uniqueId("textfield");
  protected readonly error = computed(() => this.props().validationErrors?.[0]);
  protected readonly type = computed(() => {
    switch (this.props().variant) {
      case "number":
        return "number";
      case "obscured":
        return "password";
      default:
        return "text";
    }
  });

  protected update(event: Event): void {
    this.props().setValue(
      (event.target as HTMLInputElement | HTMLTextAreaElement).value,
    );
  }
}
