// packages/a2ui-renderer/src/web-components/catalog/basic/video.ts
import { html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { VideoApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { getBaseLeafStyle } from "./utils";

export const Video = createLitComponent(
  VideoApi,
  ({ props }) => html`
  <video
    src=${props.url ?? ""}
    controls
    style=${styleMap({
      ...getBaseLeafStyle(),
      width: "100%",
      aspectRatio: "16/9",
    })}
  ></video>
`,
);

// packages/angular/src/a2ui/lib/basic/video.ts
import { Component } from "@angular/core";
import { VideoApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-video",
  template: `
    <video class="video" controls [src]="props().url ?? ''"></video>
  `,
  styles: `
    :host {
      display: block;
    }
    .video {
      width: 100%;
      aspect-ratio: 16 / 9;
      box-sizing: border-box;
    }
  `,
})
export class CopilotA2UIVideo extends CopilotA2UIBasicComponent<
  typeof VideoApi
> {}
