// packages/react-core/src/v2/components/chat/CopilotModalHeader.tsx
import React, { useCallback, useEffect, useState } from "react";

import { cn } from "../../lib/utils";
import {
  useCopilotChatConfiguration,
  CopilotChatDefaultLabels,
} from "../../providers/CopilotChatConfigurationProvider";
import type { WithSlots } from "../../lib/slots";
import { renderSlot } from "../../lib/slots";
import { History, X } from "lucide-react";

type HeaderSlots = {
  titleContent: typeof CopilotModalHeader.Title;
  closeButton: typeof CopilotModalHeader.CloseButton;
  drawerLauncher: typeof CopilotModalHeader.DrawerLauncher;
};

type HeaderRestProps = {
  title?: string;
} & Omit<React.HTMLAttributes<HTMLDivElement>, "children">;

/**
 * Payload handed to the optional `children` render function. `drawerLauncher`
 * is nullable because the launcher is rendered only when a drawer has
 * registered — when none is present, custom layouts receive `null` and can omit
 * the launcher slot entirely.
 */
type HeaderChildrenPayload = {
  titleContent: React.ReactElement;
  closeButton: React.ReactElement;
  drawerLauncher: React.ReactElement | null;
  title?: string;
} & Omit<HeaderRestProps, "title">;

export type CopilotModalHeaderProps = Omit<
  WithSlots<HeaderSlots, HeaderRestProps>,
  "children"
> & {
  children?: (props: HeaderChildrenPayload) => React.ReactNode;
};

/**
 * Reactively tracks whether the viewport is in the mobile range (≤767px) — the
 * same breakpoint the drawer + chat coordination use. SSR-safe: starts `false`
 * (desktop) so the server render and first client render agree, then syncs on
 * mount and on resize.
 */
function useIsMobileViewport(): boolean {
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    if (
      typeof window === "undefined" ||
      typeof window.matchMedia !== "function"
    ) {
      return;
    }
    const mql = window.matchMedia("(max-width: 767px)");
    const update = () => setIsMobile(mql.matches);
    update();
    mql.addEventListener("change", update);
    return () => mql.removeEventListener("change", update);
  }, []);
  return isMobile;
}

export function CopilotModalHeader({
  title,
  titleContent,
  closeButton,
  drawerLauncher,
  children,
  className,
  ...rest
}: CopilotModalHeaderProps) {
  const configuration = useCopilotChatConfiguration();

  const fallbackTitle =
    configuration?.labels.modalHeaderTitle ??
    CopilotChatDefaultLabels.modalHeaderTitle;
  const resolvedTitle = title ?? fallbackTitle;

  // The thread-list launcher renders ONLY when a <CopilotThreadsDrawer> wrapper has
  // registered with the chat configuration AND the drawer is an overlay: either
  // the mobile off-canvas drawer, or a drawer hosted inside this modal
  // (`threadsDrawer` on the popup/sidebar), which is an overlay at every width.
  // On desktop a standalone drawer is an in-flow, persistent panel (it ignores
  // `open`), so an "open the drawer" launcher there would be a dead no-op.
  // Chats with no drawer get no launcher and no behavior change.
  const isMobile = useIsMobileViewport();
  const drawerOverlay = configuration?.ɵdrawerOverlay === true;
  const drawerRegistered =
    (configuration?.drawerRegistered ?? false) && (isMobile || drawerOverlay);

  const handleClose = useCallback(() => {
    configuration?.setModalOpen?.(false);
  }, [configuration]);

  const handleToggleDrawer = useCallback(() => {
    configuration?.setDrawerOpen?.(!configuration.drawerOpen);
  }, [configuration]);

  const BoundTitle = renderSlot(titleContent, CopilotModalHeader.Title, {
    children: resolvedTitle,
  });

  const BoundCloseButton = renderSlot(
    closeButton,
    CopilotModalHeader.CloseButton,
    {
      onClick: handleClose,
    },
  );

  // Only bind the launcher slot when a drawer is registered. When no drawer is
  // present, `BoundDrawerLauncher` is null and nothing is rendered.
  const BoundDrawerLauncher = drawerRegistered
    ? renderSlot(drawerLauncher, CopilotModalHeader.DrawerLauncher, {
        onClick: handleToggleDrawer,
        "aria-expanded": configuration?.drawerOpen ?? false,
      })
    : null;

  if (children) {
    return children({
      titleContent: BoundTitle,
      closeButton: BoundCloseButton,
      drawerLauncher: BoundDrawerLauncher,
      title: resolvedTitle,
      ...rest,
    });
  }

  return (
    <header
      data-copilotkit
      data-testid="copilot-modal-header"
      data-slot="copilot-modal-header"
      className={cn(
        "copilotKitHeader",
        "cpk:flex cpk:min-h-14 cpk:shrink-0 cpk:items-center cpk:justify-between cpk:border-b cpk:border-border cpk:px-3",
        "cpk:bg-background/95 cpk:backdrop-blur cpk:supports-[backdrop-filter]:bg-background/80",
        className,
      )}
      {...rest}
    >
      <div className="cpk:flex cpk:w-full cpk:items-center cpk:gap-2">
        <div className="cpk:flex cpk:flex-1 cpk:justify-start">
          {BoundDrawerLauncher ?? <span aria-hidden="true" />}
        </div>
        <div className="cpk:flex cpk:flex-1 cpk:justify-center cpk:text-center">
          {BoundTitle}
        </div>
        <div className="cpk:flex cpk:flex-1 cpk:justify-end">
          {BoundCloseButton}
        </div>
      </div>
    </header>
  );
}

CopilotModalHeader.displayName = "CopilotModalHeader";

export namespace CopilotModalHeader {
  export const Title: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
    children,
    className,
    ...props
  }) => (
    <div
      data-testid="copilot-header-title"
      className={cn(
        "cpk:w-full cpk:truncate cpk:text-sm cpk:font-semibold cpk:leading-none cpk:text-foreground",
        className,
      )}
      {...props}
    >
      {children}
    </div>
  );

  export const CloseButton: React.FC<
    React.ButtonHTMLAttributes<HTMLButtonElement>
  > = ({ className, children, ...props }) => (
    <button
      type="button"
      data-testid="copilot-close-button"
      className={cn(
        "cpk:inline-flex cpk:size-8 cpk:items-center cpk:justify-center cpk:rounded-lg cpk:text-muted-foreground cpk:transition-colors cpk:cursor-pointer",
        "cpk:hover:bg-accent cpk:hover:text-foreground cpk:focus-visible:outline-none cpk:focus-visible:ring-2 cpk:focus-visible:ring-ring/50",
        className,
      )}
      aria-label="Close"
      {...props}
    >
      {children ?? <X className="cpk:size-4" aria-hidden="true" />}
    </button>
  );

  /**
   * The thread-list launcher button. Rendered in the header ONLY when a
   * `<CopilotThreadsDrawer>` wrapper has registered with the chat configuration
   * and the drawer is an overlay (mobile, or hosted inside the modal); it
   * toggles the drawer open state. The stable `data-testid` is the focus-return
   * target for the drawer wrapper on cancel/back/backdrop/Escape.
   */
  export const DrawerLauncher: React.FC<
    React.ButtonHTMLAttributes<HTMLButtonElement>
  > = ({ className, ...props }) => (
    <button
      type="button"
      data-testid="copilot-threads-drawer-launcher"
      className={cn(
        "cpk:inline-flex cpk:size-8 cpk:items-center cpk:justify-center cpk:rounded-lg cpk:text-muted-foreground cpk:transition-colors cpk:cursor-pointer",
        "cpk:hover:bg-accent cpk:hover:text-foreground cpk:focus-visible:outline-none cpk:focus-visible:ring-2 cpk:focus-visible:ring-ring/50",
        className,
      )}
      aria-label="Open threads"
      {...props}
    >
      <History className="cpk:size-4" aria-hidden="true" />
    </button>
  );
}

CopilotModalHeader.Title.displayName = "CopilotModalHeader.Title";
CopilotModalHeader.CloseButton.displayName = "CopilotModalHeader.CloseButton";
CopilotModalHeader.DrawerLauncher.displayName =
  "CopilotModalHeader.DrawerLauncher";

export default CopilotModalHeader;

// packages/vue/src/v2/components/chat/CopilotModalHeader.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useAttrs } from "vue";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import { CopilotChatDefaultLabels } from "../../providers/types";
import { MOBILE_MAX_WIDTH_QUERY } from "../../lib/is-mobile-viewport";
import CopilotModalHeaderCloseButton from "./CopilotModalHeaderCloseButton";
import CopilotModalHeaderTitle from "./CopilotModalHeaderTitle";
import { IconHistory } from "../icons";
import type {
  CopilotModalHeaderCloseButtonSlotProps,
  CopilotModalHeaderLayoutSlotProps,
  CopilotModalHeaderProps,
  CopilotModalHeaderTitleContentSlotProps,
} from "./types";

defineOptions({ inheritAttrs: false });

const props = defineProps<CopilotModalHeaderProps>();

defineSlots<{
  "title-content"?: (props: CopilotModalHeaderTitleContentSlotProps) => unknown;
  "close-button"?: (props: CopilotModalHeaderCloseButtonSlotProps) => unknown;
  layout?: (props: CopilotModalHeaderLayoutSlotProps) => unknown;
}>();

const attrs = useAttrs();
const config = useCopilotChatConfiguration();

const resolvedTitle = computed(
  () =>
    props.title ??
    config.value?.labels.modalHeaderTitle ??
    CopilotChatDefaultLabels.modalHeaderTitle,
);
const headerClass = computed(() => [
  "cpk:flex cpk:min-h-14 cpk:shrink-0 cpk:items-center cpk:justify-between cpk:border-b cpk:border-border cpk:px-3",
  "cpk:bg-background/95 cpk:backdrop-blur cpk:supports-[backdrop-filter]:bg-background/80",
  attrs.class,
]);
const headerAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});

function handleClose() {
  config.value?.setModalOpen?.(false);
}

// Tracks whether the viewport is in the mobile range (MOBILE_MAX_WIDTH_QUERY) — the same
// breakpoint the drawer + chat coordination use. SSR-safe: starts `false`
// (desktop) so the server render and first client render agree, then syncs
// on mount and on viewport changes.
const isMobile = ref(false);
let mobileMediaQuery: MediaQueryList | null = null;

function syncIsMobile() {
  if (mobileMediaQuery) {
    isMobile.value = mobileMediaQuery.matches;
  }
}

onMounted(() => {
  if (
    typeof window === "undefined" ||
    typeof window.matchMedia !== "function"
  ) {
    return;
  }
  mobileMediaQuery = window.matchMedia(MOBILE_MAX_WIDTH_QUERY);
  mobileMediaQuery.addEventListener("change", syncIsMobile);
  syncIsMobile();
});

onBeforeUnmount(() => {
  mobileMediaQuery?.removeEventListener("change", syncIsMobile);
  mobileMediaQuery = null;
});

// The thread-list launcher renders ONLY when a <CopilotThreadsDrawer> wrapper
// has registered with the chat configuration AND the viewport is mobile. On
// desktop the drawer is an in-flow, persistent panel (it ignores `open`), so
// an "open the drawer" launcher there is a dead no-op — it only does
// anything for the mobile off-canvas drawer. Chats with no drawer get no
// launcher and no behavior change.
// A drawer hosted inside this modal (`threads-drawer` on the popup/sidebar)
// is an overlay at every width, so its launcher shows on desktop too.
const showDrawerLauncher = computed(
  () =>
    (config.value?.drawerRegistered ?? false) &&
    (isMobile.value || config.value?.ɵdrawerOverlay === true),
);

function toggleDrawer() {
  config.value?.setDrawerOpen?.(!config.value?.drawerOpen);
}
</script>

<template>
  <header
    data-copilotkit
    data-slot="copilot-modal-header"
    :class="headerClass"
    v-bind="headerAttrs"
  >
    <slot name="layout" :title="resolvedTitle" :on-close="handleClose">
      <div class="cpk:flex cpk:w-full cpk:items-center cpk:gap-2">
        <div class="cpk:flex cpk:flex-1 cpk:justify-start">
          <button
            v-if="showDrawerLauncher"
            type="button"
            data-testid="drawer-launcher"
            class="cpk:inline-flex cpk:size-8 cpk:items-center cpk:justify-center cpk:rounded-lg cpk:text-muted-foreground cpk:transition-colors cpk:cursor-pointer cpk:hover:bg-accent cpk:hover:text-foreground cpk:focus-visible:outline-none cpk:focus-visible:ring-2 cpk:focus-visible:ring-ring/50"
            :aria-expanded="config?.drawerOpen ?? false"
            aria-label="Open threads"
            @click="toggleDrawer"
          >
            <IconHistory class="cpk:size-4" aria-hidden="true" />
          </button>
          <span v-else aria-hidden="true" />
        </div>
        <div class="cpk:flex cpk:flex-1 cpk:justify-center cpk:text-center">
          <slot name="title-content" :title="resolvedTitle">
            <CopilotModalHeaderTitle>
              {{ resolvedTitle }}
            </CopilotModalHeaderTitle>
          </slot>
        </div>
        <div class="cpk:flex cpk:flex-1 cpk:justify-end">
          <slot name="close-button" :on-close="handleClose">
            <CopilotModalHeaderCloseButton @click="handleClose" />
          </slot>
        </div>
      </div>
    </slot>
  </header>
</template>
