// packages/svelte/src/components/chat/CopilotChatAssistantMessage.svelte
<script lang="ts">
  import type { AssistantMessage, Message } from "@ag-ui/core";
  import type { Snippet } from "svelte";
  import { IconCheck, IconCopy, IconThumbsUp, IconThumbsDown, IconVolume2, IconRefreshCw } from "../icons";
  import { getChatConfig } from "./chat-config-context.svelte";
  import StreamMarkdown from "./StreamMarkdown.svelte";
  import CopilotChatToolCallsView from "./CopilotChatToolCallsView.svelte";

  interface MessageRendererProps {
    message: AssistantMessage;
    content: string;
  }

  interface ToolbarProps {
    message: AssistantMessage;
    shouldShowToolbar: boolean;
  }

  interface CopyButtonProps {
    onCopy: () => Promise<void>;
    copied: boolean;
    label: string;
  }

  interface ThumbsUpButtonProps {
    onThumbsUp: () => void;
    label: string;
  }

  interface ThumbsDownButtonProps {
    onThumbsDown: () => void;
    label: string;
  }

  interface ReadAloudButtonProps {
    onReadAloud: () => void;
    label: string;
  }

  interface RegenerateButtonProps {
    onRegenerate: () => void;
    label: string;
  }

  interface ToolCallsViewProps {
    message: AssistantMessage;
    messages: Message[];
  }

  interface LayoutProps {
    message: AssistantMessage;
    content: string;
    isRunning: boolean;
    toolbarVisible: boolean;
    shouldShowToolbar: boolean;
    messageRenderer: unknown;
    toolbar: unknown;
    copyButton: unknown;
    thumbsUpButton: unknown;
    thumbsDownButton: unknown;
    readAloudButton: unknown;
    regenerateButton: unknown;
    toolCallsView: unknown;
    onCopy: () => Promise<void>;
    onThumbsUp: () => void;
    onThumbsDown: () => void;
    onReadAloud: () => void;
    onRegenerate: () => void;
  }

  const defaultLabels = {
    assistantMessageToolbarCopyMessageLabel: "Copy",
    assistantMessageToolbarThumbsUpLabel: "Good response",
    assistantMessageToolbarThumbsDownLabel: "Bad response",
    assistantMessageToolbarReadAloudLabel: "Read aloud",
    assistantMessageToolbarRegenerateLabel: "Regenerate",
  };

  let {
    message,
    messages = [] as Message[],
    isRunning = false,
    toolbarVisible = true,
    layout,
    messageRenderer,
    toolbar: toolbarSnippet,
    copyButton,
    thumbsUpButton,
    thumbsDownButton,
    readAloudButton,
    regenerateButton,
    toolCallsView,
    toolbarItems,
    onThumbsUp,
    onThumbsDown,
    onReadAloud,
    onRegenerate,
    children,
  }: {
    message: AssistantMessage;
    messages?: Message[];
    isRunning?: boolean;
    toolbarVisible?: boolean;
    layout?: Snippet<[LayoutProps]>;
    messageRenderer?: Snippet<[MessageRendererProps]>;
    toolbar?: Snippet<[ToolbarProps]>;
    copyButton?: Snippet<[CopyButtonProps]>;
    thumbsUpButton?: Snippet<[ThumbsUpButtonProps]>;
    thumbsDownButton?: Snippet<[ThumbsDownButtonProps]>;
    readAloudButton?: Snippet<[ReadAloudButtonProps]>;
    regenerateButton?: Snippet<[RegenerateButtonProps]>;
    toolCallsView?: Snippet<[ToolCallsViewProps]>;
    toolbarItems?: Snippet<[]>;
    children?: Snippet<[]>;
    onThumbsUp?: (message: AssistantMessage) => void;
    onThumbsDown?: (message: AssistantMessage) => void;
    onReadAloud?: (message: AssistantMessage) => void;
    onRegenerate?: (message: AssistantMessage) => void;
  } = $props();

  let copied = $state(false);
  let copiedResetTimeout: ReturnType<typeof setTimeout> | null = null;

  const config = getChatConfig();
  const labels = config?.labels ?? defaultLabels;

  function normalizeContent(content: unknown): string {
    if (!content) return "";
    if (typeof content === "string") return content;
    if (Array.isArray(content)) {
      return content
        .map((part) => {
          if (part && typeof part === "object" && "type" in part && part.type === "text" && typeof part.text === "string") {
            return part.text;
          }
          return "";
        })
        .filter((text) => text.length > 0)
        .join("\n");
    }
    return "";
  }

  const normalizedContent = $derived(normalizeContent(message.content));
  const hasContent = $derived(normalizedContent.trim().length > 0);
  const isLatestAssistantMessage = $derived(messages[messages.length - 1]?.id === message.id);
  const shouldShowToolbar = $derived(toolbarVisible && hasContent && !(isRunning && isLatestAssistantMessage));

  function resetCopiedStateWithDelay() {
    if (copiedResetTimeout) clearTimeout(copiedResetTimeout);
    copied = true;
    copiedResetTimeout = setTimeout(() => {
      copied = false;
      copiedResetTimeout = null;
    }, 2000);
  }

  async function handleCopyMessage() {
    if (!normalizedContent) return;
    if (typeof navigator === "undefined" || typeof navigator.clipboard?.writeText !== "function") return;
    try {
      await navigator.clipboard.writeText(normalizedContent);
      resetCopiedStateWithDelay();
    } catch (error) {
      console.error("Failed to copy to clipboard:", error);
    }
  }

  function handleThumbsUp() { onThumbsUp?.(message); }
  function handleThumbsDown() { onThumbsDown?.(message); }
  function handleReadAloud() { onReadAloud?.(message); }
  function handleRegenerate() { onRegenerate?.(message); }

  const toolbarBtnClass = "cpk:inline-flex cpk:h-8 cpk:w-8 cpk:items-center cpk:justify-center cpk:rounded-md cpk:p-0 cpk:cursor-pointer cpk:text-[rgb(93,93,93)] cpk:transition-colors cpk:hover:bg-[#E8E8E8] cpk:hover:text-[rgb(93,93,93)] cpk:dark:text-[rgb(243,243,243)] cpk:dark:hover:bg-[#303030] cpk:dark:hover:text-[rgb(243,243,243)] cpk:disabled:pointer-events-none cpk:disabled:opacity-50";
</script>

<div
  data-copilotkit
  data-testid="copilot-assistant-message"
  class="cpk:prose cpk:max-w-full cpk:break-words cpk:dark:prose-invert"
  data-message-id={message.id}
>
  {#if messageRenderer}
    {@render messageRenderer({ message, content: normalizedContent })}
  {:else}
    {#if hasContent}
      <StreamMarkdown content={normalizedContent} />
    {/if}
  {/if}

  {#if toolCallsView}
    {@render toolCallsView({ message, messages })}
  {:else}
    <CopilotChatToolCallsView {message} {messages} />
  {/if}

  {#if shouldShowToolbar}
    {#if toolbarSnippet}
      {@render toolbarSnippet({ message, shouldShowToolbar })}
    {:else}
      <div class="cpk:w-full cpk:bg-transparent cpk:flex cpk:items-center cpk:-ml-[5px] cpk:-mt-[0px]">
        <div class="cpk:flex cpk:items-center cpk:gap-1">
          {#if copyButton}
            {@render copyButton({ onCopy: handleCopyMessage, copied, label: labels.assistantMessageToolbarCopyMessageLabel as string })}
          {:else}
            <button
              data-testid="copilot-copy-button"
              type="button"
              class={toolbarBtnClass}
              aria-label={labels.assistantMessageToolbarCopyMessageLabel as string}
              title={labels.assistantMessageToolbarCopyMessageLabel as string}
              onclick={handleCopyMessage}
            >
              {#if copied}
                <IconCheck class="cpk:size-[18px]" />
              {:else}
                <IconCopy class="cpk:size-[18px]" />
              {/if}
            </button>
          {/if}

          {#if onThumbsUp}
            {#if thumbsUpButton}
              {@render thumbsUpButton({ onThumbsUp: handleThumbsUp, label: labels.assistantMessageToolbarThumbsUpLabel as string })}
            {:else}
              <button
                type="button"
                class={toolbarBtnClass}
                aria-label={labels.assistantMessageToolbarThumbsUpLabel as string}
                title={labels.assistantMessageToolbarThumbsUpLabel as string}
                onclick={handleThumbsUp}
              >
                <IconThumbsUp class="cpk:size-[18px]" />
              </button>
            {/if}
          {/if}

          {#if onThumbsDown}
            {#if thumbsDownButton}
              {@render thumbsDownButton({ onThumbsDown: handleThumbsDown, label: labels.assistantMessageToolbarThumbsDownLabel as string })}
            {:else}
              <button
                type="button"
                class={toolbarBtnClass}
                aria-label={labels.assistantMessageToolbarThumbsDownLabel as string}
                title={labels.assistantMessageToolbarThumbsDownLabel as string}
                onclick={handleThumbsDown}
              >
                <IconThumbsDown class="cpk:size-[18px]" />
              </button>
            {/if}
          {/if}

          {#if onReadAloud}
            {#if readAloudButton}
              {@render readAloudButton({ onReadAloud: handleReadAloud, label: labels.assistantMessageToolbarReadAloudLabel as string })}
            {:else}
              <button
                type="button"
                class={toolbarBtnClass}
                aria-label={labels.assistantMessageToolbarReadAloudLabel as string}
                title={labels.assistantMessageToolbarReadAloudLabel as string}
                onclick={handleReadAloud}
              >
                <IconVolume2 class="cpk:size-[20px]" />
              </button>
            {/if}
          {/if}

          {#if onRegenerate}
            {#if regenerateButton}
              {@render regenerateButton({ onRegenerate: handleRegenerate, label: labels.assistantMessageToolbarRegenerateLabel as string })}
            {:else}
              <button
                type="button"
                class={toolbarBtnClass}
                aria-label={labels.assistantMessageToolbarRegenerateLabel as string}
                title={labels.assistantMessageToolbarRegenerateLabel as string}
                onclick={handleRegenerate}
              >
                <IconRefreshCw class="cpk:size-[18px]" />
              </button>
            {/if}
          {/if}

          {#if toolbarItems}{@render toolbarItems()}{/if}
        </div>
      </div>
    {/if}
  {/if}
</div>

// packages/vue/src/v2/components/chat/CopilotChatAssistantMessage.vue
<script setup lang="ts">
import { computed, getCurrentInstance, onBeforeUnmount, ref } from "vue";
import type { AssistantMessage, Message } from "@ag-ui/core";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import { CopilotChatDefaultLabels } from "../../providers/types";
import {
  IconCheck,
  IconCopy,
  IconRefreshCw,
  IconThumbsDown,
  IconThumbsUp,
  IconVolume2,
} from "../icons";
import BasicMarkdown from "./BasicMarkdown.vue";
import { useMarkdownRenderer } from "../../providers/markdown-renderer";
import CopilotChatToolCallsView from "./CopilotChatToolCallsView.vue";
import type {
  CopilotChatAssistantMessageCopyButtonSlotProps,
  CopilotChatAssistantMessageLayoutSlotProps,
  CopilotChatAssistantMessageMessageRendererSlotProps,
  CopilotChatAssistantMessageReadAloudButtonSlotProps,
  CopilotChatAssistantMessageRegenerateButtonSlotProps,
  CopilotChatAssistantMessageThumbsDownButtonSlotProps,
  CopilotChatAssistantMessageThumbsUpButtonSlotProps,
  CopilotChatAssistantMessageToolCallsViewSlotProps,
  CopilotChatAssistantMessageToolbarSlotProps,
} from "./types";
const props = withDefaults(
  defineProps<{
    message: AssistantMessage;
    messages?: Message[];
    isRunning?: boolean;
    toolbarVisible?: boolean;
  }>(),
  {
    messages: () => [],
    isRunning: false,
    toolbarVisible: true,
  },
);

defineSlots<{
  layout?: (props: CopilotChatAssistantMessageLayoutSlotProps) => unknown;
  "message-renderer"?: (
    props: CopilotChatAssistantMessageMessageRendererSlotProps,
  ) => unknown;
  toolbar?: (props: CopilotChatAssistantMessageToolbarSlotProps) => unknown;
  "copy-button"?: (
    props: CopilotChatAssistantMessageCopyButtonSlotProps,
  ) => unknown;
  "thumbs-up-button"?: (
    props: CopilotChatAssistantMessageThumbsUpButtonSlotProps,
  ) => unknown;
  "thumbs-down-button"?: (
    props: CopilotChatAssistantMessageThumbsDownButtonSlotProps,
  ) => unknown;
  "read-aloud-button"?: (
    props: CopilotChatAssistantMessageReadAloudButtonSlotProps,
  ) => unknown;
  "regenerate-button"?: (
    props: CopilotChatAssistantMessageRegenerateButtonSlotProps,
  ) => unknown;
  "tool-calls-view"?: (
    props: CopilotChatAssistantMessageToolCallsViewSlotProps,
  ) => unknown;
  "toolbar-items"?: () => unknown;
  [key: string]: ((props: any) => unknown) | undefined;
}>();

const emit = defineEmits<{
  "thumbs-up": [message: AssistantMessage];
  "thumbs-down": [message: AssistantMessage];
  "read-aloud": [message: AssistantMessage];
  regenerate: [message: AssistantMessage];
}>();

const config = useCopilotChatConfiguration();
const labels = computed(() => config.value?.labels ?? CopilotChatDefaultLabels);
const instance = getCurrentInstance();
const copied = ref(false);
let copiedResetTimeout: ReturnType<typeof setTimeout> | null = null;
const vnodeProps = computed(
  () => (instance?.vnode.props ?? {}) as Record<string, unknown>,
);

const toolbarButtonClass = [
  "cpk:inline-flex cpk:h-8 cpk:w-8 cpk:items-center cpk:justify-center cpk:rounded-md cpk:p-0",
  "cpk:cursor-pointer cpk:text-[rgb(93,93,93)] cpk:transition-colors cpk:hover:bg-[#E8E8E8]",
  "cpk:hover:text-[rgb(93,93,93)] cpk:dark:text-[rgb(243,243,243)] cpk:dark:hover:bg-[#303030]",
  "cpk:dark:hover:text-[rgb(243,243,243)] cpk:disabled:pointer-events-none cpk:disabled:opacity-50",
].join(" ");

function normalizeContent(content: unknown): string {
  if (!content) {
    return "";
  }

  if (typeof content === "string") {
    return content;
  }

  if (Array.isArray(content)) {
    const parts = content as Array<{ type?: unknown; text?: unknown }>;
    return parts
      .map((part) => {
        if (
          part &&
          typeof part === "object" &&
          "type" in part &&
          part.type === "text" &&
          typeof part.text === "string"
        ) {
          return part.text;
        }
        return "";
      })
      .filter((text) => text.length > 0)
      .join("\n");
  }

  return "";
}

const normalizedContent = computed(() =>
  normalizeContent(props.message.content),
);
const hasContent = computed(() => normalizedContent.value.trim().length > 0);

const providerMarkdownRenderer = useMarkdownRenderer();
const ActiveMarkdownRenderer = computed(
  () => providerMarkdownRenderer ?? BasicMarkdown,
);

function hasListener(listenerName: string) {
  const listener = vnodeProps.value[listenerName];
  if (Array.isArray(listener)) {
    return listener.length > 0;
  }
  return !!listener;
}

const hasThumbsUp = computed(() => hasListener("onThumbsUp"));
const hasThumbsDown = computed(() => hasListener("onThumbsDown"));
const hasReadAloud = computed(() => hasListener("onReadAloud"));
const hasRegenerate = computed(() => hasListener("onRegenerate"));
const isLatestAssistantMessage = computed(
  () => props.messages[props.messages.length - 1]?.id === props.message.id,
);
const shouldShowToolbar = computed(
  () =>
    props.toolbarVisible &&
    hasContent.value &&
    !(props.isRunning && isLatestAssistantMessage.value),
);

function resetCopiedStateWithDelay() {
  if (copiedResetTimeout) {
    clearTimeout(copiedResetTimeout);
  }
  copied.value = true;
  copiedResetTimeout = setTimeout(() => {
    copied.value = false;
    copiedResetTimeout = null;
  }, 2000);
}

async function handleCopyMessage() {
  const content = normalizedContent.value;
  if (!content) return;

  if (
    typeof navigator === "undefined" ||
    typeof navigator.clipboard?.writeText !== "function"
  ) {
    return;
  }

  try {
    await navigator.clipboard.writeText(content);
    resetCopiedStateWithDelay();
  } catch (error) {
    console.error("Failed to copy to clipboard:", error);
  }
}

function handleThumbsUp() {
  emit("thumbs-up", props.message);
}

function handleThumbsDown() {
  emit("thumbs-down", props.message);
}

function handleReadAloud() {
  emit("read-aloud", props.message);
}

function handleRegenerate() {
  emit("regenerate", props.message);
}

onBeforeUnmount(() => {
  if (copiedResetTimeout) {
    clearTimeout(copiedResetTimeout);
  }
});
</script>

<template>
  <slot
    name="layout"
    :message="message"
    :content="normalizedContent"
    :is-running="isRunning"
    :toolbar-visible="toolbarVisible"
    :should-show-toolbar="shouldShowToolbar"
    :message-renderer="$slots['message-renderer'] ?? (() => null)"
    :toolbar="$slots['toolbar'] ?? (() => null)"
    :copy-button="$slots['copy-button'] ?? (() => null)"
    :thumbs-up-button="$slots['thumbs-up-button'] ?? (() => null)"
    :thumbs-down-button="$slots['thumbs-down-button'] ?? (() => null)"
    :read-aloud-button="$slots['read-aloud-button'] ?? (() => null)"
    :regenerate-button="$slots['regenerate-button'] ?? (() => null)"
    :tool-calls-view="$slots['tool-calls-view'] ?? (() => null)"
    :on-copy="handleCopyMessage"
    :on-thumbs-up="handleThumbsUp"
    :on-thumbs-down="handleThumbsDown"
    :on-read-aloud="handleReadAloud"
    :on-regenerate="handleRegenerate"
  >
    <div
      data-copilotkit
      data-testid="copilot-assistant-message"
      class="cpk:prose cpk:max-w-full cpk:break-words cpk:dark:prose-invert"
      :data-message-id="message.id"
      v-bind="$attrs"
    >
      <slot
        name="message-renderer"
        :message="message"
        :content="normalizedContent"
      >
        <component
          :is="ActiveMarkdownRenderer"
          v-if="hasContent"
          :content="normalizedContent"
          :is-streaming="isRunning && isLatestAssistantMessage"
        />
      </slot>

      <slot name="tool-calls-view" :message="message" :messages="messages">
        <CopilotChatToolCallsView :message="message" :messages="messages">
          <template
            v-for="(_, slotName) in $slots"
            :key="slotName"
            #[slotName]="slotProps"
          >
            <slot :name="slotName" v-bind="slotProps" />
          </template>
        </CopilotChatToolCallsView>
      </slot>

      <slot
        v-if="shouldShowToolbar"
        name="toolbar"
        :message="message"
        :should-show-toolbar="shouldShowToolbar"
      >
        <div
          class="cpk:w-full cpk:bg-transparent cpk:flex cpk:items-center cpk:-ml-[5px] cpk:-mt-[0px]"
        >
          <div class="cpk:flex cpk:items-center cpk:gap-1">
            <slot
              name="copy-button"
              :on-copy="handleCopyMessage"
              :copied="copied"
              :label="labels.assistantMessageToolbarCopyMessageLabel"
            >
              <button
                data-testid="copilot-copy-button"
                type="button"
                :class="toolbarButtonClass"
                :aria-label="labels.assistantMessageToolbarCopyMessageLabel"
                :title="labels.assistantMessageToolbarCopyMessageLabel"
                @click="handleCopyMessage"
              >
                <IconCheck v-if="copied" class="cpk:size-[18px]" />
                <IconCopy v-else class="cpk:size-[18px]" />
              </button>
            </slot>

            <slot
              v-if="hasThumbsUp"
              name="thumbs-up-button"
              :on-thumbs-up="handleThumbsUp"
              :label="labels.assistantMessageToolbarThumbsUpLabel"
            >
              <button
                type="button"
                :class="toolbarButtonClass"
                :aria-label="labels.assistantMessageToolbarThumbsUpLabel"
                :title="labels.assistantMessageToolbarThumbsUpLabel"
                @click="handleThumbsUp"
              >
                <IconThumbsUp class="cpk:size-[18px]" />
              </button>
            </slot>

            <slot
              v-if="hasThumbsDown"
              name="thumbs-down-button"
              :on-thumbs-down="handleThumbsDown"
              :label="labels.assistantMessageToolbarThumbsDownLabel"
            >
              <button
                type="button"
                :class="toolbarButtonClass"
                :aria-label="labels.assistantMessageToolbarThumbsDownLabel"
                :title="labels.assistantMessageToolbarThumbsDownLabel"
                @click="handleThumbsDown"
              >
                <IconThumbsDown class="cpk:size-[18px]" />
              </button>
            </slot>

            <slot
              v-if="hasReadAloud"
              name="read-aloud-button"
              :on-read-aloud="handleReadAloud"
              :label="labels.assistantMessageToolbarReadAloudLabel"
            >
              <button
                type="button"
                :class="toolbarButtonClass"
                :aria-label="labels.assistantMessageToolbarReadAloudLabel"
                :title="labels.assistantMessageToolbarReadAloudLabel"
                @click="handleReadAloud"
              >
                <IconVolume2 class="cpk:size-[20px]" />
              </button>
            </slot>

            <slot
              v-if="hasRegenerate"
              name="regenerate-button"
              :on-regenerate="handleRegenerate"
              :label="labels.assistantMessageToolbarRegenerateLabel"
            >
              <button
                type="button"
                :class="toolbarButtonClass"
                :aria-label="labels.assistantMessageToolbarRegenerateLabel"
                :title="labels.assistantMessageToolbarRegenerateLabel"
                @click="handleRegenerate"
              >
                <IconRefreshCw class="cpk:size-[18px]" />
              </button>
            </slot>

            <slot name="toolbar-items" />
          </div>
        </div>
      </slot>
    </div>
  </slot>
</template>
