// examples/experiments/a2ui-private/original_a2ui_source/samples/client/angular/projects/lib/src/lib/catalog/divider.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';

@Component({
  selector: 'a2ui-divider',
  template: '<hr [class]="theme.components.Divider" [style]="theme.additionalStyles?.Divider"/>',
  styles: `
    :host {
      display: block;
      min-height: 0;
      overflow: auto;
    }

    hr {
      height: 1px;
      background: #ccc;
      border: none;
    }
  `,
})
export class Divider extends DynamicComponent {}

// packages/a2ui-renderer/src/react-renderer/a2ui-react/catalog/basic/components/Divider.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from "react";
import { createReactComponent } from "../../../adapter";
import { DividerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { LEAF_MARGIN } from "../utils";

export const Divider = createReactComponent(DividerApi, ({ props }) => {
  const isVertical = props.axis === "vertical";
  const style: React.CSSProperties = {
    margin: LEAF_MARGIN,
    border: "none",
    backgroundColor: "#ccc",
  };

  if (isVertical) {
    style.width = "1px";
    style.height = "100%";
  } else {
    style.width = "100%";
    style.height = "1px";
  }

  return <div style={style} />;
});
