// examples/experiments/a2ui-private/original_a2ui_source/samples/client/angular/projects/lib/src/lib/catalog/list.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, input } from '@angular/core';
import * as v0_8 from '@a2ui/web-lib/0.8';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';

@Component({
  selector: 'a2ui-list',
  imports: [Renderer],
  host: {
    '[attr.direction]': 'direction()',
  },
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
      overflow: auto;
    }

    :host([direction="vertical"]) section {
      display: grid;
    }

    :host([direction="horizontal"]) section {
      display: flex;
      max-width: 100%;
      overflow-x: scroll;
      overflow-y: hidden;
      scrollbar-width: none;

      > ::slotted(*) {
        flex: 1 0 fit-content;
        max-width: min(80%, 400px);
      }
    }
  `,
  template: `
    <section [class]="theme.components.List" [style]="theme.additionalStyles?.List">
      @for (child of component().properties.children; track child) {
        <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="child" />
      }
    </section>
  `,
})
export class List extends DynamicComponent<v0_8.Types.ListNode> {
  readonly direction = input<'vertical' | 'horizontal'>('vertical');
}

// packages/a2ui-renderer/src/react-renderer/a2ui-react/catalog/basic/components/List.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {ListApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {ChildList} from './ChildList';
import {mapAlign} from '../utils';

export const List = createReactComponent(ListApi, ({props, buildChild, context}) => {
  const isHorizontal = props.direction === 'horizontal';
  const style: React.CSSProperties = {
    display: 'flex',
    flexDirection: isHorizontal ? 'row' : 'column',
    alignItems: mapAlign(props.align),
    overflowX: isHorizontal ? 'auto' : 'hidden',
    overflowY: isHorizontal ? 'hidden' : 'auto',
    width: '100%',
    margin: 0,
    padding: 0,
  };

  return (
    <div style={style}>
      <ChildList childList={props.children} buildChild={buildChild} context={context} />
    </div>
  );
});
