// packages/angular/src/a2ui/lib/basic/button.ts
import { Component } from "@angular/core";
import { ButtonApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIChild } from "../child";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-button",
  imports: [CopilotA2UIChild],
  template: `
    <button
      type="button"
      class="button"
      [class.primary]="props().variant === 'primary'"
      [class.borderless]="props().variant === 'borderless'"
      [disabled]="props().isValid === false"
      (click)="props().action?.()"
    >
      <copilot-a2ui-child [child]="props().child" />
    </button>
  `,
  styles: `
    :host {
      display: inline-flex;
      flex-direction: column;
    }
    .button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      margin: var(--a2ui-spacing-m, 8px);
      padding: var(--a2ui-button-padding, 8px 16px);
      border: 1px solid var(--a2ui-color-border, #ccc);
      border-radius: var(--a2ui-button-border-radius, 4px);
      box-sizing: border-box;
      background-color: var(--a2ui-color-surface, #fff);
      color: inherit;
      cursor: pointer;
    }
    .primary {
      background-color: var(
        --a2ui-color-primary,
        var(--a2ui-primary-color, #007bff)
      );
      color: var(--a2ui-color-on-primary, #fff);
    }
    .borderless {
      border: none;
      background-color: transparent;
    }
  `,
})
export class CopilotA2UIButton extends CopilotA2UIBasicComponent<
  typeof ButtonApi
> {}

// packages/a2ui-renderer/src/web-components/catalog/basic/button.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { ButtonApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { LEAF_MARGIN } from "./utils";

export const Button = createLitComponent(
  ButtonApi,
  ({ props, buildChild }) => html`
    <button
      type="button"
      style=${styleMap({
        margin: LEAF_MARGIN,
        padding: "8px 16px",
        cursor: "pointer",
        border: props.variant === "borderless" ? "none" : "1px solid #ccc",
        backgroundColor:
          props.variant === "primary"
            ? "var(--a2ui-primary-color, #007bff)"
            : props.variant === "borderless"
              ? "transparent"
              : "#fff",
        color: props.variant === "primary" ? "#fff" : "inherit",
        borderRadius: "4px",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        boxSizing: "border-box",
      })}
      ?disabled=${props.isValid === false}
      @click=${() => props.action?.()}
    >
      ${props.child ? buildChild(props.child) : nothing}
    </button>
  `,
);
