// packages/angular/src/a2ui/lib/basic/choice-picker.ts
import { Component, computed, signal } from "@angular/core";
import { ChoicePickerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";
import { uniqueId } from "./shared";

@Component({
  selector: "copilot-a2ui-choice-picker",
  template: `
    @if (props().label) {
      <strong class="label">{{ props().label }}</strong>
    }
    @if (props().filterable) {
      <input
        #filterInput
        type="text"
        class="filter"
        placeholder="Filter options..."
        [value]="filter()"
        (input)="filter.set(filterInput.value)"
      />
    }
    <div class="options" [class.chips]="chips()">
      @for (option of options(); track option.value) {
        @if (chips()) {
          <button
            type="button"
            class="chip"
            [class.selected]="selected().includes(option.value)"
            [attr.aria-pressed]="selected().includes(option.value)"
            (click)="toggle(option.value)"
          >
            {{ option.label }}
          </button>
        } @else {
          <label class="option">
            <input
              [type]="exclusive() ? 'radio' : 'checkbox'"
              [name]="exclusive() ? groupName : ''"
              [checked]="selected().includes(option.value)"
              (change)="toggle(option.value)"
            />
            <span class="option-label">{{ option.label }}</span>
          </label>
        }
      }
    </div>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      gap: var(--a2ui-spacing-m, 8px);
      width: 100%;
    }
    .label {
      font-size: var(--a2ui-font-size-s, 14px);
    }
    .filter {
      padding: 4px 8px;
      background-color: var(--a2ui-color-input, Field);
      color: var(--a2ui-color-on-input, FieldText);
      border: 1px solid var(--a2ui-color-border, #ccc);
      border-radius: var(--a2ui-border-radius, 8px);
    }
    .options {
      display: flex;
      flex-direction: column;
      flex-wrap: nowrap;
      gap: var(--a2ui-spacing-m, 8px);
    }
    .options.chips {
      flex-direction: row;
      flex-wrap: wrap;
    }
    .chip {
      padding: 4px 12px;
      border: 1px solid var(--a2ui-color-border, #ccc);
      border-radius: var(--a2ui-chip-border-radius, 16px);
      background-color: var(--a2ui-color-surface, #fff);
      color: inherit;
      font-size: var(--a2ui-font-size-xs, 12px);
      cursor: pointer;
    }
    .chip.selected {
      border: 1px solid
        var(--a2ui-color-primary, var(--a2ui-primary-color, #007bff));
      background-color: var(
        --a2ui-color-primary,
        var(--a2ui-primary-color, #007bff)
      );
      color: var(--a2ui-color-on-primary, #fff);
    }
    .option {
      display: flex;
      align-items: center;
      gap: var(--a2ui-spacing-m, 8px);
      cursor: pointer;
    }
    .option-label {
      font-size: var(--a2ui-font-size-s, 14px);
    }
  `,
})
export class CopilotA2UIChoicePicker extends CopilotA2UIBasicComponent<
  typeof ChoicePickerApi
> {
  /** Per instance, so template-spawned pickers never share a radio group. */
  protected readonly groupName = uniqueId("choice");
  protected readonly filter = signal("");
  protected readonly chips = computed(
    () => this.props().displayStyle === "chips",
  );
  protected readonly exclusive = computed(
    () => this.props().variant === "mutuallyExclusive",
  );
  protected readonly selected = computed((): string[] => {
    const value: unknown = this.props().value;
    return Array.isArray(value) ? value : [];
  });
  protected readonly options = computed(() => {
    const { options, filterable } = this.props();
    const filter = this.filter().toLowerCase();
    return (options ?? []).filter(
      (option) =>
        !filterable ||
        filter === "" ||
        String(option.label).toLowerCase().includes(filter),
    );
  });

  protected toggle(value: string): void {
    const selected = this.selected();
    this.props().setValue(
      this.exclusive()
        ? [value]
        : selected.includes(value)
          ? selected.filter((item) => item !== value)
          : [...selected, value],
    );
  }
}

// packages/a2ui-renderer/src/web-components/catalog/basic/choice-picker.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { ChoicePickerApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { LEAF_MARGIN, STANDARD_BORDER, STANDARD_RADIUS } from "./utils";

export const ChoicePicker = createLitComponent(
  ChoicePickerApi,
  ({ props, context, state, requestUpdate }) => {
    const local = state as { filter: string };
    const values = Array.isArray(props.value) ? props.value : [];
    const isMutuallyExclusive = props.variant === "mutuallyExclusive";
    const onToggle = (val: string) => {
      if (isMutuallyExclusive) {
        props.setValue([val]);
      } else {
        props.setValue(
          values.includes(val)
            ? values.filter((v: string) => v !== val)
            : [...values, val],
        );
      }
    };
    const options = (props.options || []).filter(
      (opt: any) =>
        !props.filterable ||
        local.filter === "" ||
        String(opt.label).toLowerCase().includes(local.filter.toLowerCase()),
    );

    return html`
      <div
        style=${styleMap({
          display: "flex",
          flexDirection: "column",
          gap: "8px",
          margin: LEAF_MARGIN,
          width: "100%",
        })}
      >
        ${
          props.label
            ? html`<strong style="font-size: 14px;">${props.label}</strong>`
            : nothing
        }
        ${
          props.filterable
            ? html`<input
              type="text"
              placeholder="Filter options..."
              .value=${local.filter}
              @input=${(e: Event) => {
                local.filter = (e.target as HTMLInputElement).value;
                requestUpdate();
              }}
              style=${styleMap({
                padding: "4px 8px",
                border: STANDARD_BORDER,
                borderRadius: STANDARD_RADIUS,
              })}
            />`
            : nothing
        }
        <div
          style=${styleMap({
            display: "flex",
            flexDirection: props.displayStyle === "chips" ? "row" : "column",
            flexWrap: props.displayStyle === "chips" ? "wrap" : "nowrap",
            gap: "8px",
          })}
        >
          ${options.map((opt: any) => {
            const isSelected = values.includes(opt.value);
            if (props.displayStyle === "chips") {
              return html`
                <button
                  type="button"
                  aria-pressed=${isSelected ? "true" : "false"}
                  @click=${() => onToggle(opt.value)}
                  style=${styleMap({
                    padding: "4px 12px",
                    borderRadius: "16px",
                    border: isSelected
                      ? "1px solid var(--a2ui-primary-color, #007bff)"
                      : STANDARD_BORDER,
                    backgroundColor: isSelected
                      ? "var(--a2ui-primary-color, #007bff)"
                      : "#fff",
                    color: isSelected ? "#fff" : "inherit",
                    cursor: "pointer",
                    fontSize: "12px",
                  })}
                >
                  ${opt.label}
                </button>
              `;
            }
            return html`
              <label
                style="display: flex; align-items: center; gap: 8px; cursor: pointer;"
              >
                <input
                  type=${isMutuallyExclusive ? "radio" : "checkbox"}
                  .checked=${isSelected}
                  name=${
                    isMutuallyExclusive
                      ? `choice-${context.componentModel.id}`
                      : ""
                  }
                  @change=${() => onToggle(opt.value)}
                />
                <span style="font-size: 14px;">${opt.label}</span>
              </label>
            `;
          })}
        </div>
      </div>
    `;
  },
  () => ({ filter: "" }),
);
