// packages/angular/src/a2ui/lib/basic/list.ts
import { Component, computed, input } from "@angular/core";
import type { ListApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIChild } from "../child";
import { mapAlign, type BasicProps } from "./shared";

@Component({
  selector: "copilot-a2ui-list",
  imports: [CopilotA2UIChild],
  template: `
    <div
      class="list"
      [class.horizontal]="horizontal()"
      [style.align-items]="mapAlign(props().align)"
    >
      @for (child of props().children; track $index) {
        <copilot-a2ui-child [child]="child" />
      }
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .list {
      display: flex;
      flex-direction: column;
      overflow-x: hidden;
      overflow-y: auto;
      width: 100%;
      margin: 0;
      padding: 0;
    }
    .horizontal {
      flex-direction: row;
      overflow-x: auto;
      overflow-y: hidden;
    }
  `,
})
export class CopilotA2UIList {
  readonly props = input.required<BasicProps<typeof ListApi>>();
  protected readonly mapAlign = mapAlign;
  protected readonly horizontal = computed(
    () => this.props().direction === "horizontal",
  );
}

// packages/a2ui-renderer/src/web-components/catalog/basic/list.ts
import { html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { ListApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { renderChildList } from "../children";
import { mapAlign } from "./utils";

export const List = createLitComponent(ListApi, ({ props, buildChild }) => {
  const isHorizontal = props.direction === "horizontal";
  return html`
    <div
      style=${styleMap({
        display: "flex",
        flexDirection: isHorizontal ? "row" : "column",
        alignItems: mapAlign(props.align),
        overflowX: isHorizontal ? "auto" : "hidden",
        overflowY: isHorizontal ? "hidden" : "auto",
        width: "100%",
        margin: "0",
        padding: "0",
      })}
    >
      ${renderChildList(props.children, buildChild)}
    </div>
  `;
});
