// packages/angular/src/a2ui/lib/basic/row.ts
import { Component, input } from "@angular/core";
import type { RowApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIChild } from "../child";
import { mapAlign, mapJustify, type BasicProps } from "./shared";

@Component({
  selector: "copilot-a2ui-row",
  imports: [CopilotA2UIChild],
  template: `
    <div
      class="row"
      [style.justify-content]="mapJustify(props().justify)"
      [style.align-items]="mapAlign(props().align)"
    >
      @for (child of props().children; track $index) {
        <copilot-a2ui-child [child]="child" />
      }
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .row {
      display: flex;
      flex-direction: row;
      width: 100%;
      margin: 0;
      padding: 0;
    }
  `,
})
export class CopilotA2UIRow {
  readonly props = input.required<BasicProps<typeof RowApi>>();
  protected readonly mapJustify = mapJustify;
  protected readonly mapAlign = mapAlign;
}

// packages/a2ui-renderer/src/web-components/catalog/basic/row.ts
import { html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { RowApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { renderChildList } from "../children";
import { mapAlign, mapJustify } from "./utils";

export const Row = createLitComponent(
  RowApi,
  ({ props, buildChild }) => html`
  <div
    style=${styleMap({
      display: "flex",
      flexDirection: "row",
      justifyContent: mapJustify(props.justify),
      alignItems: mapAlign(props.align),
      width: "100%",
      margin: "0",
      padding: "0",
    })}
  >
    ${renderChildList(props.children, buildChild)}
  </div>
`,
);
