// packages/angular/src/a2ui/lib/basic/slider.ts
import { Component } from "@angular/core";
import { SliderApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIBasicComponent } from "./basic-component";
import { uniqueId } from "./shared";

@Component({
  selector: "copilot-a2ui-slider",
  template: `
    <div class="header">
      @if (props().label) {
        <label class="label" [for]="inputId">{{ props().label }}</label>
      }
      <span class="value">{{ props().value }}</span>
    </div>
    <input
      type="range"
      class="range"
      [id]="inputId"
      [min]="props().min ?? 0"
      [max]="props().max"
      [value]="props().value ?? 0"
      (input)="update($event)"
    />
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      gap: calc(var(--a2ui-spacing-m, 8px) / 2);
      width: 100%;
    }
    .header {
      display: flex;
      justify-content: space-between;
    }
    .label {
      font-size: var(--a2ui-font-size-s, 14px);
      font-weight: bold;
    }
    .value {
      font-size: var(--a2ui-font-size-xs, 12px);
      color: var(--a2ui-color-muted, #666);
    }
    .range {
      width: 100%;
      cursor: pointer;
    }
  `,
})
export class CopilotA2UISlider extends CopilotA2UIBasicComponent<
  typeof SliderApi
> {
  protected readonly inputId = uniqueId("slider");

  protected update(event: Event): void {
    this.props().setValue(Number((event.target as HTMLInputElement).value));
  }
}

// packages/a2ui-renderer/src/web-components/catalog/basic/slider.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { SliderApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { uniqueId } from "./ids";
import { LEAF_MARGIN } from "./utils";

export const Slider = createLitComponent(SliderApi, ({ props }) => {
  const inputId = uniqueId("slider");
  return html`
    <div
      style=${styleMap({
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        margin: LEAF_MARGIN,
        width: "100%",
      })}
    >
      <div style="display: flex; justify-content: space-between;">
        ${
          props.label
            ? html`<label
              for=${inputId}
              style="font-size: 14px; font-weight: bold;"
              >${props.label}</label
            >`
            : nothing
        }
        <span style="font-size: 12px; color: #666;">${props.value}</span>
      </div>
      <input
        id=${inputId}
        type="range"
        min=${props.min ?? 0}
        max=${props.max}
        .value=${String(props.value ?? 0)}
        @input=${(e: Event) =>
          props.setValue(Number((e.target as HTMLInputElement).value))}
        style="width: 100%; cursor: pointer;"
      />
    </div>
  `;
});
