// packages/angular/src/a2ui/lib/basic/tabs.ts
import { Component, computed, signal } from "@angular/core";
import { TabsApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { CopilotA2UIChild } from "../child";
import { CopilotA2UIBasicComponent } from "./basic-component";

@Component({
  selector: "copilot-a2ui-tabs",
  imports: [CopilotA2UIChild],
  template: `
    <div class="tab-list" role="tablist">
      @for (tab of tabs(); track $index) {
        <button
          type="button"
          role="tab"
          class="tab"
          [class.active]="selectedIndex() === $index"
          [attr.aria-selected]="selectedIndex() === $index"
          (click)="selectedIndex.set($index)"
        >
          {{ tab.title }}
        </button>
      }
    </div>
    <div class="tab-panel" role="tabpanel">
      @if (activeTab(); as tab) {
        <copilot-a2ui-child [child]="tab.child" />
      }
    </div>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      width: 100%;
    }
    .tab-list {
      display: flex;
      margin-bottom: var(--a2ui-spacing-m, 8px);
      border-bottom: 1px solid var(--a2ui-color-border, #ccc);
    }
    .tab {
      padding: var(--a2ui-button-padding, 8px 16px);
      border: none;
      background: none;
      color: inherit;
      font-weight: normal;
      cursor: pointer;
    }
    .active {
      border-bottom: 2px solid
        var(--a2ui-color-primary, var(--a2ui-primary-color, #007bff));
      color: var(--a2ui-color-primary, var(--a2ui-primary-color, #007bff));
      font-weight: bold;
    }
    .tab-panel {
      flex: 1;
    }
  `,
})
export class CopilotA2UITabs extends CopilotA2UIBasicComponent<typeof TabsApi> {
  protected readonly selectedIndex = signal(0);
  protected readonly tabs = computed(() => this.props().tabs ?? []);
  protected readonly activeTab = computed(
    () => this.tabs()[this.selectedIndex()] ?? this.tabs()[0],
  );
}

// packages/a2ui-renderer/src/web-components/catalog/basic/tabs.ts
import { html, nothing } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { TabsApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { createLitComponent } from "../../adapter";
import { LEAF_MARGIN } from "./utils";

export const Tabs = createLitComponent(
  TabsApi,
  ({ props, buildChild, state, requestUpdate }) => {
    const local = state as { selectedIndex: number };
    const tabs = props.tabs || [];
    const activeTab = tabs[local.selectedIndex] ?? tabs[0];
    return html`
      <div
        style=${styleMap({
          display: "flex",
          flexDirection: "column",
          width: "100%",
          margin: LEAF_MARGIN,
        })}
      >
        <div
          style=${styleMap({
            display: "flex",
            borderBottom: "1px solid #ccc",
            marginBottom: "8px",
          })}
        >
          ${tabs.map(
            (tab: any, i: number) => html`
              <button
                type="button"
                @click=${() => {
                  local.selectedIndex = i;
                  requestUpdate();
                }}
                style=${styleMap({
                  padding: "8px 16px",
                  border: "none",
                  background: "none",
                  borderBottom:
                    local.selectedIndex === i
                      ? "2px solid var(--a2ui-primary-color, #007bff)"
                      : "none",
                  fontWeight: local.selectedIndex === i ? "bold" : "normal",
                  cursor: "pointer",
                  color:
                    local.selectedIndex === i
                      ? "var(--a2ui-primary-color, #007bff)"
                      : "inherit",
                })}
              >
                ${tab.title}
              </button>
            `,
          )}
        </div>
        <div style="flex: 1;">
          ${activeTab ? buildChild(activeTab.child) : nothing}
        </div>
      </div>
    `;
  },
  () => ({ selectedIndex: 0 }),
);
