// examples/v2/react/demo/src/app/a2ui-demo/page.tsx
"use client";

import { CopilotChat, CopilotKitProvider } from "@copilotkit/react-core/v2";

export const dynamic = "force-dynamic";

export default function A2UIDemoPage() {
  return (
    <CopilotKitProvider runtimeUrl="/api/copilotkit" a2ui={{}} showDevConsole="auto">
      <div style={{ height: "100vh", margin: 0, padding: 0, overflow: "hidden" }}>
        <CopilotChat agentId="demo-button" threadId="a2ui-demo-thread" />
      </div>
    </CopilotKitProvider>
  );
}

// examples/v2/vue/demo/pages/a2ui-demo.vue
<script setup lang="ts">
import { CopilotChat, CopilotKitProvider } from "@copilotkit/vue/v2";
</script>

<template>
  <CopilotKitProvider runtime-url="/api/copilotkit" :a2ui="{}">
    <div style="height: 100vh; margin: 0; padding: 0; overflow: hidden">
      <CopilotChat agent-id="demo-button" thread-id="a2ui-demo-thread" />
    </div>
  </CopilotKitProvider>
</template>
