// packages/a2ui-renderer/src/react-renderer/a2ui-react/catalog/basic/components/Image.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {ImageApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {getBaseLeafStyle} from '../utils';

export const Image = createReactComponent(ImageApi, ({props}) => {
  const mapFit = (fit?: string): React.CSSProperties['objectFit'] => {
    if (fit === 'scaleDown') return 'scale-down';
    return (fit as React.CSSProperties['objectFit']) || 'fill';
  };

  const style: React.CSSProperties = {
    ...getBaseLeafStyle(),
    objectFit: mapFit(props.fit),
    width: '100%',
    height: 'auto',
    display: 'block',
  };

  if (props.variant === 'icon') {
    style.width = '24px';
    style.height = '24px';
  } else if (props.variant === 'avatar') {
    style.width = '40px';
    style.height = '40px';
    style.borderRadius = '50%';
  } else if (props.variant === 'smallFeature') {
    style.maxWidth = '100px';
  } else if (props.variant === 'largeFeature') {
    style.maxHeight = '400px';
  } else if (props.variant === 'header') {
    style.height = '200px';
    style.objectFit = 'cover';
  }

  return <img src={props.url} alt={props.description || ''} style={style} />;
});

// examples/experiments/a2ui-private/original_a2ui_source/samples/client/angular/projects/lib/src/lib/catalog/image.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import * as v0_8 from '@a2ui/web-lib/0.8';

@Component({
  selector: 'a2ui-image',
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
      overflow: auto;
    }

    img {
      display: block;
      width: 100%;
      height: 100%;
      box-sizing: border-box;
    }
  `,
  template: `
    @let resolvedUrl = this.resolvedUrl();

    @if (resolvedUrl) {
      <section [class]="classes()" [style]="theme.additionalStyles?.Image">
        <img [src]="resolvedUrl" />
      </section>
    }
  `,
})
export class Image extends DynamicComponent {
  readonly url = input.required<v0_8.Primitives.StringValue | null>();
  readonly usageHint = input.required<v0_8.Types.ResolvedImage['usageHint'] | null>();

  protected readonly resolvedUrl = computed(() => this.resolvePrimitive(this.url()));

  protected classes = computed(() => {
    const usageHint = this.usageHint();

    return v0_8.Styles.merge(
      this.theme.components.Image.all,
      usageHint ? this.theme.components.Image[usageHint] : {},
    );
  });
}
