// packages/v2/vue/src/components/chat/CopilotChatSuggestionView.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import type { Suggestion } from "@copilotkitnext/core";
import CopilotChatSuggestionPill from "./CopilotChatSuggestionPill.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    suggestions: Suggestion[];
    loadingIndexes?: ReadonlyArray<number>;
  }>(),
  {
    loadingIndexes: () => [],
  },
);

defineSlots<{
  suggestion?: (props: {
    suggestion: Suggestion;
    index: number;
    isLoading: boolean;
    onSelect: () => void;
  }) => unknown;
}>();

const emit = defineEmits<{
  "select-suggestion": [suggestion: Suggestion, index: number];
}>();

const attrs = useAttrs();
const loadingSet = computed(() => new Set(props.loadingIndexes));
const containerClass = computed(() => [
  "flex flex-wrap items-center gap-1.5 pl-0 pr-4 pointer-events-none sm:gap-2 sm:px-0",
  attrs.class,
]);
const containerAttrs = computed(() => {
  const { class: _className, ...rest } = attrs;
  return rest;
});

function isLoading(index: number, suggestion: Suggestion) {
  return loadingSet.value.has(index) || suggestion.isLoading === true;
}

function handleSelectSuggestion(suggestion: Suggestion, index: number) {
  emit("select-suggestion", suggestion, index);
}
</script>

<template>
  <div
    data-testid="copilot-chat-suggestion-view"
    :class="containerClass"
    v-bind="containerAttrs"
  >
    <template v-for="(suggestion, index) in suggestions" :key="`${suggestion.title}-${index}`">
      <slot
        name="suggestion"
        :suggestion="suggestion"
        :index="index"
        :is-loading="isLoading(index, suggestion)"
        :on-select="() => handleSelectSuggestion(suggestion, index)"
      >
        <CopilotChatSuggestionPill
          :is-loading="isLoading(index, suggestion)"
          type="button"
          @click="handleSelectSuggestion(suggestion, index)"
        >
          {{ suggestion.title }}
        </CopilotChatSuggestionPill>
      </slot>
    </template>
  </div>
</template>

// packages/v2/react/src/components/chat/CopilotChatSuggestionView.tsx
import React from "react";
import { Suggestion } from "@copilotkitnext/core";
import { renderSlot, WithSlots } from "@/lib/slots";
import { cn } from "@/lib/utils";
import CopilotChatSuggestionPill, {
  CopilotChatSuggestionPillProps,
} from "./CopilotChatSuggestionPill";

const DefaultContainer = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(function DefaultContainer({ className, ...props }, ref) {
  return (
    <div
      ref={ref}
      data-copilotkit
      data-testid="copilot-suggestions"
      className={cn(
        "cpk:flex cpk:flex-wrap cpk:items-center cpk:gap-1.5 cpk:sm:gap-2 cpk:pl-0 cpk:pr-4 cpk:sm:px-0 cpk:pointer-events-none",
        className,
      )}
      {...props}
    />
  );
});

export type CopilotChatSuggestionViewProps = WithSlots<
  {
    container: typeof DefaultContainer;
    suggestion: typeof CopilotChatSuggestionPill;
  },
  {
    suggestions: Suggestion[];
    onSelectSuggestion?: (suggestion: Suggestion, index: number) => void;
    loadingIndexes?: ReadonlyArray<number>;
  } & React.HTMLAttributes<HTMLDivElement>
>;

export const CopilotChatSuggestionView = React.forwardRef<
  HTMLDivElement,
  CopilotChatSuggestionViewProps
>(function CopilotChatSuggestionView(
  {
    suggestions,
    onSelectSuggestion,
    loadingIndexes,
    container,
    suggestion: suggestionSlot,
    className,
    children,
    ...restProps
  },
  ref,
) {
  const loadingSet = React.useMemo(() => {
    if (!loadingIndexes || loadingIndexes.length === 0) {
      return new Set<number>();
    }
    return new Set(loadingIndexes);
  }, [loadingIndexes]);

  const ContainerElement = renderSlot(container, DefaultContainer, {
    ref,
    className,
    ...restProps,
  });

  const suggestionElements = suggestions.map((suggestion, index) => {
    const isLoading = loadingSet.has(index) || suggestion.isLoading === true;
    const pill = renderSlot<
      typeof CopilotChatSuggestionPill,
      CopilotChatSuggestionPillProps
    >(suggestionSlot, CopilotChatSuggestionPill, {
      children: suggestion.title,
      isLoading,
      type: "button",
      onClick: () => onSelectSuggestion?.(suggestion, index),
    });

    return React.cloneElement(pill, {
      key: `${suggestion.title}-${index}`,
    });
  });

  const boundContainer = React.cloneElement(
    ContainerElement,
    undefined,
    suggestionElements,
  );

  if (typeof children === "function") {
    const sampleSuggestion = renderSlot<
      typeof CopilotChatSuggestionPill,
      CopilotChatSuggestionPillProps
    >(suggestionSlot, CopilotChatSuggestionPill, {
      children: suggestions[0]?.title ?? "",
      isLoading:
        suggestions.length > 0
          ? loadingSet.has(0) || suggestions[0]?.isLoading === true
          : false,
      type: "button",
    });

    return (
      <div data-copilotkit style={{ display: "contents" }}>
        {children({
          container: boundContainer,
          suggestion: sampleSuggestion,
          suggestions,
          onSelectSuggestion,
          loadingIndexes,
          className,
          ...restProps,
        })}
      </div>
    );
  }

  if (children) {
    return (
      <div data-copilotkit style={{ display: "contents" }}>
        {boundContainer}
        {children}
      </div>
    );
  }

  return boundContainer;
});

CopilotChatSuggestionView.displayName = "CopilotChatSuggestionView";

export default CopilotChatSuggestionView;
