// examples/integrations/adk-angular/src/app/proverbs.ts
import { Component, computed, effect } from "@angular/core";
import { injectAgentStore } from "@copilotkit/angular";
import { AGENT_ID } from "./app.config";
import type { AgentState } from "./agent-state";

@Component({
  selector: "app-proverbs",
  standalone: true,
  template: `
    <div class="card">
      <h1>Proverbs</h1>
      <p class="subtitle">
        This is a demonstrative page, but it could be anything you want! 🪁
      </p>
      <hr />
      <div class="list">
        @for (proverb of proverbs(); track $index) {
          <div class="proverb">
            <p>{{ proverb }}</p>
            <button (click)="remove($index)" aria-label="Remove proverb">✕</button>
          </div>
        }
      </div>
      @if (proverbs().length === 0) {
        <p class="empty">No proverbs yet. Ask the assistant to add some!</p>
      }
    </div>
  `,
  styles: [
    `
      .card {
        background: rgba(255, 255, 255, 0.2);
        backdrop-filter: blur(12px);
        padding: 2rem;
        border-radius: 1rem;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.15);
        max-width: 42rem;
        width: 100%;
        color: #fff;
      }
      h1 {
        font-size: 2.25rem;
        font-weight: 700;
        text-align: center;
        margin: 0 0 0.5rem;
      }
      .subtitle {
        text-align: center;
        font-style: italic;
        opacity: 0.85;
        margin: 0 0 1.5rem;
      }
      hr {
        border: none;
        border-top: 1px solid rgba(255, 255, 255, 0.2);
        margin: 1.5rem 0;
      }
      .list {
        display: flex;
        flex-direction: column;
        gap: 0.75rem;
      }
      .proverb {
        position: relative;
        background: rgba(255, 255, 255, 0.15);
        padding: 1rem;
        border-radius: 0.75rem;
      }
      .proverb p {
        margin: 0;
        padding-right: 2rem;
      }
      .proverb button {
        position: absolute;
        right: 0.75rem;
        top: 0.75rem;
        height: 1.5rem;
        width: 1.5rem;
        border: none;
        border-radius: 9999px;
        background: #ef4444;
        color: #fff;
        cursor: pointer;
      }
      .empty {
        text-align: center;
        font-style: italic;
        opacity: 0.8;
        margin: 2rem 0;
      }
    `,
  ],
})
export class Proverbs {
  readonly #store = injectAgentStore(AGENT_ID);

  protected readonly proverbs = computed<string[]>(
    () => (this.#store().state() as AgentState | undefined)?.proverbs ?? [],
  );

  constructor() {
    // Seed one proverb once, when the agent first reports empty/undefined state
    // (mirrors the React page.tsx useEffect seed).
    let seeded = false;
    effect(() => {
      const state = this.#store().state() as AgentState | undefined;
      if (!seeded && state?.proverbs === undefined) {
        seeded = true;
        this.#store().agent.setState({
          proverbs: [
            "CopilotKit may be new, but it's the best thing since sliced bread.",
          ],
        } satisfies AgentState);
      }
    });
  }

  protected remove(index: number): void {
    const next = this.proverbs().filter((_, i) => i !== index);
    this.#store().agent.setState({ proverbs: next } satisfies AgentState);
  }
}

// examples/integrations/mastra/src/components/proverbs.tsx
import { AgentState } from "@/lib/types";

export interface ProverbsCardProps {
  state: AgentState;
  setState: (state: AgentState) => void;
}

export function ProverbsCard({ state, setState }: ProverbsCardProps) {
  return (
    <div className="bg-white/20 backdrop-blur-md p-8 rounded-2xl shadow-xl max-w-2xl w-full">
      <h1 className="text-4xl font-bold text-white mb-2 text-center">
        Proverbs
      </h1>
      <p className="text-gray-200 text-center italic mb-6">
        This is a demonstrative page, but it could be anything you want! 🪁
      </p>
      <hr className="border-white/20 my-6" />
      <div className="flex flex-col gap-3">
        {state.proverbs?.map((proverb, index) => (
          <div
            key={index}
            className="bg-white/15 p-4 rounded-xl text-white relative group hover:bg-white/20 transition-all"
          >
            <p className="pr-8">{proverb}</p>
            <button
              onClick={() =>
                setState({
                  ...state,
                  proverbs: state.proverbs?.filter((_, i) => i !== index),
                })
              }
              className="absolute right-3 top-3 opacity-0 group-hover:opacity-100 transition-opacity 
                bg-red-500 hover:bg-red-600 text-white rounded-full h-6 w-6 flex items-center justify-center"
            >
              ✕
            </button>
          </div>
        ))}
      </div>
      {state.proverbs?.length === 0 && (
        <p className="text-center text-white/80 italic my-8">
          No proverbs yet. Ask the assistant to add some!
        </p>
      )}
    </div>
  );
}
