// packages/vue/src/v2/components/chat/CopilotThreadsDrawer.vue
<script setup lang="ts">
import { computed, onMounted, onScopeDispose, ref, watchEffect } from "vue";
// NOTE: the `<copilotkit-threads-drawer>` element is a Lit custom element whose
// module evaluates `class ... extends HTMLElement` at import time, which throws
// under SSR (Node has no DOM). It is therefore imported LAZILY (client-only,
// inside onMounted) rather than statically, so that importing `@copilotkit/vue`
// stays SSR-safe for every consumer (e.g. Nuxt). Only the erased `import type`
// below is kept at module scope.
import type {
  CopilotKitThreadsDrawer as CopilotKitThreadsDrawerElement,
  DrawerThread,
  ThreadSelectedDetail,
  ArchiveDetail,
  UnarchiveDetail,
  DeleteDetail,
  RetryDetail,
  OpenChangeDetail,
} from "@copilotkit/web-components/threads-drawer";
// TODO(ENT-1051): import `CollapseChangeDetail` from
// "@copilotkit/web-components/threads-drawer" once the parallel element PR that
// adds the collapse feature (property `collapsible` + event `collapse-change`)
// lands and is published; declared locally here because the built element types
// in this worktree predate it.
type CollapseChangeDetail = { collapsed: boolean };
import { DEFAULT_AGENT_ID } from "@copilotkit/shared";
import { useThreads } from "../../hooks/use-threads";
import type { Thread } from "../../hooks/use-threads";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import { useLicenseContext } from "../../providers/useLicenseContext";

const props = withDefaults(
  defineProps<{
    agentId?: string;
    onThreadSelect?: (threadId: string) => void;
    onNewThread?: () => void;
    onLicensed?: () => void;
    licenseUrl?: string;
    label?: string;
    /**
     * Heading rendered above the thread list (element attribute
     * `recent-label`). Defaults to the element's own `"Recent Conversations"`
     * when omitted.
     */
    recentLabel?: string;
    /**
     * Whether the drawer offers a collapse toggle. Bound to the element's
     * `collapsible` PROPERTY. When `false`, the drawer has no collapse toggle
     * and is always expanded. Defaults to `true`.
     *
     * NOTE: this MUST carry an explicit `true` default below. Vue coerces an
     * omitted `Boolean` prop to `false` (not `undefined`), so without the
     * default the `!== undefined` guard would always fire and force the element
     * to `collapsible=false` — silently disabling collapse. Defaulting to `true`
     * restores the element's own default when the prop is omitted.
     */
    collapsible?: boolean;
    limit?: number;
    dataTestId?: string;
  }>(),
  { dataTestId: "copilot-threads-drawer", collapsible: true },
);

const emit = defineEmits<{
  /**
   * Emitted when the drawer's collapsed state changes (mirrors the element's
   * `collapse-change` event), carrying the new collapsed state.
   */
  "collapse-change": [collapsed: boolean];
}>();

const config = useCopilotChatConfiguration();
const license = useLicenseContext();

const licensed = computed(() => {
  const status = license.value.status;
  // `unknown` is an unrecovered retryable entitlement lookup, not a settled
  // negative: fetch the list and let the threads endpoint decide.
  if (status === "unknown") return true;
  const present = status === "valid" || status === "expiring";
  return present && license.value.checkFeature("threads");
});
const licensePending = computed(() => license.value.status === null);

const resolvedAgentId = computed(
  () => props.agentId ?? config.value?.agentId ?? DEFAULT_AGENT_ID,
);
const activeThreadId = computed(() => config.value?.threadId ?? null);
// Hosted inside a chat modal (`threads-drawer` on the popup/sidebar): render
// as an overlay panel over the modal instead of an in-flow sidebar.
const overlay = computed(() => config.value?.ɵdrawerOverlay === true);

// Provider-less fallback: without a surrounding chat configuration there is
// no shared open-state to bind to, so the wrapper keeps its own local
// open-state. It starts CLOSED — matching the provider's own default — so a
// bare `<CopilotThreadsDrawer>` does not render stuck-open and the element's
// open-change events still toggle it.
const localDrawerOpen = ref(false);
const drawerOpen = computed(() =>
  config.value ? config.value.drawerOpen : localDrawerOpen.value,
);
function setDrawerOpen(open: boolean) {
  if (config.value) config.value.setDrawerOpen?.(open);
  else localDrawerOpen.value = open;
}

const threadsApi = useThreads({
  agentId: resolvedAgentId,
  includeArchived: true,
  enabled: licensed,
  limit: () => props.limit,
});

function toDrawerThread(t: Thread): DrawerThread {
  return {
    id: t.id,
    name: t.name,
    archived: t.archived,
    createdAt: t.createdAt,
    updatedAt: t.updatedAt,
    ...(t.lastRunAt !== undefined ? { lastRunAt: t.lastRunAt } : {}),
  };
}
const drawerThreads = computed(() =>
  threadsApi.threads.value.map(toDrawerThread),
);

// Client-only element registration (SSR-safe). The element module is imported
// lazily here (never at module scope — see the import note above) so SSR never
// evaluates its `extends HTMLElement`. `elementTag` holds the resolved custom-
// element tag and `mounted` gates the render; both are set only after the
// dynamic import resolves on the client.
const mounted = ref(false);
const elementTag = ref<string | null>(null);
const elRef = ref<CopilotKitThreadsDrawerElement | null>(null);
onMounted(async () => {
  const mod = await import("@copilotkit/web-components/threads-drawer");
  mod.defineCopilotKitThreadsDrawer();
  elementTag.value = mod.COPILOTKIT_THREADS_DRAWER_TAG;
  mounted.value = true;
});

// Imperatively push object/array/boolean PROPERTIES (v-bind on a custom element
// would set string attributes for these). Re-runs whenever the element or any
// reactive value read in the body changes (auto-tracked by watchEffect).
watchEffect(
  () => {
    const el = elRef.value;
    if (!el) return;
    el.threads = drawerThreads.value;
    el.loading = threadsApi.isLoading.value || licensePending.value;
    el.error = threadsApi.listError.value?.message ?? null;
    el.activeThreadId = activeThreadId.value;
    el.licensed = licensed.value || licensePending.value;
    el.hasMore = threadsApi.hasMoreThreads.value;
    el.fetchingMore = threadsApi.isFetchingMoreThreads.value;
    // Dedicated fetch-more error channel: drives the element's inline
    // "couldn't load more — retry" panel without disturbing the loaded list.
    el.fetchMoreError = threadsApi.fetchMoreError.value?.message ?? null;
    el.open = drawerOpen.value;
    (el as CopilotKitThreadsDrawerElement & { overlay: boolean }).overlay =
      overlay.value;
    if (props.label !== undefined) el.label = props.label;
    if (props.licenseUrl !== undefined) el.licenseUrl = props.licenseUrl;
    // `collapsible` is a default-true boolean PROPERTY (like `licensed`); leave
    // the element's own default in place when the prop is omitted.
    if (props.collapsible !== undefined) {
      // TODO(ENT-1051): drop the intersection cast once the published element
      // type declares `collapsible` (see the local CollapseChangeDetail note).
      (
        el as CopilotKitThreadsDrawerElement & { collapsible: boolean }
      ).collapsible = props.collapsible;
    }
  },
  { flush: "post" },
);

// Announce drawer presence so the mobile header launcher renders. Register
// synchronously in setup (React parity: a mount-time effect) and de-register
// on scope dispose. Not gated on `mounted`: presence is independent of the
// client-only element registration.
const unregisterDrawer = config.value?.registerDrawer?.();
if (unregisterDrawer) onScopeDispose(unregisterDrawer);

// --- Outbound event handlers ------------------------------------------------
/** The chat input textarea's documented `data-testid`. */
const CHAT_INPUT_TESTID = "copilot-chat-input-textarea";
/** The chat view container's documented `data-testid`. */
const CHAT_CONTAINER_TESTID = "copilot-chat-view";
/** The chat modals (popup / sidebar) that can host the drawer as an overlay. */
const CHAT_MODAL_SELECTOR = "[data-copilot-popup], [data-copilot-sidebar]";
/** The modal header's thread-list launcher `data-testid` (focus-return target). */
const DRAWER_LAUNCHER_TESTID = "drawer-launcher";

/**
 * Returns the chat input element for focus-return after a thread is selected.
 *
 * Best-effort and SCOPED: walks up from the drawer's custom element looking
 * for an ancestor that contains a chat-view container
 * (`data-testid="copilot-chat-view"`), then returns the chat input within
 * that subtree. This avoids focusing the wrong composer on a page hosting
 * more than one chat (multi-chat dashboards), where a document-global lookup
 * would grab whichever input appears first in DOM order rather than the one
 * this drawer drives.
 *
 * Falls back to a document-global lookup when no scoping ancestor is found
 * (e.g. the drawer and chat share no common container, or headless usage).
 */
function findChatInput(origin: Element | null): HTMLElement | null {
  if (typeof document === "undefined") return null;
  const container = origin?.closest?.(
    `[data-testid="${CHAT_CONTAINER_TESTID}"]`,
  );
  if (container) {
    const scoped = container.querySelector<HTMLElement>(
      `[data-testid="${CHAT_INPUT_TESTID}"]`,
    );
    if (scoped) return scoped;
  }
  // A drawer hosted inside a chat modal sits beside (not inside) the modal's
  // chat view: scope the lookup to that modal.
  const modal = origin?.closest?.(CHAT_MODAL_SELECTOR);
  if (modal) {
    const scoped = modal.querySelector<HTMLElement>(
      `[data-testid="${CHAT_INPUT_TESTID}"]`,
    );
    if (scoped) return scoped;
  }
  return document.querySelector<HTMLElement>(
    `[data-testid="${CHAT_INPUT_TESTID}"]`,
  );
}

/**
 * When an overlay drawer closes while focus is still inside it (Escape, the
 * scrim, its close button), hands focus back to the launcher in the header of
 * the modal hosting it. A close that follows a thread pick has already moved
 * focus to the chat input, so it is left alone.
 */
function returnFocusToLauncher(drawer: HTMLElement | null): void {
  if (!drawer || typeof document === "undefined") return;
  const active = document.activeElement;
  // Focus inside the shadow root reports the host as `activeElement`.
  if (active !== drawer && !drawer.contains(active)) return;
  drawer
    .closest(CHAT_MODAL_SELECTOR)
    ?.querySelector<HTMLElement>(`[data-testid="${DRAWER_LAUNCHER_TESTID}"]`)
    ?.focus({ preventScroll: true });
}

function focusChatInput() {
  findChatInput(elRef.value)?.focus();
}

function onThreadSelected(event: Event) {
  const { threadId } = (event as CustomEvent<ThreadSelectedDetail>).detail;
  if (props.onThreadSelect) props.onThreadSelect(threadId);
  else config.value?.setActiveThreadId?.(threadId, { explicit: true });
  focusChatInput();
}
function handleNewThread() {
  threadsApi.startNewThread();
  if (props.onNewThread) props.onNewThread();
  else config.value?.startNewThread?.();
  if (overlay.value) {
    // The overlay closes itself on "New Conversation"; land in the composer.
    // Deferred a tick because the reset swaps the chat to its welcome screen,
    // which mounts a fresh input.
    setTimeout(() => findChatInput(elRef.value)?.focus(), 0);
  }
}
function onArchive(event: Event) {
  const { threadId } = (event as CustomEvent<ArchiveDetail>).detail;
  void threadsApi
    .archiveThread(threadId)
    .catch((e) =>
      console.error("CopilotThreadsDrawer: archiveThread failed", e),
    );
}
function onUnarchive(event: Event) {
  const { threadId } = (event as CustomEvent<UnarchiveDetail>).detail;
  void threadsApi
    .unarchiveThread(threadId)
    .catch((e) =>
      console.error("CopilotThreadsDrawer: unarchiveThread failed", e),
    );
}
function onDelete(event: Event) {
  const { threadId } = (event as CustomEvent<DeleteDetail>).detail;
  const wasActive = threadId === activeThreadId.value;
  void threadsApi
    .deleteThread(threadId)
    .then(() => {
      if (wasActive) {
        handleNewThread();
      }
    })
    .catch((e) =>
      console.error("CopilotThreadsDrawer: deleteThread failed", e),
    );
}
function onFilterChange() {
  threadsApi.refetchThreads();
}
function onCollapseChange(event: Event) {
  const { collapsed } = (event as CustomEvent<CollapseChangeDetail>).detail;
  emit("collapse-change", collapsed);
}
function onRetry(event: Event) {
  const { scope } = (event as CustomEvent<RetryDetail>).detail;
  if (scope === "fetch-more") threadsApi.fetchMoreThreads();
  else threadsApi.refetchThreads();
}
function onLoadMore() {
  threadsApi.fetchMoreThreads();
}
function onOpenChange(event: Event) {
  const { open } = (event as CustomEvent<OpenChangeDetail>).detail;
  setDrawerOpen(open);
  if (!open && overlay.value) returnFocusToLauncher(elRef.value);
}
function handleLicensed() {
  props.onLicensed?.();
}

defineSlots<{
  default(): unknown;
  /**
   * Optional per-row content. When provided, this slot is rendered as
   * light-DOM children with `slot="row:{id}"` for EVERY thread in the list,
   * so the element projects it in place of the default row for all rows.
   *
   * Unlike React's `renderRow` (which returns `ReactNode | null` and can
   * fall back to the element's built-in row on a per-thread basis by
   * returning `null`), Vue's scoped slot is all-or-nothing: there is no
   * per-row escape hatch back to the element default once the slot is
   * defined. This is an intentional Vue-idiom divergence, not a bug — if a
   * consumer needs per-row fallback, they should replicate the default row
   * markup themselves inside the slot for the threads they don't want to
   * customize.
   */
  row(props: { thread: Thread }): unknown;
}>();
</script>

<template>
  <component
    :is="elementTag"
    v-if="mounted"
    ref="elRef"
    :data-testid="dataTestId"
    :recent-label="recentLabel"
    :overlay="overlay || undefined"
    @thread-selected="onThreadSelected"
    @new-thread="handleNewThread"
    @archive="onArchive"
    @unarchive="onUnarchive"
    @delete="onDelete"
    @filter-change="onFilterChange"
    @collapse-change="onCollapseChange"
    @retry="onRetry"
    @load-more="onLoadMore"
    @open-change="onOpenChange"
    @licensed="handleLicensed"
  >
    <slot />
    <!--
      When the `row` slot is defined, it is projected for EVERY thread (no
      per-row fallback to the element default) — see the JSDoc on the `row`
      slot above for the React `renderRow` comparison.
    -->
    <template v-if="$slots.row">
      <div
        v-for="t in threadsApi.threads.value"
        :key="t.id"
        v-bind="{ slot: `row:${t.id}` }"
      >
        <slot name="row" :thread="t" />
      </div>
    </template>
  </component>
</template>

// packages/react-core/src/v2/components/chat/CopilotThreadsDrawer.tsx
"use client";

import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  defineCopilotKitThreadsDrawer,
  COPILOTKIT_THREADS_DRAWER_TAG,
} from "@copilotkit/web-components/threads-drawer";
import type {
  CopilotKitThreadsDrawer as CopilotKitThreadsDrawerElement,
  DrawerThread,
  ThreadSelectedDetail,
  ArchiveDetail,
  UnarchiveDetail,
  DeleteDetail,
  OpenChangeDetail,
  RetryDetail,
} from "@copilotkit/web-components/threads-drawer";
// TODO(ENT-1051): import `CollapseChangeDetail` from
// "@copilotkit/web-components/threads-drawer" once the parallel element PR that
// adds the collapse feature (property `collapsible` + event `collapse-change`)
// lands and is published; declared locally here because the built element types
// in this worktree predate it.
type CollapseChangeDetail = { collapsed: boolean };
import { DEFAULT_AGENT_ID } from "@copilotkit/shared";
import { useThreads } from "../../hooks/use-threads";
import type { Thread } from "../../hooks/use-threads";
import { useLicenseContext } from "../../providers/CopilotKitProvider";
import { useDefaultAgentId } from "../../context";
import { useCopilotChatConfiguration } from "../../providers/CopilotChatConfigurationProvider";

/**
 * Per-row content render function. Receives a thread and returns the React
 * node to project into the element's `slot="row:{id}"`. Returning `null`
 * (or omitting the prop) falls back to the element's built-in row name.
 */
export type CopilotThreadsDrawerRowRenderer = (
  thread: Thread,
) => React.ReactNode;

/**
 * Props for {@link CopilotThreadsDrawer}.
 *
 * The drawer is a thin controller around the framework-agnostic
 * `<copilotkit-threads-drawer>` custom element. It feeds the element domain data
 * (threads/loading/error from {@link useThreads}, the active thread from the
 * chat configuration) and routes the element's outbound DOM events back into
 * core thread operations and chat-configuration changes.
 */
export interface CopilotThreadsDrawerProps {
  /**
   * The agent whose threads to list and manage. Defaults to the agent of the
   * surrounding chat configuration, or the platform default when none is set.
   */
  agentId?: string;
  /**
   * Optional escape-hatch called when the user picks a thread row. The wrapper
   * additionally focuses the chat input. When omitted, the wrapper drives the
   * surrounding chat configuration directly (`setActiveThreadId`), so a bare
   * `<CopilotThreadsDrawer>` switches the rendered thread with no host wiring. Provide
   * this only to take control of the active thread yourself (e.g. a v1
   * `setThreadId`); when provided it is preferred over the provider.
   */
  onThreadSelect?: (threadId: string) => void;
  /**
   * Optional escape-hatch called when the user starts a new thread (the
   * element's "+ New" button). The wrapper always resets the core thread store
   * to a fresh, non-explicit client-side thread (`startNewThread`). When this
   * is omitted, the wrapper also resets the surrounding chat configuration to a
   * fresh non-explicit thread (`startNewThread`) so the welcome screen shows
   * with no host wiring. Provide this only to clear your own active thread;
   * when provided it is preferred over the provider.
   */
  onNewThread?: () => void;
  /** Called when the Upgrade CTA is clicked. */
  onLicensed?: () => void;
  /**
   * Destination the locked view's Upgrade CTA opens in a new tab. Defaults to
   * the element's built-in CopilotKit Intelligence docs URL when omitted. Set
   * to an empty string to suppress the default navigation and handle the click
   * yourself via `onLicensed`.
   */
  licenseUrl?: string;
  /**
   * Optional per-row content. Rendered as light-DOM children with
   * `slot="row:{id}"` so the element projects them in place of the default
   * row name. Return `null` for a given row to keep the element's default.
   */
  renderRow?: CopilotThreadsDrawerRowRenderer;
  /**
   * Accessible + default-header label for the drawer region. Sets the custom
   * element's `aria-label` and the default header text (shown when no
   * `slot="header"` content is projected). Defaults to the element's built-in
   * `"Threads"` when omitted.
   */
  label?: string;
  /**
   * Heading for the "Recent Conversations" section above the thread list. Sets
   * the custom element's `recent-label` attribute. Defaults to the element's
   * built-in `"Recent Conversations"` when omitted.
   */
  recentLabel?: string;
  /**
   * Whether the drawer offers a collapse toggle. Sets the custom element's
   * `collapsible` PROPERTY. When `false`, the drawer has no collapse toggle and
   * is always expanded. Defaults to the element's built-in `true` when omitted.
   */
  collapsible?: boolean;
  /**
   * Called when the drawer's collapsed state changes (via the element's collapse
   * toggle), with the new collapsed state. Mirrors the element's
   * `collapse-change` event.
   */
  onCollapseChange?: (collapsed: boolean) => void;
  /**
   * Page size for thread pagination. When set, threads are fetched in pages of
   * this size and the drawer shows a "Load more" control while more remain.
   * When omitted, the full list loads at once and no pagination control shows.
   */
  limit?: number;
  /**
   * `data-testid` set on the underlying custom element (handy in tests and for
   * targeting from a host page). Defaults to `"copilot-threads-drawer"`.
   */
  "data-testid"?: string;
}

/**
 * Maps a {@link Thread} from {@link useThreads} to the element's
 * {@link DrawerThread} view shape. The shapes are structurally compatible; this
 * narrows to exactly the fields the element renders so the element never sees
 * platform-internal fields.
 */
function toDrawerThread(thread: Thread): DrawerThread {
  return {
    id: thread.id,
    name: thread.name,
    archived: thread.archived,
    createdAt: thread.createdAt,
    updatedAt: thread.updatedAt,
    ...(thread.lastRunAt !== undefined ? { lastRunAt: thread.lastRunAt } : {}),
  };
}

/** The chat input textarea's documented `data-testid`. */
const CHAT_INPUT_TESTID = "copilot-chat-textarea";
/** The chat view container's documented `data-testid`. */
const CHAT_CONTAINER_TESTID = "copilot-chat";

/**
 * Returns the chat input element for focus-return after a thread is selected.
 *
 * Best-effort and SCOPED: walks up from the drawer element looking for an
 * ancestor that contains a chat-view container (`data-testid="copilot-chat"`),
 * then returns the chat input within that subtree. This avoids focusing the
 * wrong composer on a page hosting more than one chat (multi-chat dashboards),
 * where a document-global lookup would grab whichever input appears first in
 * DOM order rather than the one this drawer drives.
 *
 * Falls back to a document-global lookup when no scoping ancestor is found
 * (e.g. the drawer and chat share no common container, or headless usage),
 * and returns `null` when there is no chat input at all.
 *
 * @param origin - The drawer element to scope the search from.
 */
function findChatInput(origin: Element | null): HTMLElement | null {
  if (typeof document === "undefined") return null;

  // The drawer lives inside (or alongside) its own chat-view container. Find the
  // nearest such container with `closest` and scope the input lookup to it, so a
  // page hosting multiple chats focuses THIS drawer's composer rather than
  // whichever input appears first in DOM order. Walking up by "ancestor that
  // *contains* a chat" would instead climb past the drawer's own container (which
  // holds no nested chat) to the shared root and grab the first chat on the page.
  const container = origin?.closest?.(
    `[data-testid="${CHAT_CONTAINER_TESTID}"]`,
  );
  if (container) {
    const scoped = container.querySelector<HTMLElement>(
      `[data-testid="${CHAT_INPUT_TESTID}"]`,
    );
    if (scoped) return scoped;
  }

  // No scoping container found (drawer and chat share no common container, or
  // headless usage): fall back to a document-global lookup.
  return document.querySelector<HTMLElement>(
    `[data-testid="${CHAT_INPUT_TESTID}"]`,
  );
}

/**
 * React wrapper for the shadow-DOM `<copilotkit-threads-drawer>` threads drawer.
 *
 * Responsibilities:
 * - Registers the custom element on the client (SSR-safe; nothing renders
 *   during prerender to avoid hydration mismatch).
 * - Feeds the element domain data: `threads`, `loading`, `error`,
 *   `activeThreadId`, `licensed`, fetch-more state.
 * - Routes the element's outbound events to core thread operations
 *   ({@link useThreads}) and chat-configuration changes.
 * - Registers with the surrounding chat configuration so the header
 *   thread-list launcher appears, and binds the element `open` state to the
 *   configuration's `drawerOpen`.
 *
 * Intelligence gating is two-pronged: the locked view shows when the runtime
 * reports no active entitlement OR the `threads` feature is unavailable. While
 * unavailable, the thread fetch is skipped entirely so the drawer issues no
 * network requests.
 *
 * Thread switching needs no host wiring: when `onThreadSelect`/`onNewThread`
 * are omitted, the wrapper drives the surrounding chat configuration directly
 * ({@link CopilotChatConfigurationValue.setActiveThreadId} /
 * {@link CopilotChatConfigurationValue.startNewThread}), so a bare drawer
 * connects to the picked thread and shows the welcome screen on "+ New". Pass
 * the callbacks only to take control yourself.
 *
 * @example
 * ```tsx
 * // Callback-free: the drawer drives the chat configuration itself.
 * <CopilotKitProvider runtimeUrl="/api/copilotkit">
 *   <CopilotChat />
 *   <CopilotThreadsDrawer />
 * </CopilotKitProvider>
 * ```
 */
export function CopilotThreadsDrawer({
  agentId,
  onThreadSelect,
  onNewThread,
  onLicensed,
  licenseUrl,
  renderRow,
  label,
  recentLabel,
  collapsible,
  onCollapseChange,
  limit,
  "data-testid": dataTestId = "copilot-threads-drawer",
}: CopilotThreadsDrawerProps): React.ReactElement | null {
  const configuration = useCopilotChatConfiguration();
  const { status, checkFeature } = useLicenseContext();

  // Two-pronged license gate. `checkFeature` fails OPEN (returns true) when no
  // license is configured, so it cannot by itself detect the no-license case.
  // We therefore also require a positive license-present signal from the
  // runtime-reported status. Only a "valid" or "expiring" license is treated
  // as present; a resolved "none"/"expired"/"invalid" status gates the drawer
  // to the locked view.
  const licensePresent = status === "valid" || status === "expiring";
  const featureLicensed = checkFeature("threads");
  const licensed = licensePresent && featureLicensed;

  // The runtime reports license status asynchronously: `status` is null until
  // the first /info response lands and while a retryable entitlement lookup is
  // recovering. Treat either pending window as "not yet unlicensed" — show the
  // loading state, never the locked view — so a licensed drawer does not flash
  // the upgrade CTA before its authority resolves. Only a resolved-negative
  // status (`none`/`expired`/`invalid`, or a present license missing the
  // `threads` feature) surfaces the locked view.
  const licensePending = status === null;

  const providerAgentId = useDefaultAgentId();
  const resolvedAgentId =
    agentId ?? configuration?.agentId ?? providerAgentId ?? DEFAULT_AGENT_ID;
  const activeThreadId = configuration?.threadId ?? null;

  // While unlicensed, skip the thread fetch entirely: the element shows only
  // its locked view and no `/threads` request is issued.
  const {
    threads,
    isLoading,
    listError,
    fetchMoreError,
    hasMoreThreads,
    isFetchingMoreThreads,
    archiveThread,
    unarchiveThread,
    deleteThread,
    fetchMoreThreads,
    refetchThreads,
    startNewThread,
  } = useThreads({
    agentId: resolvedAgentId,
    includeArchived: true,
    enabled: licensed,
    ...(limit !== undefined ? { limit } : {}),
  });

  const drawerThreads = useMemo(() => threads.map(toDrawerThread), [threads]);

  const elementRef = useRef<CopilotKitThreadsDrawerElement | null>(null);

  // Register the custom element on the client only. `customElements` is absent
  // during SSR/prerender; gating the render below on `mounted` keeps the server
  // output empty so there is no hydration mismatch or layout shift.
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    defineCopilotKitThreadsDrawer();
    setMounted(true);
  }, []);

  // Announce presence to the surrounding chat configuration so the header
  // launcher renders; de-register on unmount. Depend on the stable
  // `registerDrawer` callback, NOT the whole `configuration` object — the
  // object's identity changes on every drawer/modal/label update, which would
  // otherwise churn register/de-register each render and momentarily drop
  // `drawerRegistered` (flickering the header launcher).
  const registerDrawer = configuration?.registerDrawer;
  useEffect(() => {
    if (!registerDrawer) return;
    return registerDrawer();
  }, [registerDrawer]);

  // Drive the chat configuration's drawerOpen from the element's open-change
  // event, and reflect drawerOpen back onto the element below.
  //
  // Provider-less fallback: without a surrounding chat configuration there is no
  // shared open-state to bind to, so the wrapper keeps its own local open-state.
  // It starts CLOSED — matching the provider's own `ownDrawerOpen` default of
  // `false` — so a bare `<CopilotThreadsDrawer>` does not render stuck-open and the
  // element's open-change events still toggle it.
  const [localDrawerOpen, setLocalDrawerOpen] = useState(false);
  const drawerOpen = configuration ? configuration.drawerOpen : localDrawerOpen;
  const setDrawerOpen = configuration
    ? configuration.setDrawerOpen
    : setLocalDrawerOpen;

  // --- Event handlers (stable via refs to the latest closures) -------------
  // The element is imperatively wired with addEventListener once; we keep the
  // latest handler implementations in a ref so listeners need not be re-bound
  // every render (which would churn on each thread/loading change).

  // Prefer the host callbacks when provided; otherwise drive the surrounding
  // chat configuration directly so a bare `<CopilotThreadsDrawer>` works callback-free.
  const setActiveThreadId = configuration?.setActiveThreadId;
  const startNewThreadConfig = configuration?.startNewThread;

  const handleThreadSelected = useCallback(
    (threadId: string) => {
      if (onThreadSelect) {
        onThreadSelect(threadId);
      } else {
        // Selecting a row is an explicit, caller-driven thread choice: connect
        // the chat to that backend thread (suppresses the welcome screen).
        setActiveThreadId?.(threadId, { explicit: true });
      }
      // Return focus to the chat input so keyboard users land in the composer.
      // Scope the lookup to this drawer's own chat (not document-global).
      findChatInput(elementRef.current)?.focus();
    },
    [onThreadSelect, setActiveThreadId],
  );

  const handleNewThread = useCallback(() => {
    // Reset the core thread store to a fresh, non-explicit client-side thread
    // (clears any stale error so the welcome screen can render cleanly).
    startNewThread();
    if (onNewThread) {
      onNewThread();
    } else {
      // No host callback: reset the surrounding chat configuration to a fresh,
      // non-explicit thread so the welcome screen shows with no host wiring.
      startNewThreadConfig?.();
    }
  }, [startNewThread, onNewThread, startNewThreadConfig]);

  const handleArchive = useCallback(
    (threadId: string) => {
      void archiveThread(threadId).catch((err) => {
        console.error("CopilotThreadsDrawer: archiveThread failed", err);
      });
    },
    [archiveThread],
  );

  const handleUnarchive = useCallback(
    (threadId: string) => {
      void unarchiveThread(threadId).catch((err) => {
        console.error("CopilotThreadsDrawer: unarchiveThread failed", err);
      });
    },
    [unarchiveThread],
  );

  const handleDelete = useCallback(
    (threadId: string) => {
      // Deleting the active thread resets to a fresh, non-explicit thread so the
      // user is not stranded on a now-gone conversation. Archiving the active
      // thread keeps the user viewing it.
      const isActive = threadId === activeThreadId;
      // The core thread store performs the optimistic removal (and rollback on
      // failure) in its own reducer, so the wrapper holds no removal bookkeeping
      // of its own — it simply renders the threads the store hands it.
      void deleteThread(threadId)
        .then(() => {
          if (isActive) {
            startNewThread();
            if (onNewThread) {
              onNewThread();
            } else {
              startNewThreadConfig?.();
            }
          }
        })
        .catch((err) => {
          console.error("CopilotThreadsDrawer: deleteThread failed", err);
        });
    },
    [
      deleteThread,
      activeThreadId,
      startNewThread,
      onNewThread,
      startNewThreadConfig,
    ],
  );

  const handleFilterChange = useCallback(() => {
    // The element owns the Active/All filter; on change we refetch so the list
    // reflects the server.
    refetchThreads();
  }, [refetchThreads]);

  const handleRetry = useCallback(
    (scope: RetryDetail["scope"]) => {
      if (scope === "fetch-more") {
        fetchMoreThreads();
      } else {
        refetchThreads();
      }
    },
    [fetchMoreThreads, refetchThreads],
  );

  const handleOpenChange = useCallback(
    (open: boolean) => {
      setDrawerOpen(open);
    },
    [setDrawerOpen],
  );

  const handleLicensed = useCallback(() => {
    onLicensed?.();
  }, [onLicensed]);

  const handleLoadMore = useCallback(() => {
    // Advance pagination. No-op when there is no next page; the element only
    // surfaces the "Load more" control while `hasMore` is true.
    fetchMoreThreads();
  }, [fetchMoreThreads]);

  const handleCollapseChange = useCallback(
    (collapsed: boolean) => {
      onCollapseChange?.(collapsed);
    },
    [onCollapseChange],
  );

  // Keep a ref to the live handlers so the addEventListener effect can stay
  // stable (bind once) while still calling the freshest closures.
  const handlersRef = useRef({
    handleThreadSelected,
    handleNewThread,
    handleArchive,
    handleUnarchive,
    handleDelete,
    handleFilterChange,
    handleRetry,
    handleOpenChange,
    handleLicensed,
    handleLoadMore,
    handleCollapseChange,
  });
  handlersRef.current = {
    handleThreadSelected,
    handleNewThread,
    handleArchive,
    handleUnarchive,
    handleDelete,
    handleFilterChange,
    handleRetry,
    handleOpenChange,
    handleLicensed,
    handleLoadMore,
    handleCollapseChange,
  };

  // Bind the outbound DOM events once the element exists. Listeners are
  // bound a single time and cleaned up on unmount; they dispatch through the
  // handlers ref so they always invoke the latest closures.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;

    const onThreadSelected = (event: Event) => {
      const detail = (event as CustomEvent<ThreadSelectedDetail>).detail;
      handlersRef.current.handleThreadSelected(detail.threadId);
    };
    const onNewThreadEvent = () => handlersRef.current.handleNewThread();
    const onArchive = (event: Event) => {
      const detail = (event as CustomEvent<ArchiveDetail>).detail;
      handlersRef.current.handleArchive(detail.threadId);
    };
    const onUnarchive = (event: Event) => {
      const detail = (event as CustomEvent<UnarchiveDetail>).detail;
      handlersRef.current.handleUnarchive(detail.threadId);
    };
    const onDelete = (event: Event) => {
      const detail = (event as CustomEvent<DeleteDetail>).detail;
      handlersRef.current.handleDelete(detail.threadId);
    };
    const onFilterChange = (_event: Event) => {
      handlersRef.current.handleFilterChange();
    };
    const onOpenChangeEvent = (event: Event) => {
      const detail = (event as CustomEvent<OpenChangeDetail>).detail;
      handlersRef.current.handleOpenChange(detail.open);
    };
    const onRetry = (event: Event) => {
      const detail = (event as CustomEvent<RetryDetail>).detail;
      handlersRef.current.handleRetry(detail.scope);
    };
    const onLicensedEvent = () => handlersRef.current.handleLicensed();
    const onLoadMore = () => handlersRef.current.handleLoadMore();
    const onCollapseChangeEvent = (event: Event) => {
      const detail = (event as CustomEvent<CollapseChangeDetail>).detail;
      handlersRef.current.handleCollapseChange(detail.collapsed);
    };

    el.addEventListener("thread-selected", onThreadSelected);
    el.addEventListener("new-thread", onNewThreadEvent);
    el.addEventListener("archive", onArchive);
    el.addEventListener("unarchive", onUnarchive);
    el.addEventListener("delete", onDelete);
    el.addEventListener("filter-change", onFilterChange);
    el.addEventListener("open-change", onOpenChangeEvent);
    el.addEventListener("retry", onRetry);
    el.addEventListener("licensed", onLicensedEvent);
    el.addEventListener("load-more", onLoadMore);
    el.addEventListener("collapse-change", onCollapseChangeEvent);

    return () => {
      el.removeEventListener("thread-selected", onThreadSelected);
      el.removeEventListener("new-thread", onNewThreadEvent);
      el.removeEventListener("archive", onArchive);
      el.removeEventListener("unarchive", onUnarchive);
      el.removeEventListener("delete", onDelete);
      el.removeEventListener("filter-change", onFilterChange);
      el.removeEventListener("open-change", onOpenChangeEvent);
      el.removeEventListener("retry", onRetry);
      el.removeEventListener("licensed", onLicensedEvent);
      el.removeEventListener("load-more", onLoadMore);
      el.removeEventListener("collapse-change", onCollapseChangeEvent);
    };
    // Re-bind only after the first client mount (deps: [mounted]); the element
    // ref is stable thereafter.
  }, [mounted]);

  // Assign object/array/boolean PROPERTIES imperatively. React would otherwise
  // set these as string attributes, which a custom element cannot accept for
  // arrays/objects. Setting them as instance properties is the correct interop.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    el.threads = drawerThreads;
  }, [drawerThreads, mounted]);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    // While the license is still resolving, force the loading state so the
    // element shows its spinner instead of an empty/unlicensed body.
    el.loading = isLoading || licensePending;
    // Only genuine list-load/mutation errors reach the end user. Developer/
    // config errors (missing runtime URL, runtime without thread endpoints) are
    // excluded via `listError` so they never leak into the drawer's error UI.
    el.error = listError ? listError.message : null;
    el.activeThreadId = activeThreadId;
    // Pending counts as licensed for rendering: `_renderBody` shows the locked view
    // only when `licensed` is false, so keeping it true until the status
    // resolves prevents the locked view from flashing (or sticking) mid-resolution.
    el.licensed = licensed || licensePending;
    el.hasMore = hasMoreThreads;
    el.fetchingMore = isFetchingMoreThreads;
    // Dedicated fetch-more error channel: drives the element's inline
    // "couldn't load more — retry" panel without disturbing the loaded list or
    // the initial-list `error`. The `retry{scope:"fetch-more"}` handler
    // becomes reachable once this panel renders.
    el.fetchMoreError = fetchMoreError ? fetchMoreError.message : null;
  }, [
    isLoading,
    listError,
    fetchMoreError,
    activeThreadId,
    licensed,
    licensePending,
    hasMoreThreads,
    isFetchingMoreThreads,
    mounted,
  ]);

  // Bind the element's controlled `open` to the chat configuration's
  // drawerOpen, so the header launcher and the element stay in sync.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    el.open = drawerOpen;
  }, [drawerOpen, mounted]);

  // Mirror the optional `label` onto the element (its accessible + default
  // header text). Leave the element's built-in default ("Threads") in place
  // when the prop is omitted, rather than clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (label !== undefined) el.label = label;
  }, [label, mounted]);

  // Mirror the optional `licenseUrl` onto the element (the locked view's
  // Upgrade CTA destination). Leave the element's built-in default in place
  // when the prop is omitted, rather than clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (licenseUrl !== undefined) el.licenseUrl = licenseUrl;
  }, [licenseUrl, mounted]);

  // Mirror the optional `collapsible` onto the element as a PROPERTY (a
  // default-true boolean, exactly like `licensed` — a string attribute cannot
  // represent it since any non-empty value is truthy). Leave the element's
  // built-in default (`true`) in place when the prop is omitted, rather than
  // clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (collapsible !== undefined) {
      // TODO(ENT-1051): drop the intersection cast once the published element
      // type declares `collapsible` (see the local CollapseChangeDetail note).
      (
        el as CopilotKitThreadsDrawerElement & { collapsible: boolean }
      ).collapsible = collapsible;
    }
  }, [collapsible, mounted]);

  // Per-row light-DOM children projected via `slot="row:{id}"`.
  const rowChildren = useMemo(() => {
    if (!renderRow) return null;
    return drawerThreads.map((drawerThread) => {
      const fullThread = threads.find((t) => t.id === drawerThread.id);
      if (!fullThread) return null;
      const content = renderRow(fullThread);
      if (content === null || content === undefined) return null;
      return (
        <div key={drawerThread.id} slot={`row:${drawerThread.id}`}>
          {content}
        </div>
      );
    });
  }, [renderRow, drawerThreads, threads]);

  // SSR / pre-mount: render nothing so the server output matches the initial
  // client render (the element is not yet registered), avoiding hydration
  // mismatch and layout shift.
  if (!mounted) return null;

  return React.createElement(
    COPILOTKIT_THREADS_DRAWER_TAG,
    {
      ref: elementRef,
      "data-testid": dataTestId,
      // Pass the section heading label as an attribute; omit it entirely when
      // unset so the element keeps its built-in default rather than receiving
      // an `undefined` that would clobber it.
      ...(recentLabel !== undefined ? { "recent-label": recentLabel } : {}),
    },
    rowChildren,
  );
}

CopilotThreadsDrawer.displayName = "CopilotThreadsDrawer";

export default CopilotThreadsDrawer;
