// packages/vue/src/v2/components/chat/CopilotChatToolCallsView.vue
<script setup lang="ts">
import { inject, useSlots } from "vue";
import type { AssistantMessage, Message } from "@ag-ui/core";
import type { CopilotChatToolCallRenderSlotProps } from "./types";
import CopilotChatToolCallItem from "./CopilotChatToolCallItem.vue";
import CopilotChatSubagentGroup, {
  SubagentLayoutKey,
} from "./CopilotChatSubagentGroup";

withDefaults(
  defineProps<{
    message: AssistantMessage;
    messages?: Message[];
  }>(),
  {
    messages: () => [],
  },
);

defineSlots<{
  "tool-call"?: (props: CopilotChatToolCallRenderSlotProps) => unknown;
  [key: `tool-call-${string}`]: (
    props: CopilotChatToolCallRenderSlotProps,
  ) => unknown;
}>();

type ToolCallSlotName = "tool-call" | `tool-call-${string}`;
const componentSlots = useSlots() as Record<
  ToolCallSlotName,
  (props?: unknown) => unknown
>;
function getForwardedSlotNames(): ToolCallSlotName[] {
  return Object.keys(componentSlots) as ToolCallSlotName[];
}

// The subagents a tool call started render right after it, even when no
// renderer is registered for the call.
const subagentLayout = inject(SubagentLayoutKey, null);
function groupsFor(toolCallId: string) {
  return subagentLayout?.value.layout.byToolCallId.get(toolCallId) ?? [];
}
</script>

<template>
  <template v-for="toolCall in message.toolCalls ?? []" :key="toolCall.id">
    <CopilotChatToolCallItem :tool-call="toolCall" :messages="messages">
      <template
        v-for="slotName in getForwardedSlotNames()"
        :key="slotName"
        #[slotName]="slotProps"
      >
        <slot :name="slotName" v-bind="slotProps ?? {}" />
      </template>
    </CopilotChatToolCallItem>
    <CopilotChatSubagentGroup
      v-for="group in groupsFor(toolCall.id)"
      :key="`subagent-${group.subagentRunId}`"
      :group="group"
    />
  </template>
</template>

// packages/react-core/src/v2/components/chat/CopilotChatToolCallsView.tsx
import { useRenderToolCall } from "../../hooks";
import type { AssistantMessage, Message, ToolMessage } from "@ag-ui/core";
import React, { useContext } from "react";
import { SubagentLayoutContext } from "./CopilotChatSubagent";

export type CopilotChatToolCallsViewProps = {
  message: AssistantMessage;
  messages?: Message[];
};

export function CopilotChatToolCallsView({
  message,
  messages = [],
}: CopilotChatToolCallsViewProps) {
  const renderToolCall = useRenderToolCall();
  const subagents = useContext(SubagentLayoutContext);

  if (!message.toolCalls || message.toolCalls.length === 0) {
    return null;
  }

  return (
    <>
      {message.toolCalls.map((toolCall) => {
        const toolMessage = messages.find(
          (m) => m.role === "tool" && m.toolCallId === toolCall.id,
        ) as ToolMessage | undefined;

        return (
          <React.Fragment key={toolCall.id}>
            {renderToolCall({
              toolCall,
              toolMessage,
            })}
            {/* The subagents this call started, even when no renderer is registered for the call. */}
            {subagents?.layout.byToolCallId
              .get(toolCall.id)
              ?.map(subagents.renderGroup)}
          </React.Fragment>
        );
      })}
    </>
  );
}

export default CopilotChatToolCallsView;
