// src/v2.x/packages/vue/src/components/chat/CopilotChat.vue
<script setup lang="ts">
import { AGUIConnectNotImplementedError } from "@ag-ui/client";
import { DEFAULT_AGENT_ID, randomUUID, TranscriptionErrorCode } from "@copilotkitnext/shared";
import { computed, getCurrentInstance, ref, shallowRef, useAttrs, watch } from "vue";
import type { Suggestion } from "@copilotkitnext/core";
import CopilotChatConfigurationProvider from "../../providers/CopilotChatConfigurationProvider.vue";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import { useCopilotKit } from "../../providers/useCopilotKit";
import { useAgent } from "../../hooks/use-agent";
import { useSuggestions } from "../../hooks/use-suggestions";
import { transcribeAudio, TranscriptionError } from "../../lib/transcription-client";
import CopilotChatView from "./CopilotChatView.vue";
import type {
  CopilotChatInputSlotProps,
  CopilotChatProps,
  CopilotChatSuggestionViewSlotProps,
  CopilotChatViewOverrideSlotProps,
  CopilotChatWelcomeScreenSlotProps,
} from "./types";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CopilotChatProps>(), {
  autoScroll: true,
  welcomeScreen: true,
  inputValue: undefined,
  inputMode: "input",
  inputToolsMenu: () => [],
  onFinishTranscribeWithAudio: undefined,
});

defineSlots<{
  "chat-view"?: (props: CopilotChatViewOverrideSlotProps) => unknown;
  "message-view"?: (props: { messages: import("@ag-ui/core").Message[]; isRunning: boolean }) => unknown;
  input?: (props: CopilotChatInputSlotProps) => unknown;
  "suggestion-view"?: (props: CopilotChatSuggestionViewSlotProps) => unknown;
  "welcome-screen"?: (props: CopilotChatWelcomeScreenSlotProps) => unknown;
  "welcome-message"?: () => unknown;
}>();

const emit = defineEmits<{
  "submit-message": [value: string];
  stop: [];
  "input-change": [value: string];
  "select-suggestion": [suggestion: Suggestion, index: number];
  "add-file": [];
  "start-transcribe": [];
  "cancel-transcribe": [];
  "finish-transcribe": [];
}>();

const attrs = useAttrs();
const existingConfig = useCopilotChatConfiguration();
const { copilotkit } = useCopilotKit();
const instance = getCurrentInstance();
const vnodeProps = computed(() => (instance?.vnode.props ?? {}) as Record<string, unknown>);

const generatedThreadId = ref(randomUUID());
const transcribeMode = ref<"input" | "transcribe" | "processing">("input");
const inputValue = ref(props.inputValue ?? "");
const transcriptionError = ref<string | null>(null);
const isTranscribing = ref(false);
const lastConnectedAgent = shallowRef<object | null>(null);
const lastConnectedCore = shallowRef<object | null>(null);
const lastConnectedThreadId = ref<string | undefined>(undefined);

const resolvedAgentId = computed(() => props.agentId ?? existingConfig.value?.agentId ?? DEFAULT_AGENT_ID);
const resolvedThreadId = computed(
  () => props.threadId ?? existingConfig.value?.threadId ?? generatedThreadId.value,
);
const resolvedLabels = computed(() => props.labels);

const { agent } = useAgent({ agentId: resolvedAgentId });
const {
  suggestions: autoSuggestions,
} = useSuggestions({ agentId: resolvedAgentId });

const isTranscriptionEnabled = computed(() => copilotkit.value.audioFileTranscriptionEnabled);
const isMediaRecorderSupported = computed(
  () => typeof window !== "undefined" && typeof MediaRecorder !== "undefined",
);
const showTranscription = computed(
  () => isTranscriptionEnabled.value && isMediaRecorderSupported.value,
);
const effectiveMode = computed<"input" | "transcribe" | "processing">(() =>
  isTranscribing.value ? "processing" : transcribeMode.value,
);
const messages = computed(() => [...(agent.value?.messages ?? [])]);
const isRunning = computed(() => agent.value?.isRunning ?? false);
const shouldAllowStop = computed(() => isRunning.value && messages.value.length > 0);

function hasListener(listenerName: string) {
  const listener = vnodeProps.value[listenerName];
  if (Array.isArray(listener)) {
    return listener.length > 0;
  }
  return !!listener;
}

watch(
  () => props.inputValue,
  (next) => {
    if (next !== undefined) {
      inputValue.value = next;
    }
  },
);

watch(
  [() => props.threadId, () => existingConfig.value?.threadId],
  ([threadId, inheritedThreadId], previousValues) => {
    if (threadId || inheritedThreadId) {
      return;
    }

    if (previousValues && (previousValues[0] || previousValues[1])) {
      generatedThreadId.value = randomUUID();
    }
  },
);

watch(
  [agent, resolvedThreadId, copilotkit],
  ([currentAgent, threadId, core]) => {
    if (typeof window === "undefined") {
      return;
    }
    if (!currentAgent) {
      return;
    }

    if (currentAgent.threadId !== threadId) {
      currentAgent.threadId = threadId;
    }
    if (!core.runtimeUrl) {
      return;
    }
    if (
      lastConnectedAgent.value === currentAgent &&
      lastConnectedCore.value === core &&
      lastConnectedThreadId.value === threadId
    ) {
      return;
    }

    lastConnectedAgent.value = currentAgent;
    lastConnectedCore.value = core;
    lastConnectedThreadId.value = threadId;

    void core.connectAgent({ agent: currentAgent }).catch((error: unknown) => {
      if (error instanceof AGUIConnectNotImplementedError) {
        return;
      }
      throw error;
    });
  },
  { immediate: true },
);

watch(
  transcriptionError,
  (next, _old, onCleanup) => {
    if (!next) {
      return;
    }
    const timer = setTimeout(() => {
      transcriptionError.value = null;
    }, 5000);
    onCleanup(() => clearTimeout(timer));
  },
);

async function runCurrentAgent() {
  const currentAgent = agent.value;
  if (!currentAgent) {
    return;
  }

  try {
    await copilotkit.value.runAgent({ agent: currentAgent });
  } catch (error) {
    console.error("CopilotChat: runAgent failed", error);
  }
}

async function handleSubmitMessage(value: string) {
  emit("submit-message", value);
  agent.value?.addMessage({
    id: randomUUID(),
    role: "user",
    content: value,
  });
  inputValue.value = "";
  await runCurrentAgent();
}

async function handleSelectSuggestion(suggestion: Suggestion, index: number) {
  emit("select-suggestion", suggestion, index);
  agent.value?.addMessage({
    id: randomUUID(),
    role: "user",
    content: suggestion.message,
  });
  await runCurrentAgent();
}

function stopCurrentRun() {
  const currentAgent = agent.value;
  if (!currentAgent) {
    return;
  }

  try {
    copilotkit.value.stopAgent({ agent: currentAgent });
  } catch (error) {
    console.error("CopilotChat: stopAgent failed", error);
    try {
      currentAgent.abortRun();
    } catch (abortError) {
      console.error("CopilotChat: abortRun fallback failed", abortError);
    }
  }
}

function handleStop() {
  emit("stop");
  if (shouldAllowStop.value) {
    stopCurrentRun();
  }
}

function handleInputChange(value: string) {
  inputValue.value = value;
  emit("input-change", value);
}

function handleAddFile() {
  emit("add-file");
}

function handleStartTranscribe() {
  transcriptionError.value = null;
  transcribeMode.value = "transcribe";
  emit("start-transcribe");
}

function handleCancelTranscribe() {
  transcriptionError.value = null;
  transcribeMode.value = "input";
  emit("cancel-transcribe");
}

function handleFinishTranscribe() {
  transcribeMode.value = "input";
  emit("finish-transcribe");
}

async function handleFinishTranscribeWithAudio(audioBlob: Blob) {
  if (props.onFinishTranscribeWithAudio) {
    await props.onFinishTranscribeWithAudio(audioBlob);
    return;
  }

  isTranscribing.value = true;
  try {
    transcriptionError.value = null;
    const result = await transcribeAudio(copilotkit.value, audioBlob);
    const trimmedPrevious = inputValue.value.trim();
    inputValue.value = trimmedPrevious ? `${trimmedPrevious} ${result.text}` : result.text;
  } catch (error) {
    console.error("CopilotChat: Transcription failed", error);
    if (error instanceof TranscriptionError) {
      const { code, retryable, message } = error.info;
      switch (code) {
        case TranscriptionErrorCode.RATE_LIMITED:
          transcriptionError.value = "Too many requests. Please wait a moment.";
          break;
        case TranscriptionErrorCode.AUTH_FAILED:
          transcriptionError.value = "Authentication error. Please check your configuration.";
          break;
        case TranscriptionErrorCode.AUDIO_TOO_LONG:
          transcriptionError.value = "Recording is too long. Please try a shorter recording.";
          break;
        case TranscriptionErrorCode.AUDIO_TOO_SHORT:
          transcriptionError.value = "Recording is too short. Please try again.";
          break;
        case TranscriptionErrorCode.INVALID_AUDIO_FORMAT:
          transcriptionError.value = "Audio format not supported.";
          break;
        case TranscriptionErrorCode.SERVICE_NOT_CONFIGURED:
          transcriptionError.value = "Transcription service is not available.";
          break;
        case TranscriptionErrorCode.NETWORK_ERROR:
          transcriptionError.value = "Network error. Please check your connection.";
          break;
        default:
          transcriptionError.value = retryable
            ? "Transcription failed. Please try again."
            : message;
      }
    } else {
      transcriptionError.value = "Transcription failed. Please try again.";
    }
  } finally {
    isTranscribing.value = false;
  }
}

const chatViewSlotProps = computed<CopilotChatViewOverrideSlotProps>(() => ({
  messages: messages.value,
  autoScroll: props.autoScroll,
  isRunning: isRunning.value,
  suggestions: autoSuggestions.value,
  suggestionLoadingIndexes: [],
  welcomeScreen: props.welcomeScreen,
  inputValue: inputValue.value,
  inputMode: effectiveMode.value,
  inputToolsMenu: props.inputToolsMenu,
  onSubmitMessage: handleSubmitMessage,
  onStop: shouldAllowStop.value ? handleStop : undefined,
  onInputChange: handleInputChange,
  onSelectSuggestion: handleSelectSuggestion,
  onAddFile: hasListener("onAddFile") ? handleAddFile : undefined,
  onStartTranscribe: showTranscription.value ? handleStartTranscribe : undefined,
  onCancelTranscribe: showTranscription.value ? handleCancelTranscribe : undefined,
  onFinishTranscribe: showTranscription.value ? handleFinishTranscribe : undefined,
  onFinishTranscribeWithAudio: showTranscription.value ? handleFinishTranscribeWithAudio : undefined,
}));

const defaultChatViewBindings = computed(() => {
  const listeners: Record<string, unknown> = {
    ...attrs,
    onSubmitMessage: handleSubmitMessage,
    onInputChange: handleInputChange,
    onSelectSuggestion: handleSelectSuggestion,
  };

  if (shouldAllowStop.value) {
    listeners.onStop = handleStop;
  }
  if (hasListener("onAddFile")) {
    listeners.onAddFile = handleAddFile;
  }
  if (showTranscription.value) {
    listeners.onStartTranscribe = handleStartTranscribe;
    listeners.onCancelTranscribe = handleCancelTranscribe;
    listeners.onFinishTranscribe = handleFinishTranscribe;
  }

  return listeners;
});
</script>

<template>
  <CopilotChatConfigurationProvider
    :agent-id="resolvedAgentId"
    :thread-id="resolvedThreadId"
    :labels="resolvedLabels"
  >
    <div
      v-if="transcriptionError"
      style="position: absolute; bottom: 100px; left: 50%; transform: translateX(-50%); background-color: #ef4444; color: white; padding: 8px 16px; border-radius: 8px; font-size: 14px; z-index: 50;"
    >
      {{ transcriptionError }}
    </div>

    <slot name="chat-view" v-bind="chatViewSlotProps">
      <CopilotChatView
        :messages="chatViewSlotProps.messages"
        :auto-scroll="chatViewSlotProps.autoScroll"
        :is-running="chatViewSlotProps.isRunning"
        :suggestions="chatViewSlotProps.suggestions"
        :suggestion-loading-indexes="chatViewSlotProps.suggestionLoadingIndexes"
        :welcome-screen="chatViewSlotProps.welcomeScreen"
        :input-value="chatViewSlotProps.inputValue"
        :input-mode="chatViewSlotProps.inputMode"
        :input-tools-menu="chatViewSlotProps.inputToolsMenu"
        :on-finish-transcribe-with-audio="chatViewSlotProps.onFinishTranscribeWithAudio"
        v-bind="defaultChatViewBindings"
      >
        <template v-if="$slots['message-view']" #message-view="slotProps">
          <slot name="message-view" v-bind="slotProps" />
        </template>

        <template v-if="$slots.input" #input="slotProps">
          <slot name="input" v-bind="slotProps" />
        </template>

        <template v-if="$slots['suggestion-view']" #suggestion-view="slotProps">
          <slot name="suggestion-view" v-bind="slotProps" />
        </template>

        <template v-if="$slots['welcome-screen']" #welcome-screen="slotProps">
          <slot name="welcome-screen" v-bind="slotProps" />
        </template>

        <template v-if="$slots['welcome-message']" #welcome-message>
          <slot name="welcome-message" />
        </template>
      </CopilotChatView>
    </slot>
  </CopilotChatConfigurationProvider>
</template>

// src/v2.x/packages/react/src/components/chat/CopilotChat.tsx
import { useAgent } from "@/hooks/use-agent";
import { useSuggestions } from "@/hooks/use-suggestions";
import { CopilotChatView, CopilotChatViewProps } from "./CopilotChatView";
import CopilotChatInput, { CopilotChatInputProps, CopilotChatInputMode } from "./CopilotChatInput";
import {
  CopilotChatConfigurationProvider,
  CopilotChatLabels,
  useCopilotChatConfiguration,
} from "@/providers/CopilotChatConfigurationProvider";
import { DEFAULT_AGENT_ID, randomUUID, TranscriptionErrorCode } from "@copilotkitnext/shared";
import { Suggestion, CopilotKitCoreErrorCode } from "@copilotkitnext/core";
import { useCallback, useEffect, useMemo, useState } from "react";
import { merge } from "ts-deepmerge";
import { useCopilotKit } from "@/providers/CopilotKitProvider";
import { AbstractAgent, AGUIConnectNotImplementedError } from "@ag-ui/client";
import { renderSlot, SlotValue } from "@/lib/slots";
import { transcribeAudio, TranscriptionError } from "@/lib/transcription-client";

export type CopilotChatProps = Omit<
  CopilotChatViewProps,
  "messages" | "isRunning" | "suggestions" | "suggestionLoadingIndexes" | "onSelectSuggestion"
> & {
  agentId?: string;
  threadId?: string;
  labels?: Partial<CopilotChatLabels>;
  chatView?: SlotValue<typeof CopilotChatView>;
  isModalDefaultOpen?: boolean;
};
export function CopilotChat({ agentId, threadId, labels, chatView, isModalDefaultOpen, ...props }: CopilotChatProps) {
  // Check for existing configuration provider
  const existingConfig = useCopilotChatConfiguration();

  // Apply priority: props > existing config > defaults
  const resolvedAgentId = agentId ?? existingConfig?.agentId ?? DEFAULT_AGENT_ID;
  const resolvedThreadId = useMemo(
    () => threadId ?? existingConfig?.threadId ?? randomUUID(),
    [threadId, existingConfig?.threadId],
  );
  const { agent } = useAgent({ agentId: resolvedAgentId });
  const { copilotkit } = useCopilotKit();

  const { suggestions: autoSuggestions } = useSuggestions({ agentId: resolvedAgentId });

  // Transcription state
  const [transcribeMode, setTranscribeMode] = useState<CopilotChatInputMode>("input");
  const [inputValue, setInputValue] = useState("");
  const [transcriptionError, setTranscriptionError] = useState<string | null>(null);
  const [isTranscribing, setIsTranscribing] = useState(false);

  // Check if transcription is enabled
  const isTranscriptionEnabled = copilotkit.audioFileTranscriptionEnabled;

  // Check if browser supports MediaRecorder
  const isMediaRecorderSupported = typeof window !== "undefined" && typeof MediaRecorder !== "undefined";

  const {
    inputProps: providedInputProps,
    messageView: providedMessageView,
    suggestionView: providedSuggestionView,
    ...restProps
  } = props;

  useEffect(() => {
    const connect = async (agent: AbstractAgent) => {
      try {
        await copilotkit.connectAgent({ agent });
      } catch (error) {
        if (error instanceof AGUIConnectNotImplementedError) {
          // connect not implemented, ignore
        } else {
          throw error;
        }
      }
    };
    agent.threadId = resolvedThreadId;
    connect(agent);
    return () => {};
  }, [resolvedThreadId, agent, copilotkit, resolvedAgentId]);

  const onSubmitInput = useCallback(
    async (value: string) => {
      agent.addMessage({
        id: randomUUID(),
        role: "user",
        content: value,
      });
      // Clear input after submitting
      setInputValue("");
      try {
        await copilotkit.runAgent({ agent });
      } catch (error) {
        console.error("CopilotChat: runAgent failed", error);
      }
    },
    [agent, copilotkit],
  );

  const handleSelectSuggestion = useCallback(
    async (suggestion: Suggestion) => {
      agent.addMessage({
        id: randomUUID(),
        role: "user",
        content: suggestion.message,
      });

      try {
        await copilotkit.runAgent({ agent });
      } catch (error) {
        console.error("CopilotChat: runAgent failed after selecting suggestion", error);
      }
    },
    [agent, copilotkit],
  );

  const stopCurrentRun = useCallback(() => {
    try {
      copilotkit.stopAgent({ agent });
    } catch (error) {
      console.error("CopilotChat: stopAgent failed", error);
      try {
        agent.abortRun();
      } catch (abortError) {
        console.error("CopilotChat: abortRun fallback failed", abortError);
      }
    }
  }, [agent, copilotkit]);

  // Transcription handlers
  const handleStartTranscribe = useCallback(() => {
    setTranscriptionError(null);
    setTranscribeMode("transcribe");
  }, []);

  const handleCancelTranscribe = useCallback(() => {
    setTranscriptionError(null);
    setTranscribeMode("input");
  }, []);

  const handleFinishTranscribe = useCallback(() => {
    setTranscribeMode("input");
  }, []);

  // Handle audio blob from CopilotChatInput and transcribe it
  const handleFinishTranscribeWithAudio = useCallback(async (audioBlob: Blob) => {
    setIsTranscribing(true);
    try {
      setTranscriptionError(null);

      // Send to transcription endpoint
      const result = await transcribeAudio(copilotkit, audioBlob);

      // Insert transcribed text into input
      setInputValue((prev) => {
        const trimmedPrev = prev.trim();
        if (trimmedPrev) {
          return `${trimmedPrev} ${result.text}`;
        }
        return result.text;
      });
    } catch (error) {
      console.error("CopilotChat: Transcription failed", error);

      // Show contextual error message based on error type
      if (error instanceof TranscriptionError) {
        const { code, retryable, message } = error.info;
        switch (code) {
          case TranscriptionErrorCode.RATE_LIMITED:
            setTranscriptionError("Too many requests. Please wait a moment.");
            break;
          case TranscriptionErrorCode.AUTH_FAILED:
            setTranscriptionError("Authentication error. Please check your configuration.");
            break;
          case TranscriptionErrorCode.AUDIO_TOO_LONG:
            setTranscriptionError("Recording is too long. Please try a shorter recording.");
            break;
          case TranscriptionErrorCode.AUDIO_TOO_SHORT:
            setTranscriptionError("Recording is too short. Please try again.");
            break;
          case TranscriptionErrorCode.INVALID_AUDIO_FORMAT:
            setTranscriptionError("Audio format not supported.");
            break;
          case TranscriptionErrorCode.SERVICE_NOT_CONFIGURED:
            setTranscriptionError("Transcription service is not available.");
            break;
          case TranscriptionErrorCode.NETWORK_ERROR:
            setTranscriptionError("Network error. Please check your connection.");
            break;
          default:
            // For retryable errors, show more helpful message
            setTranscriptionError(
              retryable
                ? "Transcription failed. Please try again."
                : message
            );
        }
      } else {
        // Fallback for unexpected errors
        setTranscriptionError("Transcription failed. Please try again.");
      }
    } finally {
      setIsTranscribing(false);
    }
  }, [copilotkit]);

  // Clear transcription error after a delay
  useEffect(() => {
    if (transcriptionError) {
      const timer = setTimeout(() => {
        setTranscriptionError(null);
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [transcriptionError]);

  const mergedProps = merge(
    {
      isRunning: agent.isRunning,
      suggestions: autoSuggestions,
      onSelectSuggestion: handleSelectSuggestion,
      suggestionView: providedSuggestionView,
    },
    {
      ...restProps,
      ...(typeof providedMessageView === "string"
        ? { messageView: { className: providedMessageView } }
        : providedMessageView !== undefined
          ? { messageView: providedMessageView }
          : {}),
    },
  );

  const providedStopHandler = providedInputProps?.onStop;
  const hasMessages = agent.messages.length > 0;
  const shouldAllowStop = agent.isRunning && hasMessages;
  const effectiveStopHandler = shouldAllowStop ? (providedStopHandler ?? stopCurrentRun) : providedStopHandler;

  // Determine if transcription feature should be available
  const showTranscription = isTranscriptionEnabled && isMediaRecorderSupported;

  // Determine mode: transcribing takes priority, then transcribe mode, then default to input
  const effectiveMode: CopilotChatInputMode = isTranscribing
    ? "processing"
    : transcribeMode;

  const finalInputProps = {
    ...providedInputProps,
    onSubmitMessage: onSubmitInput,
    onStop: effectiveStopHandler,
    isRunning: agent.isRunning,
    mode: effectiveMode,
    value: inputValue,
    onChange: setInputValue,
    // Only provide transcription handlers if feature is available
    onStartTranscribe: showTranscription ? handleStartTranscribe : undefined,
    onCancelTranscribe: showTranscription ? handleCancelTranscribe : undefined,
    onFinishTranscribe: showTranscription ? handleFinishTranscribe : undefined,
    onFinishTranscribeWithAudio: showTranscription ? handleFinishTranscribeWithAudio : undefined,
  } as Partial<CopilotChatInputProps> & { onSubmitMessage: (value: string) => void };

  const finalProps = merge(mergedProps, {
    messages: agent.messages,
    inputProps: finalInputProps,
  }) as CopilotChatViewProps;

  // Always create a provider with merged values
  // This ensures priority: props > existing config > defaults
  const RenderedChatView = renderSlot(chatView, CopilotChatView, finalProps);

  return (
    <CopilotChatConfigurationProvider
      agentId={resolvedAgentId}
      threadId={resolvedThreadId}
      labels={labels}
      isModalDefaultOpen={isModalDefaultOpen}
    >
      {transcriptionError && (
        <div
          style={{
            position: "absolute",
            bottom: "100px",
            left: "50%",
            transform: "translateX(-50%)",
            backgroundColor: "#ef4444",
            color: "white",
            padding: "8px 16px",
            borderRadius: "8px",
            fontSize: "14px",
            zIndex: 50,
          }}
        >
          {transcriptionError}
        </div>
      )}
      {RenderedChatView}
    </CopilotChatConfigurationProvider>
  );
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace CopilotChat {
  export const View = CopilotChatView;
}
