// packages/vue/src/v2/components/chat/CopilotChatToolCallsView.vue
<script setup lang="ts">
import { inject, useSlots } from "vue";
import type { AssistantMessage, Message } from "@ag-ui/core";
import type { CopilotChatToolCallRenderSlotProps } from "./types";
import CopilotChatToolCallItem from "./CopilotChatToolCallItem.vue";
import SaveSnippetBeside from "./SaveSnippetBeside.vue";
import { InspectorKey } from "../../providers/keys";
import { useCopilotChatConfiguration } from "../../providers/useCopilotChatConfiguration";
import { CopilotChatDefaultLabels } from "../../providers/types";
import { IconBookmark } from "../icons";

const props = withDefaults(
  defineProps<{
    message: AssistantMessage;
    messages?: Message[];
  }>(),
  {
    messages: () => [],
  },
);

defineSlots<{
  "tool-call"?: (props: CopilotChatToolCallRenderSlotProps) => unknown;
  [key: `tool-call-${string}`]: (
    props: CopilotChatToolCallRenderSlotProps,
  ) => unknown;
}>();

type ToolCallSlotName = "tool-call" | `tool-call-${string}`;
const componentSlots = useSlots() as Record<
  ToolCallSlotName,
  (props?: unknown) => unknown
>;
function getForwardedSlotNames(): ToolCallSlotName[] {
  return Object.keys(componentSlots) as ToolCallSlotName[];
}

// A streaming tool call has truncated arguments. Do not offer to capture it
// until the JSON is complete, or the snippet holds a broken partial payload.
function hasCompleteArgs(args: string | undefined): boolean {
  const trimmed = (args ?? "").trim();
  if (!trimmed) {
    return true;
  }
  try {
    JSON.parse(trimmed);
    return true;
  } catch {
    return false;
  }
}

const inspector = inject(InspectorKey, null);
const chatConfiguration = useCopilotChatConfiguration();
const canSave = (toolCall: { function: { arguments: string } }) =>
  inspector?.isInspectorEnabled.value === true &&
  hasCompleteArgs(toolCall.function.arguments);
const saveLabel = () =>
  chatConfiguration.value?.labels.assistantMessageToolbarSaveSnippetLabel ??
  CopilotChatDefaultLabels.assistantMessageToolbarSaveSnippetLabel;

function saveToolCall(toolCall: {
  id: string;
  function: { name: string; arguments: string };
}) {
  void inspector?.saveEventSnippet({
    kind: "tool-call",
    messageId: props.message.id,
    toolCallId: toolCall.id,
    toolName: toolCall.function.name,
    argsJson: toolCall.function.arguments || "{}",
    threadId: chatConfiguration.value?.threadId,
    agentId: chatConfiguration.value?.agentId,
  });
}
</script>

<template>
  <div v-for="toolCall in message.toolCalls ?? []" :key="toolCall.id">
    <SaveSnippetBeside :enabled="canSave(toolCall)">
      <CopilotChatToolCallItem :tool-call="toolCall" :messages="messages">
        <template
          v-for="slotName in getForwardedSlotNames()"
          :key="slotName"
          #[slotName]="slotProps"
        >
          <slot :name="slotName" v-bind="slotProps ?? {}" />
        </template>
      </CopilotChatToolCallItem>
      <template #save>
        <button
          type="button"
          class="cpk:inline-flex cpk:h-8 cpk:w-8 cpk:items-center cpk:justify-center cpk:rounded-md cpk:p-0 cpk:text-[rgb(93,93,93)] cpk:hover:bg-[#E8E8E8] cpk:dark:text-[rgb(243,243,243)] cpk:dark:hover:bg-[#303030]"
          data-testid="copilot-tool-save-snippet-button"
          :aria-label="`${saveLabel()} (${chatConfiguration?.labels.assistantMessageToolbarInspectorLocalOnlyLabel ?? CopilotChatDefaultLabels.assistantMessageToolbarInspectorLocalOnlyLabel})`"
          @click="saveToolCall(toolCall)"
        >
          <IconBookmark class="cpk:size-[18px]" />
        </button>
      </template>
    </SaveSnippetBeside>
  </div>
</template>

// packages/angular/src/lib/components/chat/copilot-chat-tool-calls-view.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  input,
} from "@angular/core";

import type { AssistantMessage, Message } from "@ag-ui/core";
import { RenderToolCalls } from "../../render-tool-calls";
import { CopilotInspector } from "../../inspector";
import { CopilotChatConfiguration } from "../../chat-configuration";
import { injectChatLabels } from "../../chat-config";
import { Bookmark, CopilotIcon } from "../icons/copilot-icon";
import { CopilotChatAssistantMessageToolbarButton } from "./copilot-chat-assistant-message-buttons";
import { CopilotSaveSnippetBeside } from "./copilot-save-snippet-beside";

type AssistantToolCall = NonNullable<AssistantMessage["toolCalls"]>[number];

@Component({
  selector: "copilot-chat-tool-calls-view",
  imports: [
    RenderToolCalls,
    CopilotIcon,
    CopilotChatAssistantMessageToolbarButton,
    CopilotSaveSnippetBeside,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (toolCall of message().toolCalls ?? []; track toolCall.id) {
      <copilot-save-snippet-beside [enabled]="inspectorEnabled(toolCall)">
        <copilot-render-tool-calls
          [message]="singleToolMessage(toolCall)"
          [messages]="messages()"
          [agentId]="agentId()"
          [isLoading]="isLoading()"
        >
        </copilot-render-tool-calls>
        <button
          saveSnippet
          type="button"
          copilotChatAssistantMessageToolbarButton
          data-testid="copilot-tool-save-snippet-button"
          [title]="saveSnippetTitle()"
          (click)="saveToolSnippet(toolCall)"
        >
          <copilot-icon [img]="bookmarkIcon" [size]="18" />
        </button>
      </copilot-save-snippet-beside>
    }
  `,
})
export class CopilotChatToolCallsView {
  readonly message = input.required<AssistantMessage>();
  readonly messages = input.required<Message[]>();
  readonly agentId = input<string | undefined>();
  readonly isLoading = input<boolean>(false);

  private readonly inspector = inject(CopilotInspector, { optional: true });
  private readonly chatConfig = inject(CopilotChatConfiguration, {
    optional: true,
  });
  protected readonly labels = injectChatLabels();
  protected readonly bookmarkIcon = Bookmark;

  protected inspectorEnabled(toolCall: AssistantToolCall): boolean {
    return (
      this.inspector?.isInspectorEnabled === true &&
      hasCompleteArgs(toolCall.function.arguments)
    );
  }

  protected saveSnippetTitle(): string {
    return `${this.labels.assistantMessageToolbarSaveSnippetLabel} (${this.labels.assistantMessageToolbarInspectorLocalOnlyLabel})`;
  }

  protected singleToolMessage(toolCall: AssistantToolCall): AssistantMessage {
    return {
      ...this.message(),
      toolCalls: [toolCall],
    };
  }

  protected saveToolSnippet(toolCall: AssistantToolCall): void {
    void this.inspector?.saveEventSnippet({
      kind: "tool-call",
      messageId: this.message().id,
      toolCallId: toolCall.id,
      toolName: toolCall.function.name,
      argsJson: toolCall.function.arguments || "{}",
      threadId: this.chatConfig?.threadId(),
      agentId: this.chatConfig?.agentId(),
    });
  }
}

// A streaming tool call has truncated arguments. Do not offer to capture it
// until the JSON is complete, or the snippet holds a broken partial payload.
function hasCompleteArgs(args: string | undefined): boolean {
  const trimmed = (args ?? "").trim();
  if (!trimmed) {
    return true;
  }
  try {
    JSON.parse(trimmed);
    return true;
  } catch {
    return false;
  }
}
