// packages/react-core/src/v2/components/chat/CopilotThreadsDrawer.tsx
"use client";

import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  defineCopilotKitThreadsDrawer,
  COPILOTKIT_THREADS_DRAWER_TAG,
} from "@copilotkit/web-components/threads-drawer";
import type {
  CopilotKitThreadsDrawer as CopilotKitThreadsDrawerElement,
  DrawerThread,
  ThreadSelectedDetail,
  ArchiveDetail,
  UnarchiveDetail,
  DeleteDetail,
  OpenChangeDetail,
  RetryDetail,
} from "@copilotkit/web-components/threads-drawer";
// TODO(ENT-1051): import `CollapseChangeDetail` from
// "@copilotkit/web-components/threads-drawer" once the parallel element PR that
// adds the collapse feature (property `collapsible` + event `collapse-change`)
// lands and is published; declared locally here because the built element types
// in this worktree predate it.
type CollapseChangeDetail = { collapsed: boolean };
import { DEFAULT_AGENT_ID } from "@copilotkit/shared";
import { useThreads } from "../../hooks/use-threads";
import type { Thread } from "../../hooks/use-threads";
import { useLicenseContext } from "../../providers/CopilotKitProvider";
import { useCopilotChatConfiguration } from "../../providers/CopilotChatConfigurationProvider";

/**
 * Per-row content render function. Receives a thread and returns the React
 * node to project into the element's `slot="row:{id}"`. Returning `null`
 * (or omitting the prop) falls back to the element's built-in row name.
 */
export type CopilotThreadsDrawerRowRenderer = (
  thread: Thread,
) => React.ReactNode;

/**
 * Props for {@link CopilotThreadsDrawer}.
 *
 * The drawer is a thin controller around the framework-agnostic
 * `<copilotkit-threads-drawer>` custom element. It feeds the element domain data
 * (threads/loading/error from {@link useThreads}, the active thread from the
 * chat configuration) and routes the element's outbound DOM events back into
 * core thread operations and chat-configuration changes.
 */
export interface CopilotThreadsDrawerProps {
  /**
   * The agent whose threads to list and manage. Defaults to the agent of the
   * surrounding chat configuration, or the platform default when none is set.
   */
  agentId?: string;
  /**
   * Optional escape-hatch called when the user picks a thread row. The wrapper
   * additionally focuses the chat input. When omitted, the wrapper drives the
   * surrounding chat configuration directly (`setActiveThreadId`), so a bare
   * `<CopilotThreadsDrawer>` switches the rendered thread with no host wiring. Provide
   * this only to take control of the active thread yourself (e.g. a v1
   * `setThreadId`); when provided it is preferred over the provider.
   */
  onThreadSelect?: (threadId: string) => void;
  /**
   * Optional escape-hatch called when the user starts a new thread (the
   * element's "+ New" button). The wrapper always resets the core thread store
   * to a fresh, non-explicit client-side thread (`startNewThread`). When this
   * is omitted, the wrapper also resets the surrounding chat configuration to a
   * fresh non-explicit thread (`startNewThread`) so the welcome screen shows
   * with no host wiring. Provide this only to clear your own active thread;
   * when provided it is preferred over the provider.
   */
  onNewThread?: () => void;
  /** Called when the Upgrade CTA is clicked. */
  onLicensed?: () => void;
  /**
   * Destination the locked view's Upgrade CTA opens in a new tab. Defaults to
   * the element's built-in CopilotKit Intelligence docs URL when omitted. Set
   * to an empty string to suppress the default navigation and handle the click
   * yourself via `onLicensed`.
   */
  licenseUrl?: string;
  /**
   * Optional per-row content. Rendered as light-DOM children with
   * `slot="row:{id}"` so the element projects them in place of the default
   * row name. Return `null` for a given row to keep the element's default.
   */
  renderRow?: CopilotThreadsDrawerRowRenderer;
  /**
   * Accessible + default-header label for the drawer region. Sets the custom
   * element's `aria-label` and the default header text (shown when no
   * `slot="header"` content is projected). Defaults to the element's built-in
   * `"Threads"` when omitted.
   */
  label?: string;
  /**
   * Heading for the "Recent Conversations" section above the thread list. Sets
   * the custom element's `recent-label` attribute. Defaults to the element's
   * built-in `"Recent Conversations"` when omitted.
   */
  recentLabel?: string;
  /**
   * Whether the drawer offers a collapse toggle. Sets the custom element's
   * `collapsible` PROPERTY. When `false`, the drawer has no collapse toggle and
   * is always expanded. Defaults to the element's built-in `true` when omitted.
   */
  collapsible?: boolean;
  /**
   * Called when the drawer's collapsed state changes (via the element's collapse
   * toggle), with the new collapsed state. Mirrors the element's
   * `collapse-change` event.
   */
  onCollapseChange?: (collapsed: boolean) => void;
  /**
   * Page size for thread pagination. When set, threads are fetched in pages of
   * this size and the drawer shows a "Load more" control while more remain.
   * When omitted, the full list loads at once and no pagination control shows.
   */
  limit?: number;
  /**
   * `data-testid` set on the underlying custom element (handy in tests and for
   * targeting from a host page). Defaults to `"copilot-threads-drawer"`.
   */
  "data-testid"?: string;
}

/**
 * Maps a {@link Thread} from {@link useThreads} to the element's
 * {@link DrawerThread} view shape. The shapes are structurally compatible; this
 * narrows to exactly the fields the element renders so the element never sees
 * platform-internal fields.
 */
function toDrawerThread(thread: Thread): DrawerThread {
  return {
    id: thread.id,
    name: thread.name,
    archived: thread.archived,
    createdAt: thread.createdAt,
    updatedAt: thread.updatedAt,
    ...(thread.lastRunAt !== undefined ? { lastRunAt: thread.lastRunAt } : {}),
  };
}

/** The chat input textarea's documented `data-testid`. */
const CHAT_INPUT_TESTID = "copilot-chat-textarea";
/** The chat view container's documented `data-testid`. */
const CHAT_CONTAINER_TESTID = "copilot-chat";

/**
 * Returns the chat input element for focus-return after a thread is selected.
 *
 * Best-effort and SCOPED: walks up from the drawer element looking for an
 * ancestor that contains a chat-view container (`data-testid="copilot-chat"`),
 * then returns the chat input within that subtree. This avoids focusing the
 * wrong composer on a page hosting more than one chat (multi-chat dashboards),
 * where a document-global lookup would grab whichever input appears first in
 * DOM order rather than the one this drawer drives.
 *
 * Falls back to a document-global lookup when no scoping ancestor is found
 * (e.g. the drawer and chat share no common container, or headless usage),
 * and returns `null` when there is no chat input at all.
 *
 * @param origin - The drawer element to scope the search from.
 */
function findChatInput(origin: Element | null): HTMLElement | null {
  if (typeof document === "undefined") return null;

  // The drawer lives inside (or alongside) its own chat-view container. Find the
  // nearest such container with `closest` and scope the input lookup to it, so a
  // page hosting multiple chats focuses THIS drawer's composer rather than
  // whichever input appears first in DOM order. Walking up by "ancestor that
  // *contains* a chat" would instead climb past the drawer's own container (which
  // holds no nested chat) to the shared root and grab the first chat on the page.
  const container = origin?.closest?.(
    `[data-testid="${CHAT_CONTAINER_TESTID}"]`,
  );
  if (container) {
    const scoped = container.querySelector<HTMLElement>(
      `[data-testid="${CHAT_INPUT_TESTID}"]`,
    );
    if (scoped) return scoped;
  }

  // No scoping container found (drawer and chat share no common container, or
  // headless usage): fall back to a document-global lookup.
  return document.querySelector<HTMLElement>(
    `[data-testid="${CHAT_INPUT_TESTID}"]`,
  );
}

/**
 * React wrapper for the shadow-DOM `<copilotkit-threads-drawer>` threads drawer.
 *
 * Responsibilities:
 * - Registers the custom element on the client (SSR-safe; nothing renders
 *   during prerender to avoid hydration mismatch).
 * - Feeds the element domain data: `threads`, `loading`, `error`,
 *   `activeThreadId`, `licensed`, fetch-more state.
 * - Routes the element's outbound events to core thread operations
 *   ({@link useThreads}) and chat-configuration changes.
 * - Registers with the surrounding chat configuration so the header
 *   thread-list launcher appears, and binds the element `open` state to the
 *   configuration's `drawerOpen`.
 *
 * License gating is two-pronged: the locked view shows when no license is configured
 * (the runtime reported no license status) OR the `threads` feature is
 * explicitly unlicensed. While unlicensed, the thread fetch is skipped entirely
 * so an unlicensed drawer issues no network requests.
 *
 * Thread switching needs no host wiring: when `onThreadSelect`/`onNewThread`
 * are omitted, the wrapper drives the surrounding chat configuration directly
 * ({@link CopilotChatConfigurationValue.setActiveThreadId} /
 * {@link CopilotChatConfigurationValue.startNewThread}), so a bare drawer
 * connects to the picked thread and shows the welcome screen on "+ New". Pass
 * the callbacks only to take control yourself.
 *
 * @example
 * ```tsx
 * // Callback-free: the drawer drives the chat configuration itself.
 * <CopilotKitProvider runtimeUrl="/api/copilotkit" publicLicenseKey="ck_pub_...">
 *   <CopilotChat />
 *   <CopilotThreadsDrawer />
 * </CopilotKitProvider>
 * ```
 */
export function CopilotThreadsDrawer({
  agentId,
  onThreadSelect,
  onNewThread,
  onLicensed,
  licenseUrl,
  renderRow,
  label,
  recentLabel,
  collapsible,
  onCollapseChange,
  limit,
  "data-testid": dataTestId = "copilot-threads-drawer",
}: CopilotThreadsDrawerProps): React.ReactElement | null {
  const configuration = useCopilotChatConfiguration();
  const { status, checkFeature } = useLicenseContext();

  // Two-pronged license gate. `checkFeature` fails OPEN (returns true) when no
  // license is configured, so it cannot by itself detect the no-license case.
  // We therefore also require a positive license-present signal from the
  // runtime-reported status. Only a "valid" or "expiring" license is treated
  // as present; a resolved "none"/"expired"/"invalid" status gates the drawer
  // to the locked view.
  const licensePresent = status === "valid" || status === "expiring";
  const featureLicensed = checkFeature("threads");
  const licensed = licensePresent && featureLicensed;

  // The runtime reports license status asynchronously: `status` is null until
  // the first /info response lands. Treat that pending window as "not yet
  // unlicensed" — show the loading state, never the locked view — so a licensed
  // drawer doesn't flash the upgrade CTA before its license resolves (and never
  // strands the CTA on screen when the status is slow or fails to arrive). Only
  // a RESOLVED-negative status (`none`/`expired`/`invalid`, or a present license
  // missing the `threads` feature) surfaces the locked view.
  const licensePending = status === null;

  const resolvedAgentId = agentId ?? configuration?.agentId ?? DEFAULT_AGENT_ID;
  const activeThreadId = configuration?.threadId ?? null;

  // While unlicensed, skip the thread fetch entirely: the element shows only
  // its locked view and no `/threads` request is issued.
  const {
    threads,
    isLoading,
    listError,
    fetchMoreError,
    hasMoreThreads,
    isFetchingMoreThreads,
    archiveThread,
    unarchiveThread,
    deleteThread,
    fetchMoreThreads,
    refetchThreads,
    startNewThread,
  } = useThreads({
    agentId: resolvedAgentId,
    includeArchived: true,
    enabled: licensed,
    ...(limit !== undefined ? { limit } : {}),
  });

  const drawerThreads = useMemo(() => threads.map(toDrawerThread), [threads]);

  const elementRef = useRef<CopilotKitThreadsDrawerElement | null>(null);

  // Register the custom element on the client only. `customElements` is absent
  // during SSR/prerender; gating the render below on `mounted` keeps the server
  // output empty so there is no hydration mismatch or layout shift.
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    defineCopilotKitThreadsDrawer();
    setMounted(true);
  }, []);

  // Announce presence to the surrounding chat configuration so the header
  // launcher renders; de-register on unmount. Depend on the stable
  // `registerDrawer` callback, NOT the whole `configuration` object — the
  // object's identity changes on every drawer/modal/label update, which would
  // otherwise churn register/de-register each render and momentarily drop
  // `drawerRegistered` (flickering the header launcher).
  const registerDrawer = configuration?.registerDrawer;
  useEffect(() => {
    if (!registerDrawer) return;
    return registerDrawer();
  }, [registerDrawer]);

  // Drive the chat configuration's drawerOpen from the element's open-change
  // event, and reflect drawerOpen back onto the element below.
  //
  // Provider-less fallback: without a surrounding chat configuration there is no
  // shared open-state to bind to, so the wrapper keeps its own local open-state.
  // It starts CLOSED — matching the provider's own `ownDrawerOpen` default of
  // `false` — so a bare `<CopilotThreadsDrawer>` does not render stuck-open and the
  // element's open-change events still toggle it.
  const [localDrawerOpen, setLocalDrawerOpen] = useState(false);
  const drawerOpen = configuration ? configuration.drawerOpen : localDrawerOpen;
  const setDrawerOpen = configuration
    ? configuration.setDrawerOpen
    : setLocalDrawerOpen;

  // --- Event handlers (stable via refs to the latest closures) -------------
  // The element is imperatively wired with addEventListener once; we keep the
  // latest handler implementations in a ref so listeners need not be re-bound
  // every render (which would churn on each thread/loading change).

  // Prefer the host callbacks when provided; otherwise drive the surrounding
  // chat configuration directly so a bare `<CopilotThreadsDrawer>` works callback-free.
  const setActiveThreadId = configuration?.setActiveThreadId;
  const startNewThreadConfig = configuration?.startNewThread;

  const handleThreadSelected = useCallback(
    (threadId: string) => {
      if (onThreadSelect) {
        onThreadSelect(threadId);
      } else {
        // Selecting a row is an explicit, caller-driven thread choice: connect
        // the chat to that backend thread (suppresses the welcome screen).
        setActiveThreadId?.(threadId, { explicit: true });
      }
      // Return focus to the chat input so keyboard users land in the composer.
      // Scope the lookup to this drawer's own chat (not document-global).
      findChatInput(elementRef.current)?.focus();
    },
    [onThreadSelect, setActiveThreadId],
  );

  const handleNewThread = useCallback(() => {
    // Reset the core thread store to a fresh, non-explicit client-side thread
    // (clears any stale error so the welcome screen can render cleanly).
    startNewThread();
    if (onNewThread) {
      onNewThread();
    } else {
      // No host callback: reset the surrounding chat configuration to a fresh,
      // non-explicit thread so the welcome screen shows with no host wiring.
      startNewThreadConfig?.();
    }
  }, [startNewThread, onNewThread, startNewThreadConfig]);

  const handleArchive = useCallback(
    (threadId: string) => {
      void archiveThread(threadId).catch((err) => {
        console.error("CopilotThreadsDrawer: archiveThread failed", err);
      });
    },
    [archiveThread],
  );

  const handleUnarchive = useCallback(
    (threadId: string) => {
      void unarchiveThread(threadId).catch((err) => {
        console.error("CopilotThreadsDrawer: unarchiveThread failed", err);
      });
    },
    [unarchiveThread],
  );

  const handleDelete = useCallback(
    (threadId: string) => {
      // Deleting the active thread resets to a fresh, non-explicit thread so the
      // user is not stranded on a now-gone conversation. Archiving the active
      // thread keeps the user viewing it.
      const isActive = threadId === activeThreadId;
      // The core thread store performs the optimistic removal (and rollback on
      // failure) in its own reducer, so the wrapper holds no removal bookkeeping
      // of its own — it simply renders the threads the store hands it.
      void deleteThread(threadId)
        .then(() => {
          if (isActive) {
            startNewThread();
            if (onNewThread) {
              onNewThread();
            } else {
              startNewThreadConfig?.();
            }
          }
        })
        .catch((err) => {
          console.error("CopilotThreadsDrawer: deleteThread failed", err);
        });
    },
    [
      deleteThread,
      activeThreadId,
      startNewThread,
      onNewThread,
      startNewThreadConfig,
    ],
  );

  const handleFilterChange = useCallback(() => {
    // The element owns the Active/All filter; on change we refetch so the list
    // reflects the server.
    refetchThreads();
  }, [refetchThreads]);

  const handleRetry = useCallback(
    (scope: RetryDetail["scope"]) => {
      if (scope === "fetch-more") {
        fetchMoreThreads();
      } else {
        refetchThreads();
      }
    },
    [fetchMoreThreads, refetchThreads],
  );

  const handleOpenChange = useCallback(
    (open: boolean) => {
      setDrawerOpen(open);
    },
    [setDrawerOpen],
  );

  const handleLicensed = useCallback(() => {
    onLicensed?.();
  }, [onLicensed]);

  const handleLoadMore = useCallback(() => {
    // Advance pagination. No-op when there is no next page; the element only
    // surfaces the "Load more" control while `hasMore` is true.
    fetchMoreThreads();
  }, [fetchMoreThreads]);

  const handleCollapseChange = useCallback(
    (collapsed: boolean) => {
      onCollapseChange?.(collapsed);
    },
    [onCollapseChange],
  );

  // Keep a ref to the live handlers so the addEventListener effect can stay
  // stable (bind once) while still calling the freshest closures.
  const handlersRef = useRef({
    handleThreadSelected,
    handleNewThread,
    handleArchive,
    handleUnarchive,
    handleDelete,
    handleFilterChange,
    handleRetry,
    handleOpenChange,
    handleLicensed,
    handleLoadMore,
    handleCollapseChange,
  });
  handlersRef.current = {
    handleThreadSelected,
    handleNewThread,
    handleArchive,
    handleUnarchive,
    handleDelete,
    handleFilterChange,
    handleRetry,
    handleOpenChange,
    handleLicensed,
    handleLoadMore,
    handleCollapseChange,
  };

  // Bind the outbound DOM events once the element exists. Listeners are
  // bound a single time and cleaned up on unmount; they dispatch through the
  // handlers ref so they always invoke the latest closures.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;

    const onThreadSelected = (event: Event) => {
      const detail = (event as CustomEvent<ThreadSelectedDetail>).detail;
      handlersRef.current.handleThreadSelected(detail.threadId);
    };
    const onNewThreadEvent = () => handlersRef.current.handleNewThread();
    const onArchive = (event: Event) => {
      const detail = (event as CustomEvent<ArchiveDetail>).detail;
      handlersRef.current.handleArchive(detail.threadId);
    };
    const onUnarchive = (event: Event) => {
      const detail = (event as CustomEvent<UnarchiveDetail>).detail;
      handlersRef.current.handleUnarchive(detail.threadId);
    };
    const onDelete = (event: Event) => {
      const detail = (event as CustomEvent<DeleteDetail>).detail;
      handlersRef.current.handleDelete(detail.threadId);
    };
    const onFilterChange = (_event: Event) => {
      handlersRef.current.handleFilterChange();
    };
    const onOpenChangeEvent = (event: Event) => {
      const detail = (event as CustomEvent<OpenChangeDetail>).detail;
      handlersRef.current.handleOpenChange(detail.open);
    };
    const onRetry = (event: Event) => {
      const detail = (event as CustomEvent<RetryDetail>).detail;
      handlersRef.current.handleRetry(detail.scope);
    };
    const onLicensedEvent = () => handlersRef.current.handleLicensed();
    const onLoadMore = () => handlersRef.current.handleLoadMore();
    const onCollapseChangeEvent = (event: Event) => {
      const detail = (event as CustomEvent<CollapseChangeDetail>).detail;
      handlersRef.current.handleCollapseChange(detail.collapsed);
    };

    el.addEventListener("thread-selected", onThreadSelected);
    el.addEventListener("new-thread", onNewThreadEvent);
    el.addEventListener("archive", onArchive);
    el.addEventListener("unarchive", onUnarchive);
    el.addEventListener("delete", onDelete);
    el.addEventListener("filter-change", onFilterChange);
    el.addEventListener("open-change", onOpenChangeEvent);
    el.addEventListener("retry", onRetry);
    el.addEventListener("licensed", onLicensedEvent);
    el.addEventListener("load-more", onLoadMore);
    el.addEventListener("collapse-change", onCollapseChangeEvent);

    return () => {
      el.removeEventListener("thread-selected", onThreadSelected);
      el.removeEventListener("new-thread", onNewThreadEvent);
      el.removeEventListener("archive", onArchive);
      el.removeEventListener("unarchive", onUnarchive);
      el.removeEventListener("delete", onDelete);
      el.removeEventListener("filter-change", onFilterChange);
      el.removeEventListener("open-change", onOpenChangeEvent);
      el.removeEventListener("retry", onRetry);
      el.removeEventListener("licensed", onLicensedEvent);
      el.removeEventListener("load-more", onLoadMore);
      el.removeEventListener("collapse-change", onCollapseChangeEvent);
    };
    // Re-bind only after the first client mount (deps: [mounted]); the element
    // ref is stable thereafter.
  }, [mounted]);

  // Assign object/array/boolean PROPERTIES imperatively. React would otherwise
  // set these as string attributes, which a custom element cannot accept for
  // arrays/objects. Setting them as instance properties is the correct interop.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    el.threads = drawerThreads;
  }, [drawerThreads, mounted]);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    // While the license is still resolving, force the loading state so the
    // element shows its spinner instead of an empty/unlicensed body.
    el.loading = isLoading || licensePending;
    // Only genuine list-load/mutation errors reach the end user. Developer/
    // config errors (missing runtime URL, runtime without thread endpoints) are
    // excluded via `listError` so they never leak into the drawer's error UI.
    el.error = listError ? listError.message : null;
    el.activeThreadId = activeThreadId;
    // Pending counts as licensed for rendering: `_renderBody` shows the locked view
    // only when `licensed` is false, so keeping it true until the status
    // resolves prevents the locked view from flashing (or sticking) mid-resolution.
    el.licensed = licensed || licensePending;
    el.hasMore = hasMoreThreads;
    el.fetchingMore = isFetchingMoreThreads;
    // Dedicated fetch-more error channel: drives the element's inline
    // "couldn't load more — retry" panel without disturbing the loaded list or
    // the initial-list `error`. The `retry{scope:"fetch-more"}` handler
    // becomes reachable once this panel renders.
    el.fetchMoreError = fetchMoreError ? fetchMoreError.message : null;
  }, [
    isLoading,
    listError,
    fetchMoreError,
    activeThreadId,
    licensed,
    licensePending,
    hasMoreThreads,
    isFetchingMoreThreads,
    mounted,
  ]);

  // Bind the element's controlled `open` to the chat configuration's
  // drawerOpen, so the header launcher and the element stay in sync.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    el.open = drawerOpen;
  }, [drawerOpen, mounted]);

  // Mirror the optional `label` onto the element (its accessible + default
  // header text). Leave the element's built-in default ("Threads") in place
  // when the prop is omitted, rather than clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (label !== undefined) el.label = label;
  }, [label, mounted]);

  // Mirror the optional `licenseUrl` onto the element (the locked view's
  // Upgrade CTA destination). Leave the element's built-in default in place
  // when the prop is omitted, rather than clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (licenseUrl !== undefined) el.licenseUrl = licenseUrl;
  }, [licenseUrl, mounted]);

  // Mirror the optional `collapsible` onto the element as a PROPERTY (a
  // default-true boolean, exactly like `licensed` — a string attribute cannot
  // represent it since any non-empty value is truthy). Leave the element's
  // built-in default (`true`) in place when the prop is omitted, rather than
  // clobbering it with undefined.
  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (collapsible !== undefined) {
      // TODO(ENT-1051): drop the intersection cast once the published element
      // type declares `collapsible` (see the local CollapseChangeDetail note).
      (
        el as CopilotKitThreadsDrawerElement & { collapsible: boolean }
      ).collapsible = collapsible;
    }
  }, [collapsible, mounted]);

  // Per-row light-DOM children projected via `slot="row:{id}"`.
  const rowChildren = useMemo(() => {
    if (!renderRow) return null;
    return drawerThreads.map((drawerThread) => {
      const fullThread = threads.find((t) => t.id === drawerThread.id);
      if (!fullThread) return null;
      const content = renderRow(fullThread);
      if (content === null || content === undefined) return null;
      return (
        <div key={drawerThread.id} slot={`row:${drawerThread.id}`}>
          {content}
        </div>
      );
    });
  }, [renderRow, drawerThreads, threads]);

  // SSR / pre-mount: render nothing so the server output matches the initial
  // client render (the element is not yet registered), avoiding hydration
  // mismatch and layout shift.
  if (!mounted) return null;

  return React.createElement(
    COPILOTKIT_THREADS_DRAWER_TAG,
    {
      ref: elementRef,
      "data-testid": dataTestId,
      // Pass the section heading label as an attribute; omit it entirely when
      // unset so the element keeps its built-in default rather than receiving
      // an `undefined` that would clobber it.
      ...(recentLabel !== undefined ? { "recent-label": recentLabel } : {}),
    },
    rowChildren,
  );
}

CopilotThreadsDrawer.displayName = "CopilotThreadsDrawer";

export default CopilotThreadsDrawer;

// packages/angular/src/lib/components/chat/copilot-threads-drawer.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  Directive,
  ElementRef,
  EventEmitter,
  Output,
  TemplateRef,
  computed,
  contentChild,
  effect,
  inject,
  input,
  signal,
  viewChild,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import {
  DEFAULT_AGENT_ID,
  createLicenseContextValue,
} from "@copilotkit/shared";
import { defineCopilotKitThreadsDrawer } from "@copilotkit/web-components/threads-drawer";
import type {
  ArchiveDetail,
  DeleteDetail,
  DrawerThread,
  OpenChangeDetail,
  RetryDetail,
  ThreadSelectedDetail,
  UnarchiveDetail,
  CopilotKitThreadsDrawer as CopilotKitThreadsDrawerElement,
} from "@copilotkit/web-components/threads-drawer";
// TODO(ENT-1051): import `CollapseChangeDetail` from
// "@copilotkit/web-components/threads-drawer" once the parallel element PR that
// adds the collapse feature (property `collapsible` + event `collapse-change`)
// lands and is published; declared locally here because the built element types
// in this worktree predate it.
type CollapseChangeDetail = { collapsed: boolean };
import { COPILOT_CHAT_CONFIGURATION } from "../../chat-configuration";
import { CopilotKit } from "../../copilotkit";
import { injectThreads } from "../../threads";
import type { Thread } from "../../threads";

/**
 * Maps a {@link Thread} from the platform store onto the minimal
 * {@link DrawerThread} shape the `<copilotkit-threads-drawer>` element accepts.
 *
 * `lastRunAt` is spread conditionally so the key is absent (rather than
 * `undefined`) when the source thread has never been run — matching the
 * element's optional typing and avoiding spurious property pollution.
 */
function toDrawerThread(thread: Thread): DrawerThread {
  return {
    id: thread.id,
    name: thread.name,
    archived: thread.archived,
    createdAt: thread.createdAt,
    updatedAt: thread.updatedAt,
    ...(thread.lastRunAt !== undefined ? { lastRunAt: thread.lastRunAt } : {}),
  };
}

/**
 * The Angular chat view container's element selector. Used to scope the
 * focus-return lookup so a multi-chat page focuses THIS drawer's composer.
 */
const CHAT_CONTAINER_SELECTOR = "copilot-chat-view";
/**
 * The Angular chat input's element selector (`<textarea copilotChatTextarea>`).
 * Note: this is the Angular chat input, NOT React's `copilot-chat-textarea` or
 * Vue's `copilot-chat-input-textarea` `data-testid` — the Angular chat
 * components identify by element/attribute selector rather than `data-testid`.
 */
const CHAT_INPUT_SELECTOR = "textarea[copilotChatTextarea]";

/**
 * Returns the chat input element for focus-return after a thread is selected.
 *
 * Best-effort and SCOPED: walks up from the drawer element looking for an
 * ancestor chat-view container ({@link CHAT_CONTAINER_SELECTOR}), then returns
 * the chat input ({@link CHAT_INPUT_SELECTOR}) within that subtree. This avoids
 * focusing the wrong composer on a page hosting more than one chat, where a
 * document-global lookup would grab whichever input appears first in DOM order.
 *
 * Falls back to a document-global lookup when no scoping ancestor is found
 * (e.g. the drawer and chat share no common container, or headless usage), and
 * returns `null` when there is no chat input at all. Mirrors the React and Vue
 * wrappers' `findChatInput`, scoped to the Angular chat selectors.
 *
 * @param origin - The drawer element to scope the search from.
 */
function findChatInput(origin: Element | null): HTMLElement | null {
  if (typeof document === "undefined") return null;
  const container = origin?.closest?.(CHAT_CONTAINER_SELECTOR);
  if (container) {
    const scoped = container.querySelector<HTMLElement>(CHAT_INPUT_SELECTOR);
    if (scoped) return scoped;
  }
  return document.querySelector<HTMLElement>(CHAT_INPUT_SELECTOR);
}

/**
 * Structural directive that captures a per-row template for projection into
 * the `<copilotkit-threads-drawer>` element as light-DOM children with
 * `slot="row:{id}"`.
 *
 * Apply it to an `<ng-template>` that is a direct child of `<copilot-threads-drawer>`.
 * The implicit context variable (`let-t`) receives the full {@link Thread}
 * record for that row.
 *
 * @example
 * ```html
 * <copilot-threads-drawer>
 *   <ng-template copilotThreadsDrawerRow let-t>
 *     <span>{{ t.name }}</span>
 *   </ng-template>
 * </copilot-threads-drawer>
 * ```
 */
@Directive({ selector: "[copilotThreadsDrawerRow]", standalone: true })
export class CopilotThreadsDrawerRow {
  /** The captured template reference for the per-row content. */
  readonly template = inject(TemplateRef);
}

/**
 * Angular wrapper around the `<copilotkit-threads-drawer>` Lit web component.
 *
 * Registers the custom element on construction (idempotent; SSR-guarded
 * internally by {@link defineCopilotKitThreadsDrawer}) and projects it into the DOM
 * via the `CUSTOM_ELEMENTS_SCHEMA`-enabled template.
 *
 * Thread list state is fetched from CopilotKit Intelligence via
 * {@link injectThreads} and pushed onto the element's JS properties via an
 * `effect`, following the imperative property-assignment pattern used elsewhere
 * in this package (see `CopilotA2UIActivityRenderer`).
 *
 * DOM events emitted by the element are routed back to the chat configuration
 * and thread mutation methods via declarative Angular event bindings.
 *
 * @example
 * ```html
 * <copilot-threads-drawer data-testid="my-drawer" />
 * ```
 */
@Component({
  selector: "copilot-threads-drawer",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [NgTemplateOutlet],
  template: `
    <copilotkit-threads-drawer
      #drawer
      [attr.data-testid]="dataTestId()"
      [attr.recent-label]="recentLabel() ?? null"
      (thread-selected)="onThreadSelected($event)"
      (new-thread)="onNewThread()"
      (archive)="onArchive($event)"
      (unarchive)="onUnarchive($event)"
      (delete)="onDelete($event)"
      (filter-change)="onFilterChange()"
      (collapse-change)="onCollapseChange($event)"
      (retry)="onRetry($event)"
      (load-more)="onLoadMore()"
      (open-change)="onOpenChange($event)"
      (licensed)="onLicensed()"
      ><ng-content></ng-content>
      @if (rowDirective(); as row) {
        @for (t of threads.threads(); track t.id) {
          <div [attr.slot]="'row:' + t.id">
            <ng-container
              [ngTemplateOutlet]="row.template"
              [ngTemplateOutletContext]="{ $implicit: t }"
            ></ng-container>
          </div>
        }
      }
    </copilotkit-threads-drawer>
  `,
})
export class CopilotThreadsDrawer {
  /**
   * Optional agent id whose threads this drawer lists/manages. Scopes the
   * {@link injectThreads} store (via the resolved-agent precedence: this input
   * → ambient config's `agentId` → {@link DEFAULT_AGENT_ID}). NOT forwarded to
   * the element (the element has no `agentId` property).
   */
  readonly agentId = input<string | undefined>();

  /**
   * Value applied as the `data-testid` attribute on the inner
   * `<copilotkit-threads-drawer>` element. Defaults to `"copilot-threads-drawer"`.
   */
  readonly dataTestId = input<string>("copilot-threads-drawer", {
    alias: "data-testid",
  });

  /**
   * Optional accessible/region + default-header label forwarded to the element's
   * `label` property; defaults to the element's own `"Threads"` when unset.
   */
  readonly label = input<string | undefined>();

  /**
   * Optional heading for the "Recent Conversations" section, forwarded to the
   * element's `recent-label` attribute; defaults to the element's own
   * `"Recent Conversations"` when unset.
   */
  readonly recentLabel = input<string | undefined>();

  /**
   * Whether the drawer offers a collapse toggle. Pushed onto the element's
   * `collapsible` PROPERTY (a default-true boolean, exactly like `licensed` — a
   * string attribute cannot represent it since any non-empty value is truthy).
   * When `false`, the drawer has no collapse toggle and is always expanded.
   * Defaults to the element's own `true` when unset.
   */
  readonly collapsible = input<boolean | undefined>();

  /**
   * Emits the new collapsed state whenever the drawer's collapsed state changes
   * (mirrors the element's `collapse-change` event).
   */
  @Output() readonly collapseChange = new EventEmitter<boolean>();

  /**
   * Optional host override for the thread-select action.
   *
   * When provided, this callback is invoked instead of driving
   * `config.setActiveThreadId`. Bound via `[onThreadSelect]="fn"`.
   */
  readonly threadSelectHandler = input<
    ((threadId: string) => void) | undefined
  >(undefined, {
    alias: "onThreadSelect",
  });

  /**
   * Optional host override for the new-thread action.
   *
   * When provided, this callback is invoked instead of driving
   * `config.startNewThread`. The core `threads.startNewThread()` reset is
   * always called regardless. Bound via `[onNewThread]="fn"`.
   */
  readonly newThreadHandler = input<(() => void) | undefined>(undefined, {
    alias: "onNewThread",
  });

  /**
   * Page size for thread pagination. When set, threads load in pages of this
   * size and the element shows a "Load more" control while more remain. When
   * unset, the full list loads at once and no pagination control shows.
   */
  readonly limit = input<number | undefined>();

  /**
   * Destination the locked view's Upgrade CTA opens in a new tab. Forwarded to
   * the element's `licenseUrl` property; defaults to the element's built-in
   * CopilotKit Intelligence docs URL when unset. Set to an empty string to
   * suppress the default navigation and handle the click via `onLicensed`.
   */
  readonly licenseUrl = input<string | undefined>();

  /**
   * Optional host hook fired when the locked view's Upgrade CTA is clicked. The
   * element still performs its default navigation unless `licenseUrl` is blank;
   * use this for telemetry or to drive your own upgrade flow. Bound via
   * `[onLicensed]="fn"`.
   */
  readonly licensedHandler = input<(() => void) | undefined>(undefined, {
    alias: "onLicensed",
  });

  private readonly config = inject(COPILOT_CHAT_CONFIGURATION, {
    optional: true,
  });

  private readonly copilotkit = inject(CopilotKit);

  private readonly drawerRef = viewChild<
    unknown,
    ElementRef<CopilotKitThreadsDrawerElement>
  >("drawer", {
    read: ElementRef,
  });

  /**
   * Optional per-row template directive projected as a direct child of this
   * component. When present, a `<div slot="row:{id}">` is rendered inside the
   * `<copilotkit-threads-drawer>` element for each thread, allowing the host to inject
   * custom light-DOM content into each row slot.
   */
  protected readonly rowDirective = contentChild(CopilotThreadsDrawerRow);

  /**
   * The resolved agent id for the threads store. Precedence:
   * 1. `agentId` input prop.
   * 2. Ambient `CopilotChatConfiguration.agentId`.
   * 3. {@link DEFAULT_AGENT_ID}.
   */
  protected readonly resolvedAgentId = computed(
    () => this.agentId() ?? this.config?.agentId() ?? DEFAULT_AGENT_ID,
  );

  /**
   * Normalized license context derived from the core's runtime-reported status,
   * via the same `@copilotkit/shared` helper the React provider uses.
   */
  private readonly licenseContext = computed(() =>
    createLicenseContextValue(this.copilotkit.licenseStatus()),
  );

  /**
   * Two-pronged license gate, mirroring the React wrapper. `checkFeature` fails
   * OPEN (returns true) when no license is configured, so it cannot by itself
   * detect the no-license case; we therefore also require a positive
   * license-present signal. Only a resolved `valid`/`expiring` status counts as
   * present — a resolved `none`/`expired`/`invalid` gates the drawer to the
   * locked view.
   */
  protected readonly licensed = computed(() => {
    const ctx = this.licenseContext();
    const licensePresent = ctx.status === "valid" || ctx.status === "expiring";
    return licensePresent && ctx.checkFeature("threads");
  });

  /**
   * Whether the runtime has not yet reported a license status. The status is
   * `null` until the first `/info` response lands; treat that window as
   * "not yet unlicensed" — show the loading state, never the locked view — so a
   * licensed drawer never flashes (or strands) the Upgrade CTA mid-resolution.
   */
  protected readonly licensePending = computed(
    () => this.licenseContext().status === null,
  );

  /** Live thread list from CopilotKit Intelligence for the resolved agent. */
  protected readonly threads = injectThreads({
    agentId: this.resolvedAgentId,
    includeArchived: true,
    limit: this.limit,
    // While unlicensed, skip the thread fetch entirely: the element shows only
    // its locked view and no `/threads` request is issued.
    enabled: this.licensed,
  });

  /** Thread records mapped to the element's {@link DrawerThread} shape. */
  protected readonly drawerThreads = computed(() =>
    this.threads.threads().map(toDrawerThread),
  );

  /**
   * User-facing error message from the filtered list error signal, or `null`
   * when there is no error. Uses `listError` (not `error`) so developer/config
   * errors (missing runtime URL, runtime without thread endpoints) are excluded
   * and never displayed to end users.
   */
  protected readonly errorMessage = computed(
    () => this.threads.listError()?.message ?? null,
  );

  /**
   * The currently-active thread id, sourced from the ambient chat
   * configuration, or `null` when no configuration is present.
   */
  protected readonly activeThreadId = computed(
    () => this.config?.threadId() ?? null,
  );

  /**
   * User-facing fetch-more error message from the dedicated fetch-more error
   * signal, or `null`. Drives the element's inline "couldn't load more — retry"
   * panel without disturbing the loaded list or the initial-list `error`.
   */
  protected readonly fetchMoreErrorMessage = computed(
    () => this.threads.fetchMoreError()?.message ?? null,
  );

  private readonly destroyRef = inject(DestroyRef);

  /**
   * Provider-less fallback open-state. Without a surrounding chat configuration
   * there is no shared open-state to bind to, so the wrapper keeps its own
   * local state. Starts CLOSED — matching the configuration's own default — so
   * the element does not spring open (and scroll-lock the page on mobile) on
   * load, and the element's `open-change` events still toggle it.
   */
  private readonly localDrawerOpen = signal(false);

  /**
   * The effective drawer open-state: the ambient chat configuration's
   * `drawerOpen` when present, else the provider-less {@link localDrawerOpen}.
   * Pushed onto the element's controlled `open` property in the effect below.
   */
  protected readonly drawerOpen = computed(() =>
    this.config ? this.config.drawerOpen() : this.localDrawerOpen(),
  );

  constructor() {
    defineCopilotKitThreadsDrawer();

    // Announce drawer presence to the surrounding chat configuration so a
    // future header launcher can render, and de-register on destroy. Mirrors
    // the React (`registerDrawer()` effect) and Vue (`onScopeDispose`) wrappers.
    const unregisterDrawer = this.config?.registerDrawer();
    if (unregisterDrawer) {
      this.destroyRef.onDestroy(unregisterDrawer);
    }

    // Push signal-derived values onto the element's JS properties every time
    // any reactive dependency changes. Using an effect (rather than template
    // bindings) is required because Lit elements accept object/boolean domains
    // only as JS properties, not as HTML attributes.
    effect(() => {
      const el = this.drawerRef()?.nativeElement;
      if (!el) return;
      el.threads = this.drawerThreads();
      // While the license is still resolving, force the loading state so the
      // element shows its spinner instead of an empty/locked body.
      el.loading = this.threads.isLoading() || this.licensePending();
      el.error = this.errorMessage();
      el.fetchMoreError = this.fetchMoreErrorMessage();
      el.activeThreadId = this.activeThreadId();
      el.hasMore = this.threads.hasMoreThreads();
      el.fetchingMore = this.threads.isFetchingMoreThreads();
      // Drive the element's controlled `open` from the (config-backed or local)
      // open-state so the element does not default open=true on load.
      el.open = this.drawerOpen();
      // Pending counts as licensed for rendering: the element shows the locked
      // view only when `licensed` is false, so keeping it true until the status
      // resolves prevents the locked view from flashing mid-resolution.
      el.licensed = this.licensed() || this.licensePending();
      if (this.label() !== undefined) el.label = this.label() as string;
      const licenseUrl = this.licenseUrl();
      if (licenseUrl !== undefined) el.licenseUrl = licenseUrl;
      // `collapsible` is a default-true boolean PROPERTY (like `licensed`);
      // leave the element's own default in place when the input is unset.
      const collapsible = this.collapsible();
      if (collapsible !== undefined) {
        // TODO(ENT-1051): drop the intersection cast once the published element
        // type declares `collapsible` (see the local CollapseChangeDetail note).
        (
          el as CopilotKitThreadsDrawerElement & { collapsible: boolean }
        ).collapsible = collapsible;
      }
    });
  }

  /**
   * Handles the `thread-selected` event from the drawer element.
   *
   * When a `threadSelectHandler` override is provided by the host, it is called
   * exclusively. Otherwise, the ambient chat configuration is driven directly so
   * a bare `<copilot-threads-drawer>` works without any host wiring.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<ThreadSelectedDetail>` to extract `threadId`.
   */
  protected onThreadSelected(event: Event): void {
    const { threadId } = (event as CustomEvent<ThreadSelectedDetail>).detail;
    const handler = this.threadSelectHandler();
    if (handler) {
      handler(threadId);
    } else {
      this.config?.setActiveThreadId(threadId, { explicit: true });
    }
    // Return focus to the chat input so keyboard users land in the composer.
    // Scope the lookup to this drawer's own chat (not document-global). Mirrors
    // the React (`findChatInput(...).focus()`) and Vue (`focusChatInput()`)
    // wrappers.
    findChatInput(this.drawerRef()?.nativeElement ?? null)?.focus();
  }

  /**
   * Handles the `open-change` event from the drawer element.
   *
   * Drives the ambient chat configuration's `setDrawerOpen` when present, else
   * the provider-less {@link localDrawerOpen} fallback — mirroring the React
   * and Vue wrappers so the element's open-state stays coordinated.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<OpenChangeDetail>` to extract `open`.
   */
  protected onOpenChange(event: Event): void {
    const { open } = (event as CustomEvent<OpenChangeDetail>).detail;
    if (this.config) {
      this.config.setDrawerOpen(open);
    } else {
      this.localDrawerOpen.set(open);
    }
  }

  /**
   * Handles the `new-thread` event from the drawer element.
   *
   * Always resets the core thread store to a fresh, non-explicit client-side
   * thread first. When a `newThreadHandler` override is provided by the host,
   * it is called exclusively. Otherwise, the ambient chat configuration is
   * driven directly so a bare `<copilot-threads-drawer>` works without any host wiring.
   */
  protected onNewThread(): void {
    this.threads.startNewThread();
    const handler = this.newThreadHandler();
    if (handler) {
      handler();
    } else {
      this.config?.startNewThread();
    }
  }

  /**
   * Handles the `archive` event from the drawer element.
   *
   * Delegates to the threads mutation and logs any failure to the console.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<ArchiveDetail>` to extract `threadId`.
   */
  protected onArchive(event: Event): void {
    const { threadId } = (event as CustomEvent<ArchiveDetail>).detail;
    this.threads.archiveThread(threadId).catch((err) => {
      console.error("CopilotThreadsDrawer: archiveThread failed", err);
    });
  }

  /**
   * Handles the `unarchive` event from the drawer element.
   *
   * Delegates to the threads mutation and logs any failure to the console.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<UnarchiveDetail>` to extract `threadId`.
   */
  protected onUnarchive(event: Event): void {
    const { threadId } = (event as CustomEvent<UnarchiveDetail>).detail;
    this.threads.unarchiveThread(threadId).catch((err) => {
      console.error("CopilotThreadsDrawer: unarchiveThread failed", err);
    });
  }

  /**
   * Handles the `delete` event from the drawer element.
   *
   * Deleting the active thread resets to a fresh, non-explicit thread so the
   * user is not stranded on a now-gone conversation. Archiving the active
   * thread keeps the user viewing it.
   *
   * The core `threads.startNewThread()` reset is always called when the deleted
   * thread was active. When a `newThreadHandler` override is provided by the
   * host, it is called exclusively; otherwise the ambient chat configuration is
   * driven directly.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<DeleteDetail>` to extract `threadId`.
   */
  protected onDelete(event: Event): void {
    const { threadId } = (event as CustomEvent<DeleteDetail>).detail;
    const wasActive = threadId === this.activeThreadId();
    this.threads
      .deleteThread(threadId)
      .then(() => {
        if (wasActive) {
          this.threads.startNewThread();
          const handler = this.newThreadHandler();
          if (handler) {
            handler();
          } else {
            this.config?.startNewThread();
          }
        }
      })
      .catch((err) => {
        console.error("CopilotThreadsDrawer: deleteThread failed", err);
      });
  }

  /**
   * Handles the `filter-change` event from the drawer element.
   *
   * The element owns the Active/All filter; on change we refetch so the list
   * reflects the server.
   */
  protected onFilterChange(): void {
    this.threads.refetchThreads();
  }

  /**
   * Handles the `collapse-change` event from the drawer element — re-emits the
   * new collapsed state through the component's `collapseChange` output so hosts
   * can observe (or persist) the drawer's collapsed state.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<CollapseChangeDetail>` to extract `collapsed`.
   */
  protected onCollapseChange(event: Event): void {
    const { collapsed } = (event as CustomEvent<CollapseChangeDetail>).detail;
    this.collapseChange.emit(collapsed);
  }

  /**
   * Handles the `retry` event from the drawer element.
   *
   * `scope` distinguishes an initial fetch retry from a fetch-more retry so
   * the correct pagination operation is invoked.
   *
   * @param event - The raw DOM event; cast to `CustomEvent<RetryDetail>` to extract `scope`.
   */
  protected onRetry(event: Event): void {
    const { scope } = (event as CustomEvent<RetryDetail>).detail;
    if (scope === "fetch-more") {
      this.threads.fetchMoreThreads();
    } else {
      this.threads.refetchThreads();
    }
  }

  /**
   * Handles the `load-more` event from the drawer element — advances pagination
   * by fetching the next page. No-op when there is no next page (the element
   * only surfaces the "Load more" control while `hasMoreThreads` is true).
   */
  protected onLoadMore(): void {
    this.threads.fetchMoreThreads();
  }

  /**
   * Handles the `licensed` event from the drawer element (Upgrade CTA click).
   *
   * The element performs its own default navigation to `licenseUrl`; this hook
   * lets the host observe the click (e.g. for telemetry) or drive a custom
   * upgrade flow when provided via `[onLicensed]`.
   */
  protected onLicensed(): void {
    this.licensedHandler()?.();
  }
}
