// packages/a2ui-renderer/src/react-renderer/a2ui-react/catalog/basic/components/Tabs.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { useState } from "react";
import { createReactComponent } from "../../../adapter";
import { TabsApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { LEAF_MARGIN } from "../utils";

// The type of a tab is deeply nested into the TabsApi schema, and
// it seems z.infer is not inferring it correctly (?). We use `any` for now.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type _Tab = any;

export const Tabs = createReactComponent(TabsApi, ({ props, buildChild }) => {
  const [selectedIndex, setSelectedIndex] = useState(0);

  const tabs = props.tabs || [];
  const activeTab = tabs[selectedIndex];

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        width: "100%",
        margin: LEAF_MARGIN,
      }}
    >
      <div
        style={{
          display: "flex",
          borderBottom: "1px solid #ccc",
          marginBottom: "8px",
        }}
      >
        {tabs.map((tab: _Tab, i: number) => (
          <button
            key={i}
            onClick={() => setSelectedIndex(i)}
            style={{
              padding: "8px 16px",
              border: "none",
              background: "none",
              borderBottom:
                selectedIndex === i
                  ? "2px solid var(--a2ui-primary-color, #007bff)"
                  : "none",
              fontWeight: selectedIndex === i ? "bold" : "normal",
              cursor: "pointer",
              color:
                selectedIndex === i
                  ? "var(--a2ui-primary-color, #007bff)"
                  : "inherit",
            }}
          >
            {tab.title}
          </button>
        ))}
      </div>
      <div style={{ flex: 1 }}>
        {activeTab ? buildChild(activeTab.child) : null}
      </div>
    </div>
  );
});

// examples/experiments/a2ui-private/original_a2ui_source/renderers/angular/src/lib/catalog/tabs.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input, signal } from '@angular/core';
import * as v0_8 from '@a2ui/web-lib/0.8';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';

@Component({
  selector: 'a2ui-tabs',
  imports: [Renderer],
  template: `
    @let tabs = this.tabs();
    @let selectedIndex = this.selectedIndex();

    <section [class]="theme.components.Tabs.container" [style]="theme.additionalStyles?.Tabs">
      <div [class]="theme.components.Tabs.element">
        @for (tab of tabs; track tab) {
          <button
            (click)="this.selectedIndex.set($index)"
            [disabled]="selectedIndex === $index"
            [class]="buttonClasses()[selectedIndex]">
            {{ resolvePrimitive(tab.title) }}
          </button>
        }
      </div>

      <ng-container
        a2ui-renderer
        [surfaceId]="surfaceId()!"
        [component]="tabs[selectedIndex].child"
      />
    </section>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
    }
  `,
})
export class Tabs extends DynamicComponent {
  protected selectedIndex = signal(0);
  readonly tabs = input.required<v0_8.Types.ResolvedTabItem[]>();

  protected readonly buttonClasses = computed(() => {
    const selectedIndex = this.selectedIndex();

    return this.tabs().map((_, index) => {
      return index === selectedIndex
        ? v0_8.Styles.merge(
            this.theme.components.Tabs.controls.all,
            this.theme.components.Tabs.controls.selected
          )
        : this.theme.components.Tabs.controls.all;
    });
  });
}
